package dev.dmigrate.driver.sqlite

import dev.dmigrate.core.model.*
import dev.dmigrate.driver.*
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import io.kotest.matchers.string.shouldStartWith

class SqliteDdlGeneratorTest : FunSpec({

    val generator = SqliteDdlGenerator()

    // ── Helper functions ────────────────────────────────────────────

    fun schema(
        tables: Map<String, TableDefinition> = emptyMap(),
        customTypes: Map<String, CustomTypeDefinition> = emptyMap(),
        sequences: Map<String, SequenceDefinition> = emptyMap(),
        views: Map<String, ViewDefinition> = emptyMap(),
        functions: Map<String, FunctionDefinition> = emptyMap(),
        procedures: Map<String, ProcedureDefinition> = emptyMap(),
        triggers: Map<String, TriggerDefinition> = emptyMap()
    ) = SchemaDefinition(
        name = "test-schema",
        version = "1.0.0",
        customTypes = customTypes,
        tables = tables,
        sequences = sequences,
        views = views,
        functions = functions,
        procedures = procedures,
        triggers = triggers
    )

    fun table(
        columns: Map<String, ColumnDefinition> = emptyMap(),
        primaryKey: List<String> = emptyList(),
        indices: List<IndexDefinition> = emptyList(),
        constraints: List<ConstraintDefinition> = emptyList(),
        partitioning: PartitionConfig? = null
    ) = TableDefinition(
        columns = columns,
        primaryKey = primaryKey,
        indices = indices,
        constraints = constraints,
        partitioning = partitioning
    )

    fun col(
        type: NeutralType,
        required: Boolean = false,
        unique: Boolean = false,
        default: DefaultValue? = null,
        references: ReferenceDefinition? = null
    ) = ColumnDefinition(
        type = type,
        required = required,
        unique = unique,
        default = default,
        references = references
    )

    fun ref(
        table: String,
        column: String,
        onDelete: ReferentialAction? = null,
        onUpdate: ReferentialAction? = null
    ) = ReferenceDefinition(table, column, onDelete, onUpdate)

    /** Extracts the rendered SQL from DdlResult, skipping the header comment. */
    fun DdlResult.tableSql(): String {
        // Filter to actual CREATE TABLE statements
        return statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE TABLE") }
    }

    /** Collects all SQL statements from a DdlResult (excluding header). */
    fun DdlResult.allSql(): List<String> =
        statements.map { it.sql.trim() }.filter { !it.startsWith("-- Generated by") && !it.startsWith("-- Source:") }

    // ── 1. Simple table with double-quoted identifiers ──────────────

    test("simple table uses double-quoted identifiers and CREATE TABLE") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "name" to col(NeutralType.Text(maxLength = 100), required = true),
                        "email" to col(NeutralType.Email, required = true, unique = true)
                    )
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "CREATE TABLE \"users\""
        sql shouldContain "\"name\" TEXT NOT NULL"
        sql shouldContain "\"email\" TEXT NOT NULL UNIQUE"
    }

    // ── 2. Identifier type produces INTEGER PRIMARY KEY AUTOINCREMENT ─

    test("identifier column produces INTEGER PRIMARY KEY AUTOINCREMENT without separate PK clause") {
        val s = schema(
            tables = mapOf(
                "items" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "label" to col(NeutralType.Text(), required = true)
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT"
        sql shouldNotContain "PRIMARY KEY (\"id\")"
    }

    // ── 3. Composite primary key (non-identifier) ───────────────────

    test("composite primary key emits separate PRIMARY KEY clause") {
        val s = schema(
            tables = mapOf(
                "order_items" to table(
                    columns = mapOf(
                        "order_id" to col(NeutralType.Integer, required = true),
                        "product_id" to col(NeutralType.Integer, required = true),
                        "quantity" to col(NeutralType.Integer, required = true)
                    ),
                    primaryKey = listOf("order_id", "product_id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "PRIMARY KEY (\"order_id\", \"product_id\")"
    }

    // ── 4. Inline foreign key with ON DELETE action ─────────────────

    test("inline foreign key produces REFERENCES with ON DELETE action") {
        val s = schema(
            tables = mapOf(
                "categories" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                ),
                "products" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "category_id" to col(
                            NeutralType.Integer,
                            required = true,
                            references = ref("categories", "id", onDelete = ReferentialAction.CASCADE)
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val productsSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("\"products\"") && it.startsWith("CREATE TABLE") }

        productsSql shouldContain "REFERENCES \"categories\"(\"id\") ON DELETE CASCADE"
    }

    // ── 5. Enum with inline values produces TEXT + CHECK ─────────────

    test("enum with inline values produces TEXT with CHECK constraint") {
        val s = schema(
            tables = mapOf(
                "tasks" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "status" to col(
                            NeutralType.Enum(values = listOf("open", "in_progress", "done")),
                            required = true
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"status\" TEXT NOT NULL CHECK (\"status\" IN ('open', 'in_progress', 'done'))"
    }

    // ── 6. Enum with ref_type resolves values from customTypes ──────

    test("enum with ref_type resolves values from custom types and produces CHECK constraint") {
        val s = schema(
            customTypes = mapOf(
                "priority_level" to CustomTypeDefinition(
                    kind = CustomTypeKind.ENUM,
                    values = listOf("low", "medium", "high", "critical")
                )
            ),
            tables = mapOf(
                "tickets" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "priority" to col(
                            NeutralType.Enum(refType = "priority_level"),
                            required = true
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"priority\" TEXT NOT NULL CHECK (\"priority\" IN ('low', 'medium', 'high', 'critical'))"
    }

    // ── 7. Composite custom type is skipped with E054 ───────────────

    test("composite custom type emits E054 action required note") {
        val s = schema(
            customTypes = mapOf(
                "address" to CustomTypeDefinition(
                    kind = CustomTypeKind.COMPOSITE,
                    fields = mapOf(
                        "street" to col(NeutralType.Text()),
                        "city" to col(NeutralType.Text())
                    )
                )
            )
        )
        val result = generator.generate(s)
        val notes = result.notes

        notes.any { it.code == "E054" && it.objectName == "address" } shouldBe true
        notes.any { it.message.contains("Composite type") } shouldBe true
    }

    // ── 8. Sequence is skipped with E056 ────────────────────────────

    test("sequence is skipped with E056 and added to skippedObjects") {
        val s = schema(
            sequences = mapOf(
                "order_seq" to SequenceDefinition(start = 1000, increment = 1)
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "sequence" && it.name == "order_seq" } shouldBe true
        result.notes.any { it.code == "E056" && it.objectName == "order_seq" } shouldBe true
    }

    // ── 9. Partitioning is skipped with E055 ────────────────────────

    test("table with partitioning emits E055 warning") {
        val s = schema(
            tables = mapOf(
                "events" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "created_at" to col(NeutralType.DateTime(), required = true)
                    ),
                    primaryKey = listOf("id"),
                    partitioning = PartitionConfig(
                        type = PartitionType.RANGE,
                        key = listOf("created_at")
                    )
                )
            )
        )
        val result = generator.generate(s)
        val notes = result.notes

        notes.any { it.code == "E055" && it.message.contains("partitioning") } shouldBe true
    }

    // ── 10. HASH index emits W102 warning and is skipped ────────────

    test("HASH index emits W102 warning and is skipped") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "email" to col(NeutralType.Email, required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_users_email",
                            columns = listOf("email"),
                            type = IndexType.HASH
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val notes = result.notes

        notes.any { it.code == "W102" && it.objectName == "idx_users_email" } shouldBe true
        // The actual CREATE INDEX should not appear
        result.statements.none {
            it.sql.trim().startsWith("CREATE INDEX \"idx_users_email\"") ||
                it.sql.trim().startsWith("CREATE UNIQUE INDEX \"idx_users_email\"")
        } shouldBe true
    }

    // ── 11. GIN/GIST/BRIN indices emit W102 warning ─────────────────

})
