package dev.dmigrate.driver.sqlite

import dev.dmigrate.core.model.*
import dev.dmigrate.driver.*
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import io.kotest.matchers.string.shouldStartWith

class SqliteDdlGeneratorTestPart2 : FunSpec({

    val generator = SqliteDdlGenerator()

    // ── Helper functions ────────────────────────────────────────────

    fun schema(
        tables: Map<String, TableDefinition> = emptyMap(),
        customTypes: Map<String, CustomTypeDefinition> = emptyMap(),
        sequences: Map<String, SequenceDefinition> = emptyMap(),
        views: Map<String, ViewDefinition> = emptyMap(),
        functions: Map<String, FunctionDefinition> = emptyMap(),
        procedures: Map<String, ProcedureDefinition> = emptyMap(),
        triggers: Map<String, TriggerDefinition> = emptyMap()
    ) = SchemaDefinition(
        name = "test-schema",
        version = "1.0.0",
        customTypes = customTypes,
        tables = tables,
        sequences = sequences,
        views = views,
        functions = functions,
        procedures = procedures,
        triggers = triggers
    )

    fun table(
        columns: Map<String, ColumnDefinition> = emptyMap(),
        primaryKey: List<String> = emptyList(),
        indices: List<IndexDefinition> = emptyList(),
        constraints: List<ConstraintDefinition> = emptyList(),
        partitioning: PartitionConfig? = null
    ) = TableDefinition(
        columns = columns,
        primaryKey = primaryKey,
        indices = indices,
        constraints = constraints,
        partitioning = partitioning
    )

    fun col(
        type: NeutralType,
        required: Boolean = false,
        unique: Boolean = false,
        default: DefaultValue? = null,
        references: ReferenceDefinition? = null
    ) = ColumnDefinition(
        type = type,
        required = required,
        unique = unique,
        default = default,
        references = references
    )

    fun ref(
        table: String,
        column: String,
        onDelete: ReferentialAction? = null,
        onUpdate: ReferentialAction? = null
    ) = ReferenceDefinition(table, column, onDelete, onUpdate)

    /** Extracts the rendered SQL from DdlResult, skipping the header comment. */
    fun DdlResult.tableSql(): String {
        // Filter to actual CREATE TABLE statements
        return statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE TABLE") }
    }

    /** Collects all SQL statements from a DdlResult (excluding header). */
    fun DdlResult.allSql(): List<String> =
        statements.map { it.sql.trim() }.filter { !it.startsWith("-- Generated by") && !it.startsWith("-- Source:") }

    // ── 1. Simple table with double-quoted identifiers ──────────────


    test("trigger with null source dialect produces CREATE TRIGGER") {
        val s = schema(
            tables = mapOf(
                "items" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                )
            ),
            triggers = mapOf(
                "trg_items_insert" to TriggerDefinition(
                    table = "items",
                    event = TriggerEvent.INSERT,
                    timing = TriggerTiming.BEFORE,
                    forEach = TriggerForEach.ROW,
                    condition = "NEW.id > 0",
                    body = "    SELECT RAISE(ABORT, 'invalid id');"
                )
            )
        )
        val result = generator.generate(s)
        val triggerSql = result.statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE TRIGGER") }

        triggerSql shouldContain "CREATE TRIGGER \"trg_items_insert\""
        triggerSql shouldContain "BEFORE INSERT ON \"items\""
        triggerSql shouldContain "WHEN NEW.id > 0"
        triggerSql shouldContain "BEGIN"
        triggerSql shouldContain "END;"
    }

    // ── 19. Trigger with different source_dialect is skipped with E053

    test("trigger with non-sqlite source dialect is skipped with E053") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                )
            ),
            triggers = mapOf(
                "trg_pg_notify" to TriggerDefinition(
                    table = "users",
                    event = TriggerEvent.INSERT,
                    timing = TriggerTiming.AFTER,
                    body = "PERFORM pg_notify('user_created', NEW.id::text);",
                    sourceDialect = "postgresql"
                )
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "trigger" && it.name == "trg_pg_notify" } shouldBe true
        result.notes.any { it.code == "E053" && it.objectName == "trg_pg_notify" } shouldBe true
    }

    // ── 20. Decimal type maps to REAL with W200 precision warning ───

    test("decimal column maps to REAL with W200 precision loss warning") {
        val s = schema(
            tables = mapOf(
                "invoices" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "amount" to col(NeutralType.Decimal(precision = 18, scale = 4), required = true)
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"amount\" REAL NOT NULL"
        result.notes.any {
            it.code == "W200" && it.objectName == "invoices.amount" && it.message.contains("Decimal(18,4)")
        } shouldBe true
    }

    // ── 21. Boolean default renders as 1 / 0 ────────────────────────

    test("boolean column with default true renders DEFAULT 1") {
        val s = schema(
            tables = mapOf(
                "settings" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "active" to col(
                            NeutralType.BooleanType,
                            required = true,
                            default = DefaultValue.BooleanLiteral(true)
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"active\" INTEGER NOT NULL DEFAULT 1"
    }

    test("boolean column with default false renders DEFAULT 0") {
        val s = schema(
            tables = mapOf(
                "settings" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "disabled" to col(
                            NeutralType.BooleanType,
                            required = true,
                            default = DefaultValue.BooleanLiteral(false)
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"disabled\" INTEGER NOT NULL DEFAULT 0"
    }

    // ── 22. Datetime default renders (datetime('now')) ───────────────

    test("datetime column with current_timestamp default renders datetime now") {
        val s = schema(
            tables = mapOf(
                "events" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "created_at" to col(
                            NeutralType.DateTime(),
                            required = true,
                            default = DefaultValue.FunctionCall("current_timestamp")
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "DEFAULT (datetime('now'))"
    }

    // ── 23. Rollback generates DROP statements ──────────────────────

    test("rollback generates DROP TABLE statement") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "name" to col(NeutralType.Text(), required = true)
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generateRollback(s)
        val dropSql = result.statements.map { it.sql.trim() }

        dropSql.any { it.startsWith("DROP TABLE IF EXISTS \"users\"") } shouldBe true
    }

    test("rollback generates DROP VIEW for IF NOT EXISTS views") {
        val s = schema(
            views = mapOf(
                "recent_events" to ViewDefinition(
                    query = "SELECT * FROM events ORDER BY created_at DESC LIMIT 100"
                )
            )
        )
        val result = generator.generateRollback(s)
        val dropSql = result.statements.map { it.sql.trim() }

        dropSql.any { it.startsWith("DROP VIEW IF EXISTS \"recent_events\"") } shouldBe true
    }

    test("rollback generates DROP INDEX for BTREE indices") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "email" to col(NeutralType.Email, required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_users_email",
                            columns = listOf("email"),
                            type = IndexType.BTREE
                        )
                    )
                )
            )
        )
        val result = generator.generateRollback(s)
        val dropSql = result.statements.map { it.sql.trim() }

        dropSql.any { it.startsWith("DROP INDEX IF EXISTS \"idx_users_email\"") } shouldBe true
    }

    test("rollback generates DROP TRIGGER for sqlite triggers") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                )
            ),
            triggers = mapOf(
                "trg_users_audit" to TriggerDefinition(
                    table = "users",
                    event = TriggerEvent.INSERT,
                    timing = TriggerTiming.AFTER,
                    body = "    INSERT INTO audit_log(action) VALUES ('insert');",
                    sourceDialect = "sqlite"
                )
            )
        )
        val result = generator.generateRollback(s)
        val dropSql = result.statements.map { it.sql.trim() }

        dropSql.any { it.startsWith("DROP TRIGGER IF EXISTS \"trg_users_audit\"") } shouldBe true
    }

    // ── 24. No table options (ENGINE, CHARSET) ──────────────────────

    test("generated DDL does not contain ENGINE or CHARSET table options") {
        val s = schema(
            tables = mapOf(
                "simple" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "value" to col(NeutralType.Text())
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val rendered = result.render()

        rendered shouldNotContain "ENGINE"
        rendered shouldNotContain "CHARSET"
        rendered shouldNotContain "COLLATE"
        rendered shouldNotContain "DEFAULT CHARSET"
    }

    // ── Additional edge-case tests ──────────────────────────────────

    test("dialect is SQLITE") {
        generator.dialect shouldBe DatabaseDialect.SQLITE
    }

    test("header contains schema name and target sqlite") {
        val s = schema()
        val result = generator.generate(s)
        val header = result.statements.first().sql

        header shouldContain "d-migrate"
        header shouldContain "test-schema"
        header shouldContain "sqlite"
    }

    test("enum with ref_type but no custom type definition still produces TEXT without CHECK") {
        val s = schema(
            tables = mapOf(
                "records" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "category" to col(
                            NeutralType.Enum(refType = "missing_type"),
                            required = true
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"category\" TEXT NOT NULL"
        sql shouldNotContain "CHECK"
    }

    test("inline foreign key with ON UPDATE action") {
        val s = schema(
            tables = mapOf(
                "parents" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                ),
                "children" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "parent_id" to col(
                            NeutralType.Integer,
                            references = ref(
                                "parents", "id",
                                onDelete = ReferentialAction.SET_NULL,
                                onUpdate = ReferentialAction.CASCADE
                            )
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val childrenSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("\"children\"") && it.startsWith("CREATE TABLE") }

        childrenSql shouldContain "REFERENCES \"parents\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE"
    }

    test("view with incompatible source dialect is transformed and generated") {
        val s = schema(
            views = mapOf(
                "pg_view" to ViewDefinition(
                    query = "SELECT NOW() FROM orders",
                    sourceDialect = "postgresql"
                )
            )
        )
        val result = generator.generate(s)

        result.render() shouldContain "CREATE VIEW IF NOT EXISTS \"pg_view\" AS"
        result.render() shouldContain "SELECT datetime('now') FROM orders;"
        result.skippedObjects.any { it.type == "view" && it.name == "pg_view" } shouldBe false
        result.notes.any { it.code == "E053" && it.objectName == "pg_view" } shouldBe false
    }

    test("index without explicit name gets auto-generated name") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "name" to col(NeutralType.Text(), required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            columns = listOf("name"),
                            type = IndexType.BTREE
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val indexSql = result.statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE INDEX") }

        indexSql shouldContain "idx_users_name"
    }

    test("trigger with no body is skipped") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                )
            ),
            triggers = mapOf(
                "trg_empty" to TriggerDefinition(
                    table = "users",
                    event = TriggerEvent.INSERT,
                    timing = TriggerTiming.AFTER,
                    body = null
                )
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "trigger" && it.name == "trg_empty" } shouldBe true
        result.notes.any { it.code == "E053" && it.objectName == "trg_empty" } shouldBe true
    }

    test("view with no query is skipped") {
        val s = schema(
            views = mapOf(
                "empty_view" to ViewDefinition(query = null)
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "view" && it.name == "empty_view" } shouldBe true
    }

    test("domain custom type emits informational note") {
        val s = schema(
            customTypes = mapOf(
                "positive_int" to CustomTypeDefinition(
                    kind = CustomTypeKind.DOMAIN,
                    baseType = "integer",
                    check = "VALUE > 0"
                )
            )
        )
        val result = generator.generate(s)
        val notes = result.notes

        notes.any { it.code == "I001" && it.objectName == "positive_int" } shouldBe true
    }

    test("enum custom type emits informational note") {
        val s = schema(
            customTypes = mapOf(
                "status" to CustomTypeDefinition(
                    kind = CustomTypeKind.ENUM,
                    values = listOf("active", "inactive")
                )
            )
        )
        val result = generator.generate(s)
        val notes = result.notes

        notes.any { it.code == "I001" && it.objectName == "status" } shouldBe true
    }

    test("constraint FOREIGN_KEY clause generates correctly") {
        val s = schema(
            tables = mapOf(
                "departments" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                ),
                "employees" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "dept_id" to col(NeutralType.Integer, required = true)
                    ),
                    primaryKey = listOf("id"),
                    constraints = listOf(
                        ConstraintDefinition(
                            name = "fk_emp_dept",
                            type = ConstraintType.FOREIGN_KEY,
                            columns = listOf("dept_id"),
                            references = ConstraintReferenceDefinition(
                                table = "departments",
                                columns = listOf("id"),
                                onDelete = ReferentialAction.CASCADE
                            )
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val empSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("\"employees\"") && it.startsWith("CREATE TABLE") }

        empSql shouldContain "CONSTRAINT \"fk_emp_dept\" FOREIGN KEY (\"dept_id\") REFERENCES \"departments\" (\"id\") ON DELETE CASCADE"
    }

    test("constraint CHECK clause generates correctly") {
        val s = schema(
            tables = mapOf(
                "products" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "price" to col(NeutralType.Decimal(10, 2), required = true)
                    ),
                    primaryKey = listOf("id"),
                    constraints = listOf(
                        ConstraintDefinition(
                            name = "chk_positive_price",
                            type = ConstraintType.CHECK,
                            expression = "price > 0"
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "CONSTRAINT \"chk_positive_price\" CHECK (price > 0)"
    }

})
