package dev.dmigrate.driver.sqlite

import dev.dmigrate.core.model.*
import dev.dmigrate.driver.*
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import io.kotest.matchers.string.shouldStartWith

class SqliteDdlGeneratorTestPart2b : FunSpec({

    val generator = SqliteDdlGenerator()

    // ── Helper functions ────────────────────────────────────────────

    fun schema(
        tables: Map<String, TableDefinition> = emptyMap(),
        customTypes: Map<String, CustomTypeDefinition> = emptyMap(),
        sequences: Map<String, SequenceDefinition> = emptyMap(),
        views: Map<String, ViewDefinition> = emptyMap(),
        functions: Map<String, FunctionDefinition> = emptyMap(),
        procedures: Map<String, ProcedureDefinition> = emptyMap(),
        triggers: Map<String, TriggerDefinition> = emptyMap()
    ) = SchemaDefinition(
        name = "test-schema",
        version = "1.0.0",
        customTypes = customTypes,
        tables = tables,
        sequences = sequences,
        views = views,
        functions = functions,
        procedures = procedures,
        triggers = triggers
    )

    fun table(
        columns: Map<String, ColumnDefinition> = emptyMap(),
        primaryKey: List<String> = emptyList(),
        indices: List<IndexDefinition> = emptyList(),
        constraints: List<ConstraintDefinition> = emptyList(),
        partitioning: PartitionConfig? = null
    ) = TableDefinition(
        columns = columns,
        primaryKey = primaryKey,
        indices = indices,
        constraints = constraints,
        partitioning = partitioning
    )

    fun col(
        type: NeutralType,
        required: Boolean = false,
        unique: Boolean = false,
        default: DefaultValue? = null,
        references: ReferenceDefinition? = null
    ) = ColumnDefinition(
        type = type,
        required = required,
        unique = unique,
        default = default,
        references = references
    )

    fun ref(
        table: String,
        column: String,
        onDelete: ReferentialAction? = null,
        onUpdate: ReferentialAction? = null
    ) = ReferenceDefinition(table, column, onDelete, onUpdate)

    /** Extracts the rendered SQL from DdlResult, skipping the header comment. */
    fun DdlResult.tableSql(): String {
        // Filter to actual CREATE TABLE statements
        return statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE TABLE") }
    }

    /** Collects all SQL statements from a DdlResult (excluding header). */
    fun DdlResult.allSql(): List<String> =
        statements.map { it.sql.trim() }.filter { !it.startsWith("-- Generated by") && !it.startsWith("-- Source:") }

    // ── 1. Simple table with double-quoted identifiers ──────────────


    test("GIN index emits W102 warning and is skipped") {
        val s = schema(
            tables = mapOf(
                "docs" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "content" to col(NeutralType.Json)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_docs_content",
                            columns = listOf("content"),
                            type = IndexType.GIN
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)

        result.notes.any { it.code == "W102" && it.message.contains("GIN") } shouldBe true
    }

    test("GIST index emits W102 warning and is skipped") {
        val s = schema(
            tables = mapOf(
                "locations" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "geom" to col(NeutralType.Text())
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_locations_geom",
                            columns = listOf("geom"),
                            type = IndexType.GIST
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)

        result.notes.any { it.code == "W102" && it.message.contains("GIST") } shouldBe true
    }

    test("BRIN index emits W102 warning and is skipped") {
        val s = schema(
            tables = mapOf(
                "logs" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "ts" to col(NeutralType.DateTime())
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_logs_ts",
                            columns = listOf("ts"),
                            type = IndexType.BRIN
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)

        result.notes.any { it.code == "W102" && it.message.contains("BRIN") } shouldBe true
    }

    // ── 12. BTREE index generates CREATE INDEX ──────────────────────

    test("BTREE index generates CREATE INDEX statement") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "email" to col(NeutralType.Email, required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_users_email",
                            columns = listOf("email"),
                            type = IndexType.BTREE
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val indexSql = result.statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE INDEX") }

        indexSql shouldBe "CREATE INDEX \"idx_users_email\" ON \"users\" (\"email\");"
    }

    test("BTREE unique index generates CREATE UNIQUE INDEX") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "email" to col(NeutralType.Email, required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_users_email_uniq",
                            columns = listOf("email"),
                            type = IndexType.BTREE,
                            unique = true
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val indexSql = result.statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE UNIQUE INDEX") }

        indexSql shouldBe "CREATE UNIQUE INDEX \"idx_users_email_uniq\" ON \"users\" (\"email\");"
    }

    // ── 13. Circular FK produces E019 error and skipped objects ──────

    test("circular foreign keys produce E019 error and are added to skipped objects") {
        val s = schema(
            tables = mapOf(
                "table_a" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "b_id" to col(
                            NeutralType.Integer,
                            references = ref("table_b", "id")
                        )
                    ),
                    primaryKey = listOf("id")
                ),
                "table_b" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "a_id" to col(
                            NeutralType.Integer,
                            references = ref("table_a", "id")
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)

        // Circular FK edges should produce E019 notes
        result.notes.any { it.code == "E019" } shouldBe true

        // Should have skipped objects of type "foreign_key"
        result.skippedObjects.any { it.type == "foreign_key" } shouldBe true
    }

    // ── 14. View uses CREATE VIEW IF NOT EXISTS (no OR REPLACE) ─────

    test("view produces CREATE VIEW IF NOT EXISTS without OR REPLACE") {
        val s = schema(
            views = mapOf(
                "active_users" to ViewDefinition(
                    query = "SELECT * FROM users WHERE active = 1"
                )
            )
        )
        val result = generator.generate(s)
        val viewSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("VIEW") && !it.startsWith("--") }

        viewSql shouldStartWith "CREATE VIEW IF NOT EXISTS \"active_users\""
        viewSql shouldNotContain "OR REPLACE"
        viewSql shouldContain "SELECT * FROM users WHERE active = 1"
    }

    // ── 15. Materialized view becomes regular VIEW + W103 warning ───

    test("materialized view is created as regular VIEW with W103 warning") {
        val s = schema(
            views = mapOf(
                "stats_summary" to ViewDefinition(
                    query = "SELECT count(*) as cnt FROM events",
                    materialized = true
                )
            )
        )
        val result = generator.generate(s)
        val viewSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("VIEW") && !it.startsWith("--") }

        viewSql shouldStartWith "CREATE VIEW IF NOT EXISTS \"stats_summary\""
        viewSql shouldNotContain "MATERIALIZED"
        result.notes.any { it.code == "W103" && it.objectName == "stats_summary" } shouldBe true
    }

    // ── 16. Function is skipped with E054 ───────────────────────────

    test("function is skipped with E054 and added to skippedObjects") {
        val s = schema(
            functions = mapOf(
                "calculate_total" to FunctionDefinition(
                    body = "RETURN a + b;",
                    language = "sql"
                )
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "function" && it.name == "calculate_total" } shouldBe true
        result.notes.any { it.code == "E054" && it.objectName == "calculate_total" } shouldBe true
    }

    // ── 17. Procedure is skipped with E054 ──────────────────────────

    test("procedure is skipped with E054 and added to skippedObjects") {
        val s = schema(
            procedures = mapOf(
                "cleanup_old_data" to ProcedureDefinition(
                    body = "DELETE FROM logs WHERE created_at < date('now', '-30 days');",
                    language = "sql"
                )
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "procedure" && it.name == "cleanup_old_data" } shouldBe true
        result.notes.any { it.code == "E054" && it.objectName == "cleanup_old_data" } shouldBe true
    }

    // ── 18. Trigger with sqlite source_dialect produces CREATE TRIGGER

    test("trigger with sqlite source dialect produces CREATE TRIGGER with BEGIN...END") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "updated_at" to col(NeutralType.DateTime())
                    ),
                    primaryKey = listOf("id")
                )
            ),
            triggers = mapOf(
                "trg_users_updated" to TriggerDefinition(
                    table = "users",
                    event = TriggerEvent.UPDATE,
                    timing = TriggerTiming.AFTER,
                    forEach = TriggerForEach.ROW,
                    body = "    UPDATE users SET updated_at = datetime('now') WHERE id = NEW.id;",
                    sourceDialect = "sqlite"
                )
            )
        )
        val result = generator.generate(s)
        val triggerSql = result.statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE TRIGGER") }

        triggerSql shouldContain "CREATE TRIGGER \"trg_users_updated\""
        triggerSql shouldContain "AFTER UPDATE ON \"users\""
        triggerSql shouldContain "FOR EACH ROW"
        triggerSql shouldContain "BEGIN"
        triggerSql shouldContain "END;"
    }

})
