package dev.dmigrate.driver.sqlite

import dev.dmigrate.core.model.*
import dev.dmigrate.driver.*
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import io.kotest.matchers.string.shouldStartWith

class SqliteDdlGeneratorTestPart3 : FunSpec({

    val generator = SqliteDdlGenerator()

    // ── Helper functions ────────────────────────────────────────────

    fun schema(
        tables: Map<String, TableDefinition> = emptyMap(),
        customTypes: Map<String, CustomTypeDefinition> = emptyMap(),
        sequences: Map<String, SequenceDefinition> = emptyMap(),
        views: Map<String, ViewDefinition> = emptyMap(),
        functions: Map<String, FunctionDefinition> = emptyMap(),
        procedures: Map<String, ProcedureDefinition> = emptyMap(),
        triggers: Map<String, TriggerDefinition> = emptyMap()
    ) = SchemaDefinition(
        name = "test-schema",
        version = "1.0.0",
        customTypes = customTypes,
        tables = tables,
        sequences = sequences,
        views = views,
        functions = functions,
        procedures = procedures,
        triggers = triggers
    )

    fun table(
        columns: Map<String, ColumnDefinition> = emptyMap(),
        primaryKey: List<String> = emptyList(),
        indices: List<IndexDefinition> = emptyList(),
        constraints: List<ConstraintDefinition> = emptyList(),
        partitioning: PartitionConfig? = null
    ) = TableDefinition(
        columns = columns,
        primaryKey = primaryKey,
        indices = indices,
        constraints = constraints,
        partitioning = partitioning
    )

    fun col(
        type: NeutralType,
        required: Boolean = false,
        unique: Boolean = false,
        default: DefaultValue? = null,
        references: ReferenceDefinition? = null
    ) = ColumnDefinition(
        type = type,
        required = required,
        unique = unique,
        default = default,
        references = references
    )

    fun ref(
        table: String,
        column: String,
        onDelete: ReferentialAction? = null,
        onUpdate: ReferentialAction? = null
    ) = ReferenceDefinition(table, column, onDelete, onUpdate)

    /** Extracts the rendered SQL from DdlResult, skipping the header comment. */
    fun DdlResult.tableSql(): String {
        // Filter to actual CREATE TABLE statements
        return statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE TABLE") }
    }

    /** Collects all SQL statements from a DdlResult (excluding header). */
    fun DdlResult.allSql(): List<String> =
        statements.map { it.sql.trim() }.filter { !it.startsWith("-- Generated by") && !it.startsWith("-- Source:") }

    // ── 1. Simple table with double-quoted identifiers ──────────────


    test("constraint UNIQUE clause generates correctly") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "email" to col(NeutralType.Email, required = true),
                        "username" to col(NeutralType.Text(), required = true)
                    ),
                    primaryKey = listOf("id"),
                    constraints = listOf(
                        ConstraintDefinition(
                            name = "uq_email_username",
                            type = ConstraintType.UNIQUE,
                            columns = listOf("email", "username")
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "CONSTRAINT \"uq_email_username\" UNIQUE (\"email\", \"username\")"
    }

    test("constraint EXCLUDE is not supported and emits E054") {
        val s = schema(
            tables = mapOf(
                "reservations" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "room" to col(NeutralType.Integer, required = true)
                    ),
                    primaryKey = listOf("id"),
                    constraints = listOf(
                        ConstraintDefinition(
                            name = "excl_room_time",
                            type = ConstraintType.EXCLUDE,
                            expression = "room WITH ="
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)

        result.notes.any { it.code == "E054" && it.objectName == "excl_room_time" } shouldBe true
    }

    test("multiple tables with foreign key dependencies are topologically sorted") {
        val s = schema(
            tables = mapOf(
                "orders" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "customer_id" to col(
                            NeutralType.Integer,
                            required = true,
                            references = ref("customers", "id")
                        )
                    ),
                    primaryKey = listOf("id")
                ),
                "customers" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "name" to col(NeutralType.Text(), required = true)
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val createTables = result.statements
            .map { it.sql.trim() }
            .filter { it.startsWith("CREATE TABLE") }

        // customers should appear before orders because orders depends on customers
        val customersIdx = createTables.indexOfFirst { it.contains("\"customers\"") }
        val ordersIdx = createTables.indexOfFirst { it.contains("\"orders\"") }

        (customersIdx < ordersIdx) shouldBe true
    }

    test("rollback statements are in reverse order") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "name" to col(NeutralType.Text())
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_users_name",
                            columns = listOf("name"),
                            type = IndexType.BTREE
                        )
                    )
                )
            )
        )
        val result = generator.generateRollback(s)
        val dropStatements = result.statements.map { it.sql.trim() }

        // Index should be dropped before the table (reverse of create order)
        val dropIndexIdx = dropStatements.indexOfFirst { it.contains("DROP INDEX") }
        val dropTableIdx = dropStatements.indexOfFirst { it.contains("DROP TABLE") }

        (dropIndexIdx < dropTableIdx) shouldBe true
    }

    test("empty schema generates only header") {
        val s = schema()
        val result = generator.generate(s)

        result.statements shouldHaveSize 1
        result.statements.first().sql shouldContain "Generated by d-migrate"
        result.skippedObjects.shouldBeEmpty()
    }

    test("enum column with inline values and default value") {
        val s = schema(
            tables = mapOf(
                "tasks" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "priority" to col(
                            NeutralType.Enum(values = listOf("low", "medium", "high")),
                            required = true,
                            default = DefaultValue.StringLiteral("medium")
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"priority\" TEXT NOT NULL DEFAULT 'medium' CHECK (\"priority\" IN ('low', 'medium', 'high'))"
    }

    test("string default value with single quote is escaped") {
        val s = schema(
            tables = mapOf(
                "notes" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "content" to col(
                            NeutralType.Text(),
                            default = DefaultValue.StringLiteral("it's a test")
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "DEFAULT 'it''s a test'"
    }

    test("identifier column without autoIncrement still uses INTEGER PRIMARY KEY AUTOINCREMENT") {
        // NeutralType.Identifier defaults autoIncrement=false, but in the generator
        // the special path only fires when autoIncrement is true.
        val s = schema(
            tables = mapOf(
                "items" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = false)),
                        "name" to col(NeutralType.Text())
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        // With autoIncrement=false, it still maps to INTEGER PRIMARY KEY AUTOINCREMENT via typeMapper
        // but uses the default columnSql path since the special branch checks autoIncrement
        sql shouldContain "\"id\""
    }

    test("multiple indices on same table are all generated") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "email" to col(NeutralType.Email, required = true),
                        "name" to col(NeutralType.Text(), required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_users_email",
                            columns = listOf("email"),
                            type = IndexType.BTREE,
                            unique = true
                        ),
                        IndexDefinition(
                            name = "idx_users_name",
                            columns = listOf("name"),
                            type = IndexType.BTREE
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val indexStatements = result.statements
            .map { it.sql.trim() }
            .filter { it.startsWith("CREATE INDEX") || it.startsWith("CREATE UNIQUE INDEX") }

        indexStatements shouldHaveSize 2
    }

    test("multi-column BTREE index generates correct SQL") {
        val s = schema(
            tables = mapOf(
                "events" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "user_id" to col(NeutralType.Integer, required = true),
                        "created_at" to col(NeutralType.DateTime(), required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_events_user_date",
                            columns = listOf("user_id", "created_at"),
                            type = IndexType.BTREE
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val indexSql = result.statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE INDEX") }

        indexSql shouldBe "CREATE INDEX \"idx_events_user_date\" ON \"events\" (\"user_id\", \"created_at\");"
    }

    test("enum with ref_type and inline reference generates REFERENCES clause") {
        val s = schema(
            customTypes = mapOf(
                "status_type" to CustomTypeDefinition(
                    kind = CustomTypeKind.ENUM,
                    values = listOf("active", "inactive")
                )
            ),
            tables = mapOf(
                "statuses" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                ),
                "accounts" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "status" to col(
                            NeutralType.Enum(refType = "status_type"),
                            required = true,
                            references = ref("statuses", "id", onDelete = ReferentialAction.RESTRICT)
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val accountsSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("\"accounts\"") && it.startsWith("CREATE TABLE") }

        accountsSql shouldContain "CHECK (\"status\" IN ('active', 'inactive'))"
        accountsSql shouldContain "REFERENCES \"statuses\"(\"id\") ON DELETE RESTRICT"
    }

    test("enum with inline values and reference generates both CHECK and REFERENCES") {
        val s = schema(
            tables = mapOf(
                "lookup" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                ),
                "records" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "kind" to col(
                            NeutralType.Enum(values = listOf("a", "b", "c")),
                            required = true,
                            references = ref("lookup", "id", onDelete = ReferentialAction.NO_ACTION)
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val recordsSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("\"records\"") && it.startsWith("CREATE TABLE") }

        recordsSql shouldContain "CHECK (\"kind\" IN ('a', 'b', 'c'))"
        recordsSql shouldContain "REFERENCES \"lookup\"(\"id\") ON DELETE NO ACTION"
    }

    test("number literal default renders correctly") {
        val s = schema(
            tables = mapOf(
                "counters" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "count" to col(
                            NeutralType.Integer,
                            required = true,
                            default = DefaultValue.NumberLiteral(42)
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"count\" INTEGER NOT NULL DEFAULT 42"
    }

    test("uuid json binary and array retain their SQLite mappings") {
        val s = schema(
            tables = mapOf(
                "typed" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "external_id" to col(NeutralType.Uuid),
                        "payload" to col(NeutralType.Json),
                        "raw_data" to col(NeutralType.Binary),
                        "tags" to col(NeutralType.Array("text")),
                    ),
                    primaryKey = listOf("id")
                )
            )
        )

        val sql = generator.generate(s).tableSql()

        sql shouldContain "\"external_id\" TEXT"
        sql shouldContain "\"payload\" TEXT"
        sql shouldContain "\"raw_data\" BLOB"
        sql shouldContain "\"tags\" TEXT"
    }

    // ─── Spatial Phase 1 ────────────────────────────────────

    test("spatialite profile produces AddGeometryColumn after CREATE TABLE") {
        val schema = SchemaDefinition(name = "T", version = "1", tables = mapOf(
            "places" to TableDefinition(columns = mapOf(
                "id" to ColumnDefinition(type = NeutralType.Identifier(true)),
                "location" to ColumnDefinition(type = NeutralType.Geometry(
                    GeometryType("point"), srid = 4326)),
            ), primaryKey = listOf("id"))
        ))
        val result = generator.generate(schema, DdlGenerationOptions(SpatialProfile.SPATIALITE))
        val ddl = result.render()
        ddl shouldContain "CREATE TABLE"
        ddl shouldContain "AddGeometryColumn('places', 'location', 4326, 'POINT', 'XY')"
        ddl shouldNotContain "geometry"  // geometry should NOT be inline in CREATE TABLE
    }

    test("spatialite rollback produces DiscardGeometryColumn") {
        val schema = SchemaDefinition(name = "T", version = "1", tables = mapOf(
            "places" to TableDefinition(columns = mapOf(
                "id" to ColumnDefinition(type = NeutralType.Identifier(true)),
                "loc" to ColumnDefinition(type = NeutralType.Geometry(GeometryType("point"))),
            ), primaryKey = listOf("id"))
        ))
        val result = generator.generateRollback(schema, DdlGenerationOptions(SpatialProfile.SPATIALITE))
        result.render() shouldContain "DiscardGeometryColumn"
    }

    test("profile none blocks table with geometry columns") {
        val schema = SchemaDefinition(name = "T", version = "1", tables = mapOf(
            "places" to TableDefinition(columns = mapOf(
                "id" to ColumnDefinition(type = NeutralType.Identifier(true)),
                "loc" to ColumnDefinition(type = NeutralType.Geometry()),
            ), primaryKey = listOf("id"))
        ))
        val result = generator.generate(schema, DdlGenerationOptions(SpatialProfile.NONE))
        result.notes.any { it.code == "E052" && it.objectName == "places" } shouldBe true
        result.skippedObjects.any { it.code == "E052" } shouldBe true
        result.render() shouldNotContain "CREATE TABLE \"places\""
        result.render() shouldNotContain "AddGeometryColumn('places'"
    }

    test("spatialite rollback with multiple geometry columns: DiscardGeometryColumn before DROP TABLE") {
        val schema = SchemaDefinition(name = "T", version = "1", tables = mapOf(
            "geo" to TableDefinition(columns = linkedMapOf(
                "id" to ColumnDefinition(type = NeutralType.Identifier(true)),
                "loc" to ColumnDefinition(type = NeutralType.Geometry(GeometryType("point"), srid = 4326)),
                "area" to ColumnDefinition(type = NeutralType.Geometry(GeometryType("polygon"))),
            ), primaryKey = listOf("id"))
        ))
        val result = generator.generateRollback(schema, DdlGenerationOptions(SpatialProfile.SPATIALITE))
        val ddl = result.render()
        val discardLoc = ddl.indexOf("DiscardGeometryColumn('geo', 'loc')")
        val discardArea = ddl.indexOf("DiscardGeometryColumn('geo', 'area')")
        val dropTable = ddl.indexOf("DROP TABLE")
        // Both DiscardGeometryColumn must appear before DROP TABLE
        (discardLoc >= 0) shouldBe true
        (discardArea >= 0) shouldBe true
        (dropTable >= 0) shouldBe true
        (discardLoc < dropTable) shouldBe true
        (discardArea < dropTable) shouldBe true
    }

    test("spatialite metadata blocking adds SkippedObject") {
        val schema = SchemaDefinition(name = "T", version = "1", tables = mapOf(
            "t" to TableDefinition(columns = mapOf(
                "id" to ColumnDefinition(type = NeutralType.Identifier(true)),
                "loc" to ColumnDefinition(type = NeutralType.Geometry(), required = true),
            ), primaryKey = listOf("id"))
        ))
        val result = generator.generate(schema, DdlGenerationOptions(SpatialProfile.SPATIALITE))
        result.skippedObjects.any { it.code == "E052" && it.name == "t" } shouldBe true
    }

    test("spatialite blocks table when geometry column has required metadata") {
        val schema = SchemaDefinition(name = "T", version = "1", tables = mapOf(
            "t" to TableDefinition(columns = mapOf(
                "id" to ColumnDefinition(type = NeutralType.Identifier(true)),
                "loc" to ColumnDefinition(type = NeutralType.Geometry(), required = true),
            ), primaryKey = listOf("id"))
        ))
        val result = generator.generate(schema, DdlGenerationOptions(SpatialProfile.SPATIALITE))
        result.notes.any { it.code == "E052" } shouldBe true
    }
})
