package dev.dmigrate.driver.postgresql

import dev.dmigrate.core.model.ColumnGeneration
import dev.dmigrate.core.model.IdentityMode
import dev.dmigrate.core.model.NeutralType
import dev.dmigrate.driver.DatabaseDialect
import dev.dmigrate.driver.DatabaseDriverRegistry
import dev.dmigrate.driver.SchemaReadNote
import dev.dmigrate.driver.SchemaReadSeverity
import dev.dmigrate.driver.connection.ConnectionConfig
import dev.dmigrate.driver.connection.ConnectionPool
import dev.dmigrate.driver.connection.HikariConnectionPoolFactory
import dev.dmigrate.driver.connection.asJdbc
import dev.dmigrate.test.images.TestImages
import io.kotest.assertions.withClue
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.nulls.shouldBeNull
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import org.testcontainers.postgresql.PostgreSQLContainer

/**
 * Was der PostgreSQL-Reverse gegen einen **echten** Server verliert und sagt.
 *
 * Die Unit-Tests pinnen die Abbildung; hier steht, was
 * `information_schema` tatsaechlich liefert — dass eine `numeric`-Spalte ohne
 * Angabe wirklich ohne `numeric_precision` ankommt, dass `date[]` als
 * `udt_name = '_date'` kommt und dass eine `integer GENERATED ALWAYS AS
 * IDENTITY PRIMARY KEY` als Identity **mit** Modus gemeldet wird.
 *
 * Abgedeckt: P8 (`R402`), P9 (`R404`), N1 (`R301` am Array), S1 (der Modus
 * bleibt) und S3 (die Elementart ueberlebt den Rundweg PostgreSQL →
 * PostgreSQL).
 */
class PostgresReverseLossNoteIntegrationTest : FunSpec({

    val container = PostgreSQLContainer(TestImages.POSTGRESQL)
        .withDatabaseName("dmigrate_loss")
        .withUsername("dmigrate")
        .withPassword("dmigrate")

    lateinit var pool: ConnectionPool

    beforeSpec {
        container.start()
        DatabaseDriverRegistry.register(PostgresDriver())
        pool = HikariConnectionPoolFactory.create(
            ConnectionConfig(
                dialect = DatabaseDialect.POSTGRESQL,
                host = container.host,
                port = container.firstMappedPort,
                database = "dmigrate_loss",
                user = "dmigrate",
                password = "dmigrate",
            ),
        )
        pool.borrow().asJdbc().use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(
                    """
                    CREATE TABLE loss_types (
                        id integer PRIMARY KEY,
                        payload_json json NOT NULL,
                        payload_jsonb jsonb NOT NULL,
                        amount numeric NOT NULL,
                        bounded numeric(12,2) NOT NULL,
                        tags text[] NOT NULL,
                        totals bigint[] NOT NULL,
                        rates double precision[] NOT NULL,
                        prices numeric[] NOT NULL,
                        docs jsonb[] NOT NULL,
                        due_dates date[] NOT NULL
                    )
                    """.trimIndent(),
                )
                stmt.execute(
                    """
                    CREATE TABLE loss_identity_int (
                        id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                        label text NOT NULL
                    )
                    """.trimIndent(),
                )
                stmt.execute(
                    """
                    CREATE TABLE loss_identity_default (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        label text NOT NULL
                    )
                    """.trimIndent(),
                )
                stmt.execute("CREATE TABLE loss_identity_serial (id serial PRIMARY KEY, label text NOT NULL)")
                stmt.execute("CREATE TYPE loss_addr AS (amount numeric, extra inet)")
            }
        }
    }

    afterSpec {
        runCatching { pool.close() }
        container.stop()
    }

    fun read() = PostgresSchemaReader().read(pool)

    fun List<SchemaReadNote>.forObject(name: String) = filter { it.objectName == name }

    test("P8: json meldet R402, jsonb nicht") {
        val notes = read().notes

        val note = notes.forObject("loss_types.payload_json").single { it.code == "R402" }
        note.severity shouldBe SchemaReadSeverity.WARNING
        note.message shouldContain "jsonb"
        notes.forObject("loss_types.payload_jsonb").filter { it.code == "R402" }.shouldBeEmpty()
    }

    test("P9: numeric ohne Praezision meldet R404, mit Praezision nicht") {
        val result = read()
        val column = result.schema.tables.getValue("loss_types").columns

        column.getValue("amount").type shouldBe NeutralType.Float()
        column.getValue("bounded").type shouldBe NeutralType.Decimal(12, 2)

        result.notes.forObject("loss_types.amount").single { it.code == "R404" }
        result.notes.forObject("loss_types.bounded").filter { it.code == "R404" }.shouldBeEmpty()
    }

    test("N1: date[] liest text und meldet R301, eine benannte Elementart nicht") {
        val result = read()
        val column = result.schema.tables.getValue("loss_types").columns

        column.getValue("due_dates").type shouldBe NeutralType.Array("text")
        result.notes.forObject("loss_types.due_dates").single { it.code == "R301" }

        for (name in listOf("tags", "totals", "rates", "prices", "docs")) {
            withClue(name) {
                result.notes.forObject("loss_types.$name").filter { it.code == "R301" }.shouldBeEmpty()
            }
        }
    }

    test("L3: ein Feld eines zusammengesetzten Typs meldet dieselben Verluste") {
        val notes = read().notes
        notes.forObject("loss_addr.amount").single { it.code == "R404" }
        notes.forObject("loss_addr.extra").single { it.code == "R301" }
    }

    test("S1: integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY behaelt den Modus") {
        val tables = read().schema.tables

        val always = tables.getValue("loss_identity_int").columns.getValue("id")
        always.type shouldBe NeutralType.Integer
        (always.generation as ColumnGeneration.Identity).mode shouldBe IdentityMode.ALWAYS

        // Gegenprobe: `BY DEFAULT` und `serial` behalten den
        // `identifier`-Vertrag.
        val byDefault = tables.getValue("loss_identity_default").columns.getValue("id")
        byDefault.type shouldBe NeutralType.Identifier(autoIncrement = true)
        byDefault.generation.shouldBeNull()

        val serial = tables.getValue("loss_identity_serial").columns.getValue("id")
        serial.type shouldBe NeutralType.Identifier(autoIncrement = true)
        serial.generation.shouldBeNull()
    }

    /**
     * S3, die Kette, die kein Unit-Test schliesst: der Reverse liest die
     * Elementart, der Generator rendert sie, der Server nimmt die DDL an, und
     * ein zweiter Reverse liefert dieselbe Elementart. Vorher entstand hier
     * ueberall `text[]`.
     */
    test("S3: die Elementart ueberlebt PostgreSQL -> DDL -> PostgreSQL") {
        val source = read().schema.tables.getValue("loss_types").columns
        val elements = listOf("tags", "totals", "rates", "prices", "docs")
            .associateWith { (source.getValue(it).type as NeutralType.Array).elementType }

        elements shouldBe mapOf(
            "tags" to "text",
            "totals" to "biginteger",
            "rates" to "float",
            "prices" to "decimal",
            "docs" to "json",
        )

        val mapper = PostgresTypeMapper()
        pool.borrow().asJdbc().use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute("DROP TABLE IF EXISTS loss_roundtrip")
                val columns = elements.entries.joinToString(", ") { (name, element) ->
                    "\"$name\" ${mapper.toSql(NeutralType.Array(element))}"
                }
                stmt.execute("CREATE TABLE loss_roundtrip (id integer PRIMARY KEY, $columns)")
            }
        }

        val back = read().schema.tables.getValue("loss_roundtrip").columns
        for ((name, element) in elements) {
            withClue(name) { back.getValue(name).type shouldBe NeutralType.Array(element) }
        }
    }
})
