package dev.dmigrate.driver.postgresql

import dev.dmigrate.driver.DatabaseDialect
import dev.dmigrate.driver.DatabaseDriverRegistry
import dev.dmigrate.driver.connection.ConnectionConfig
import dev.dmigrate.driver.connection.HikariConnectionPoolFactory
import dev.dmigrate.driver.connection.asJdbc
import dev.dmigrate.test.images.TestImages
import dev.dmigrate.core.model.ColumnGeneration
import dev.dmigrate.core.model.IdentityMode
import dev.dmigrate.core.model.NeutralType
import io.kotest.assertions.withClue
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.nulls.shouldNotBeNull
import io.kotest.matchers.shouldBe
import org.testcontainers.postgresql.PostgreSQLContainer

/**
 * Wie der PostgreSQL-Reverse eine Identity-Spalte fuehrt -- live gemessen
 * gegen 18.6, weil kein Unit-Test es zeigen kann.
 *
 * | Spalte | Ergebnis |
 * | --- | --- |
 * | `int GENERATED ALWAYS AS IDENTITY PRIMARY KEY` | `Identifier(autoIncrement = true)`, `generation` bleibt leer -- die gefaltete Schreibweise |
 * | `int GENERATED BY DEFAULT AS IDENTITY` (kein Schluessel) | `Integer` **mit** `generation: identity` |
 * | `serial` | `Integer` mit `SequenceNextVal`-Default, keine Identity |
 *
 * Die zweite Zeile war der Befund: die Spalte kam als gewoehnliches `integer`
 * zurueck -- `generation`, `default` und Typ trugen die Identity nirgends, und
 * ein `schema generate` daraus erzeugte eine Spalte ohne Generator. Der Zweig
 * darueber faengt nur `bigint`, der darunter nur den Primaerschluessel.
 */
class PostgresIdentityShapeIntegrationTest : FunSpec({

    val container = PostgreSQLContainer(TestImages.POSTGRESQL)

    beforeSpec { container.start(); DatabaseDriverRegistry.register(PostgresDriver()) }
    afterSpec { container.stop(); DatabaseDriverRegistry.clear() }

    test("the reverse carries identity in the type for a PK and in generation otherwise") {
        val pool = HikariConnectionPoolFactory.create(
            ConnectionConfig(
                dialect = DatabaseDialect.POSTGRESQL,
                host = container.host, port = container.firstMappedPort,
                database = container.databaseName, user = container.username, password = container.password,
            ),
        )
        pool.borrow().asJdbc().use { conn ->
            conn.createStatement().use {
                it.execute(
                    "CREATE TABLE shapes (" +
                        "id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, " +
                        "counter int GENERATED BY DEFAULT AS IDENTITY, " +
                        "serial_col serial, " +
                        "plain int)",
                )
            }
        }
        val cols = PostgresSchemaReader().read(pool).schema.tables.getValue("shapes").columns

        withClue(cols.entries.joinToString { "${it.key}=${it.value.type}/${it.value.generation}" }) {
            // Der Primaerschluessel: gefaltete Schreibweise im Typ.
            cols.getValue("id").type shouldBe NeutralType.Identifier(autoIncrement = true)
            cols.getValue("id").generation shouldBe null

            // Ohne Schluessel gibt es diese Faltung nicht -- hier MUSS die
            // Identity in `generation` stehen, sonst ist sie verloren.
            val counter = cols.getValue("counter")
            counter.type shouldBe NeutralType.Integer
            val identity = counter.generation as? ColumnGeneration.Identity
            identity.shouldNotBeNull()
            identity.mode shouldBe IdentityMode.BY_DEFAULT

            // `serial` ist keine Identity, sondern ein Sequenz-Default.
            cols.getValue("serial_col").generation shouldBe null
            cols.getValue("serial_col").default.shouldNotBeNull()
        }
        pool.close()
    }
})
