package dev.dmigrate.driver

import dev.dmigrate.core.model.*

abstract class AbstractDdlGenerator(
    protected val typeMapper: TypeMapper
) : DdlGenerator {

    override fun generate(schema: SchemaDefinition): DdlResult {
        val statements = mutableListOf<DdlStatement>()
        val skipped = mutableListOf<SkippedObject>()

        statements += generateHeader(schema)
        statements += generateCustomTypes(schema.customTypes)
        statements += generateSequences(schema.sequences, skipped)

        val (sorted, circularEdges) = topologicalSort(schema.tables)
        val deferredFks = circularEdges.map { it.fromTable to it.fromColumn }.toSet()
        for ((name, table) in sorted) {
            statements += generateTable(name, table, schema, deferredFks)
        }
        for ((name, table) in sorted) {
            statements += generateIndices(name, table)
        }
        statements += handleCircularReferences(circularEdges, skipped)

        statements += generateViews(schema.views, skipped)
        statements += generateFunctions(schema.functions, skipped)
        statements += generateProcedures(schema.procedures, skipped)
        statements += generateTriggers(schema.triggers, schema.tables, skipped)

        return DdlResult(statements.filter { it.sql.isNotBlank() }, skipped)
    }

    override fun generateRollback(schema: SchemaDefinition): DdlResult {
        val up = generate(schema)
        val downStatements = up.statements.reversed().mapNotNull { invertStatement(it) }
        return DdlResult(downStatements, emptyList())
    }

    // ── Abstract methods ────────────────────────

    abstract fun quoteIdentifier(name: String): String
    abstract fun generateTable(name: String, table: TableDefinition, schema: SchemaDefinition, deferredFks: Set<Pair<String, String>> = emptySet()): List<DdlStatement>
    abstract fun generateCustomTypes(types: Map<String, CustomTypeDefinition>): List<DdlStatement>
    abstract fun generateSequences(sequences: Map<String, SequenceDefinition>, skipped: MutableList<SkippedObject>): List<DdlStatement>
    abstract fun generateIndices(tableName: String, table: TableDefinition): List<DdlStatement>
    abstract fun handleCircularReferences(edges: List<CircularFkEdge>, skipped: MutableList<SkippedObject>): List<DdlStatement>
    abstract fun generateViews(views: Map<String, ViewDefinition>, skipped: MutableList<SkippedObject>): List<DdlStatement>
    abstract fun generateFunctions(functions: Map<String, FunctionDefinition>, skipped: MutableList<SkippedObject>): List<DdlStatement>
    abstract fun generateProcedures(procedures: Map<String, ProcedureDefinition>, skipped: MutableList<SkippedObject>): List<DdlStatement>
    abstract fun generateTriggers(triggers: Map<String, TriggerDefinition>, tables: Map<String, TableDefinition>, skipped: MutableList<SkippedObject>): List<DdlStatement>

    // ── Shared logic ────────────────────────────

    protected open fun getVersion(): String = "0.3.0"

    protected fun generateHeader(schema: SchemaDefinition): List<DdlStatement> {
        val header = buildString {
            appendLine("-- Generated by d-migrate ${getVersion()}")
            appendLine("-- Source: neutral schema v${schema.version} \"${schema.name}\"")
            append("-- Target: ${dialect.name.lowercase()} | Generated: ${java.time.Instant.now()}")
        }
        return listOf(DdlStatement(header))
    }

    protected fun columnSql(colName: String, col: ColumnDefinition, schema: SchemaDefinition): String {
        val parts = mutableListOf<String>()
        parts += quoteIdentifier(colName)
        parts += typeMapper.toSql(col.type)
        if (col.required) parts += "NOT NULL"
        if (col.default != null) parts += "DEFAULT ${typeMapper.toDefaultSql(col.default!!, col.type)}"
        if (col.unique) parts += "UNIQUE"
        return parts.joinToString(" ")
    }

    protected fun referentialActionSql(action: ReferentialAction): String = when (action) {
        ReferentialAction.RESTRICT -> "RESTRICT"
        ReferentialAction.CASCADE -> "CASCADE"
        ReferentialAction.SET_NULL -> "SET NULL"
        ReferentialAction.SET_DEFAULT -> "SET DEFAULT"
        ReferentialAction.NO_ACTION -> "NO ACTION"
    }

    protected open fun invertStatement(stmt: DdlStatement): DdlStatement? {
        val sql = stmt.sql.trim()
        return when {
            sql.startsWith("CREATE TABLE", ignoreCase = true) -> {
                val name = extractNameAfter(sql, "CREATE TABLE")
                DdlStatement("DROP TABLE IF EXISTS $name;")
            }
            sql.startsWith("CREATE INDEX", ignoreCase = true) || sql.startsWith("CREATE UNIQUE INDEX", ignoreCase = true) -> {
                val name = extractNameAfter(sql, if ("UNIQUE" in sql.uppercase()) "CREATE UNIQUE INDEX" else "CREATE INDEX")
                DdlStatement("DROP INDEX IF EXISTS $name;")
            }
            sql.startsWith("CREATE TYPE", ignoreCase = true) -> {
                val name = extractNameAfter(sql, "CREATE TYPE")
                DdlStatement("DROP TYPE IF EXISTS $name;")
            }
            sql.startsWith("CREATE VIEW", ignoreCase = true) || sql.startsWith("CREATE OR REPLACE VIEW", ignoreCase = true) -> {
                val keyword = if ("OR REPLACE" in sql.uppercase()) "CREATE OR REPLACE VIEW" else "CREATE VIEW"
                val name = extractNameAfter(sql, keyword)
                DdlStatement("DROP VIEW IF EXISTS $name;")
            }
            sql.startsWith("CREATE MATERIALIZED VIEW", ignoreCase = true) -> {
                val name = extractNameAfter(sql, "CREATE MATERIALIZED VIEW")
                DdlStatement("DROP MATERIALIZED VIEW IF EXISTS $name;")
            }
            sql.startsWith("CREATE FUNCTION", ignoreCase = true) || sql.startsWith("CREATE OR REPLACE FUNCTION", ignoreCase = true) -> {
                val keyword = if ("OR REPLACE" in sql.uppercase()) "CREATE OR REPLACE FUNCTION" else "CREATE FUNCTION"
                val name = extractNameAfter(sql, keyword)
                DdlStatement("DROP FUNCTION IF EXISTS $name;")
            }
            sql.startsWith("CREATE PROCEDURE", ignoreCase = true) -> {
                val name = extractNameAfter(sql, "CREATE PROCEDURE")
                DdlStatement("DROP PROCEDURE IF EXISTS $name;")
            }
            sql.startsWith("CREATE TRIGGER", ignoreCase = true) -> {
                val name = extractNameAfter(sql, "CREATE TRIGGER")
                DdlStatement("DROP TRIGGER IF EXISTS $name;")
            }
            sql.startsWith("CREATE SEQUENCE", ignoreCase = true) -> {
                val name = extractNameAfter(sql, "CREATE SEQUENCE")
                DdlStatement("DROP SEQUENCE IF EXISTS $name;")
            }
            sql.startsWith("ALTER TABLE", ignoreCase = true) && sql.contains("ADD CONSTRAINT", ignoreCase = true) -> {
                val tableName = extractNameAfter(sql, "ALTER TABLE")
                val addConstraintIdx = sql.uppercase().indexOf("ADD CONSTRAINT")
                val constraintPart = sql.substring(addConstraintIdx + "ADD CONSTRAINT".length).trimStart()
                val constraintName = constraintPart.split(Regex("[\\s(]"), limit = 2).first()
                DdlStatement("ALTER TABLE $tableName DROP CONSTRAINT IF EXISTS $constraintName;")
            }
            sql.startsWith("--") -> null // Skip comments
            else -> null
        }
    }

    private fun extractNameAfter(sql: String, keyword: String): String {
        val afterKeyword = sql.substring(keyword.length).trimStart()
        // Handle IF NOT EXISTS
        val cleaned = if (afterKeyword.uppercase().startsWith("IF NOT EXISTS"))
            afterKeyword.substring("IF NOT EXISTS".length).trimStart()
        else afterKeyword
        // Take the first token (quoted or unquoted identifier)
        return cleaned.split(Regex("[\\s(]"), limit = 2).first()
    }

    // ── Topological sort ────────────────────────

    data class TopologicalSortResult(
        val sorted: List<Pair<String, TableDefinition>>,
        val circularEdges: List<CircularFkEdge>
    )

    data class CircularFkEdge(
        val fromTable: String,
        val fromColumn: String,
        val toTable: String,
        val toColumn: String
    )

    protected fun topologicalSort(tables: Map<String, TableDefinition>): TopologicalSortResult {
        // Build adjacency: table -> set of tables it depends on
        val deps = mutableMapOf<String, MutableSet<String>>()
        val allEdges = mutableListOf<CircularFkEdge>()

        for ((tableName, table) in tables) {
            deps.getOrPut(tableName) { mutableSetOf() }
            for ((colName, col) in table.columns) {
                val ref = col.references ?: continue
                if (ref.table != tableName && ref.table in tables) {
                    deps.getOrPut(tableName) { mutableSetOf() }.add(ref.table)
                    allEdges += CircularFkEdge(tableName, colName, ref.table, ref.column)
                }
            }
        }

        // Kahn's algorithm
        val inDegree = mutableMapOf<String, Int>()
        for (name in tables.keys) inDegree[name] = 0
        for ((_, depSet) in deps) {
            for (dep in depSet) {
                // dep must come before -> tables depending on dep have in-degree
            }
        }
        // Recalculate: for each table, in-degree = how many tables must come before it
        for ((table, depSet) in deps) {
            inDegree[table] = depSet.size
        }

        val queue = ArrayDeque<String>()
        for ((name, degree) in inDegree) {
            if (degree == 0) queue.add(name)
        }

        val sorted = mutableListOf<String>()
        while (queue.isNotEmpty()) {
            val current = queue.removeFirst()
            sorted.add(current)
            for ((table, depSet) in deps) {
                if (depSet.remove(current)) {
                    inDegree[table] = (inDegree[table] ?: 1) - 1
                    if (inDegree[table] == 0) queue.add(table)
                }
            }
        }

        // Remaining tables have circular dependencies
        val remaining = tables.keys - sorted.toSet()
        val circularEdges = if (remaining.isEmpty()) emptyList()
        else {
            // Add remaining tables to sorted (they'll be created without the circular FK)
            sorted.addAll(remaining)
            // Collect the circular FK edges
            allEdges.filter { it.fromTable in remaining }
        }

        return TopologicalSortResult(
            sorted = sorted.map { it to tables[it]!! },
            circularEdges = circularEdges
        )
    }
}
