package dev.dmigrate.driver

import dev.dmigrate.core.model.ColumnGeneration

/**
 * Was eine `AlterColumnGeneration` eigentlich aendert.
 *
 * **Warum das eine eigene Unterscheidung braucht.** Die Renderer fragten
 * bisher nur „ist die Zielseite eine berechnete Spalte?" und schickten alles
 * andere in denselben Zweig — mit einer Meldung ueber den *Berechnungsausdruck*.
 * Fuer eine Aenderung an der **Identity** stimmte davon kein Wort: es ging
 * weder um einen Ausdruck, noch koennen die Server so wenig, wie die Meldung
 * behauptete. Gemessen:
 *
 * | Uebergang | PostgreSQL 18.6 | MySQL 9.7.2 | Oracle 23 |
 * | --- | --- | --- | --- |
 * | berechnet → gewoehnlich | `DROP EXPRESSION` **geht** | „Changing the STORED status is not supported" | `MODIFY (c <typ>)` **geht** |
 * | gewoehnlich → berechnet | „is not a generated column" | „Changing the STORED status is not supported" | `ORA-54026` „Real column cannot have an expression" |
 * | Identity `ALWAYS` → `BY DEFAULT` | `SET GENERATED BY DEFAULT` **geht** | (Modus gibt es nicht) | `MODIFY (c GENERATED BY DEFAULT AS IDENTITY)` **geht** |
 * | Identity → gewoehnlich | `DROP IDENTITY` **geht** | `MODIFY c INT` **geht** (Schluesselspalte) | `MODIFY (c DROP IDENTITY)` **geht** |
 * | gewoehnlich → Identity | braucht vorher `NOT NULL` | nur als Schluesselspalte | `ORA-30673` |
 *
 * Die Zeilen unterscheiden sich je Dialekt **und** je Richtung; ein einziger
 * Zweig kann sie nicht alle richtig beantworten. Diese Einteilung sagt nur,
 * *welche* Frage vorliegt — die Antwort bleibt beim Dialekt.
 */
enum class ColumnGenerationTransition {

    /** Beide Seiten berechnet: der Ausdruck und/oder die Speicherform aendert sich. */
    COMPUTED_EXPRESSION,

    /** Eine gewoehnliche Spalte wird berechnet. Kein Server macht das in place (gemessen). */
    COMPUTED_ADDED,

    /** Eine berechnete Spalte wird gewoehnlich. */
    COMPUTED_DROPPED,

    /**
     * Identity ist auf mindestens einer Seite beteiligt — auch beim Tausch
     * berechnet ↔ Identity. Mit dem Berechnungsausdruck hat der Fall nichts zu
     * tun, und die Server koennen davon mehr, als eine Ausdrucks-Meldung
     * nahelegt.
     */
    IDENTITY,

    ;

    companion object {

        /**
         * [from] und [to] sind in **Render**-Richtung zu lesen: fuer `UP` also
         * `op.before`/`op.after`, fuer `DOWN` umgekehrt. Sonst stuende der
         * Rueckweg unter der Begruendung des Hinwegs.
         */
        fun of(from: ColumnGeneration?, to: ColumnGeneration?): ColumnGenerationTransition = when {
            from is ColumnGeneration.Identity || to is ColumnGeneration.Identity -> IDENTITY
            from is ColumnGeneration.Computed && to is ColumnGeneration.Computed -> COMPUTED_EXPRESSION
            to is ColumnGeneration.Computed -> COMPUTED_ADDED
            else -> COMPUTED_DROPPED
        }
    }
}
