package dev.dmigrate.driver

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain

/**
 * Tests for the DDL data model classes (DdlResult, DdlStatement, TransformationNote,
 * NoteType, SkippedObject) — covers the lightweight logic that is NOT just
 * generated by the data class compiler (mainly DdlResult.notes and render(),
 * DdlStatement.render() with notes/hints).
 */
class DdlModelTest : FunSpec({

    // ─── NoteType enum ───────────────────────────────────────────

    test("NoteType has the three expected severities") {
        NoteType.entries shouldBe listOf(NoteType.INFO, NoteType.WARNING, NoteType.ACTION_REQUIRED)
    }

    test("NoteType.valueOf round-trip") {
        for (t in NoteType.entries) {
            NoteType.valueOf(t.name) shouldBe t
        }
    }

    // ─── DdlStatement.render() ───────────────────────────────────

    test("DdlStatement.render() without notes returns the SQL unchanged") {
        DdlStatement("CREATE TABLE x (id INT);").render() shouldBe "CREATE TABLE x (id INT);"
    }

    test("DdlStatement.render() prepends a comment per note") {
        val note = TransformationNote(
            type = NoteType.WARNING,
            code = "W100",
            objectName = "x.col",
            message = "test message",
        )
        val rendered = DdlStatement("CREATE TABLE x (col INT);", listOf(note)).render()
        rendered shouldContain "-- [W100] test message"
        rendered shouldContain "CREATE TABLE x"
        (rendered.indexOf("-- [W100]") < rendered.indexOf("CREATE TABLE")) shouldBe true
    }

    test("DdlStatement.render() includes hint when present") {
        val note = TransformationNote(
            type = NoteType.ACTION_REQUIRED,
            code = "E052",
            objectName = "fn1",
            message = "manual fix needed",
            hint = "rewrite manually",
        )
        val rendered = DdlStatement("-- TODO", listOf(note)).render()
        rendered shouldContain "-- [E052] manual fix needed"
        rendered shouldContain "-- Hint: rewrite manually"
    }

    test("DdlStatement.render() omits hint line when hint is null") {
        val note = TransformationNote(NoteType.INFO, "I001", "obj", "info", hint = null)
        val rendered = DdlStatement("CREATE TABLE x();", listOf(note)).render()
        rendered shouldNotContain "-- Hint:"
    }

    test("DdlStatement.render() with multiple notes prepends them in order") {
        val n1 = TransformationNote(NoteType.WARNING, "W1", "x", "first")
        val n2 = TransformationNote(NoteType.WARNING, "W2", "x", "second")
        val rendered = DdlStatement("SELECT 1;", listOf(n1, n2)).render()
        (rendered.indexOf("W1") < rendered.indexOf("W2")) shouldBe true
        (rendered.indexOf("W2") < rendered.indexOf("SELECT")) shouldBe true
    }

    // ─── DdlResult ───────────────────────────────────────────────

    test("DdlResult.notes aggregates notes from all statements") {
        val n1 = TransformationNote(NoteType.WARNING, "W1", "x", "warn-1")
        val n2 = TransformationNote(NoteType.INFO, "I1", "y", "info-1")
        val result = DdlResult(
            statements = listOf(
                DdlStatement("A;", listOf(n1)),
                DdlStatement("B;"),
                DdlStatement("C;", listOf(n2)),
            ),
        )
        result.notes shouldBe listOf(n1, n2)
    }

    test("DdlResult.notes is empty when no statements have notes") {
        val result = DdlResult(listOf(DdlStatement("A;"), DdlStatement("B;")))
        result.notes shouldBe emptyList()
    }

    test("DdlResult.render() joins statements with double newlines") {
        val result = DdlResult(listOf(DdlStatement("A;"), DdlStatement("B;")))
        result.render() shouldBe "A;\n\nB;"
    }

    test("DdlResult.render() includes note comments inline with statements") {
        val n = TransformationNote(NoteType.WARNING, "W1", "x", "warn")
        val result = DdlResult(listOf(DdlStatement("A;", listOf(n)), DdlStatement("B;")))
        result.render() shouldContain "-- [W1] warn"
        result.render() shouldContain "A;"
        result.render() shouldContain "B;"
    }

    test("DdlResult default skippedObjects is empty list") {
        DdlResult(emptyList()).skippedObjects shouldBe emptyList()
    }

    test("DdlResult exposes skipped objects when provided") {
        val skipped = SkippedObject(type = "function", name = "fn1", reason = "no body")
        val result = DdlResult(emptyList(), listOf(skipped))
        result.skippedObjects shouldBe listOf(skipped)
    }

    // ─── data class structural equality ──────────────────────────

    test("TransformationNote equality with and without hint") {
        val a = TransformationNote(NoteType.WARNING, "W1", "x", "msg")
        val b = TransformationNote(NoteType.WARNING, "W1", "x", "msg")
        val c = TransformationNote(NoteType.WARNING, "W1", "x", "msg", hint = "h")
        a shouldBe b
        a shouldNotBe c
    }

    test("SkippedObject equality is structural") {
        SkippedObject("view", "v1", "no query") shouldBe SkippedObject("view", "v1", "no query")
        SkippedObject("view", "v1", "no query") shouldNotBe SkippedObject("view", "v2", "no query")
    }
})
