package dev.dmigrate.format.yaml

import dev.dmigrate.driver.DdlGenerator
import dev.dmigrate.driver.mysql.MysqlDdlGenerator
import dev.dmigrate.driver.postgresql.PostgresDdlGenerator
import dev.dmigrate.driver.sqlite.SqliteDdlGenerator
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe

class DdlGoldenMasterTest : FunSpec({

    val schemas = listOf("minimal", "e-commerce", "all-types", "full-featured")
    val dialects: List<Pair<String, DdlGenerator>> = listOf(
        "postgresql" to PostgresDdlGenerator(),
        "mysql" to MysqlDdlGenerator(),
        "sqlite" to SqliteDdlGenerator()
    )
    val codec = YamlSchemaCodec()

    fun loadFixture(path: String) =
        codec.read(DdlGoldenMasterTest::class.java.getResourceAsStream("/fixtures/$path")!!)

    fun loadGoldenMaster(path: String): String =
        DdlGoldenMasterTest::class.java.getResourceAsStream("/fixtures/$path")!!
            .bufferedReader().readText()

    fun stripHeader(ddl: String): String =
        ddl.lines()
            .filter { !it.startsWith("-- Generated by") && !it.startsWith("-- Target:") }
            .joinToString("\n")
            .trim()

    for (schema in schemas) {
        for ((dialectName, generator) in dialects) {
            test("$schema generates correct $dialectName DDL") {
                val input = loadFixture("schemas/$schema.yaml")
                val expected = loadGoldenMaster("ddl/$schema.$dialectName.sql")
                val actual = generator.generate(input).render()
                stripHeader(actual) shouldBe stripHeader(expected)
            }
        }
    }
})
