rootProject.name = "d-migrate"

// Hexagon (innen)
include("hexagon:core")
include("hexagon:ports-common")
include("hexagon:ports-read")
include("hexagon:ports-write")
include("hexagon:ports")
include("hexagon:application")
include("hexagon:profiling")

// Adapters (außen)
include("adapters:driven:driver-common")
include("adapters:driven:driver-postgresql")
include("adapters:driven:driver-postgresql-profiling")
include("adapters:driven:driver-mysql")
include("adapters:driven:driver-mysql-profiling")
include("adapters:driven:driver-sqlite")
include("adapters:driven:driver-sqlite-profiling")
include("adapters:driven:audit-logging")
include("adapters:driven:connection-config")
include("adapters:driven:formats")
include("adapters:driven:integrations")
include("adapters:driven:persistence-jdbc")
include("adapters:driven:storage-file")
include("adapters:driven:streaming")
include("adapters:driven:text-icu")
include("adapters:driving:cli")
include("adapters:driving:mcp")

// Integration test modules (Testcontainers, separated from driver unit tests)
include("test:integration-postgresql")
include("test:integration-mysql")
include("test:integration-sqlite")
include("test:integration-server-state")
include("test:integration-integrations")
include("test:integration-persistence-jdbc")

// Consumer integration probe (read-only surface verification)
include("test:consumer-read-probe")
