-- Generated by d-migrate 0.2.0
-- Source: neutral schema v1.0.0 "E-Commerce System"
-- Target: sqlite | Generated: 2026-04-05T17:28:29.691743815Z

-- [I001] Enum type 'order_status' mapped to inline TEXT + CHECK constraint in SQLite.
-- Enum type "order_status" is handled inline via CHECK constraints

CREATE TABLE "customers" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "email" TEXT NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    "metadata" TEXT,
    "created_at" TEXT DEFAULT (datetime('now'))
);

-- [W200] Decimal(10,2) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "orders" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "customer_id" INTEGER NOT NULL REFERENCES "customers"("id") ON DELETE RESTRICT,
    "order_date" TEXT NOT NULL,
    "total_amount" REAL,
    "status" TEXT DEFAULT 'pending' CHECK ("status" IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
    "notes" TEXT,
    CONSTRAINT "chk_total_positive" CHECK (total_amount >= 0)
);

CREATE INDEX "idx_customers_email" ON "customers" ("email");

CREATE INDEX "idx_orders_customer_date" ON "orders" ("customer_id", "order_date");
