package dev.dmigrate.cli.migration

import dev.dmigrate.driver.DdlResult
import dev.dmigrate.driver.DdlStatement
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain

class DdlNormalizerTest : FunSpec({

    fun resultWithHeader(timestamp: String = "2026-04-14T12:00:00Z"): DdlResult {
        val header = """
            -- Generated by d-migrate 0.7.0
            -- Source: neutral schema v1.0 "Shop"
            -- Target: postgresql | Generated: $timestamp
        """.trimIndent()
        val body = "CREATE TABLE users (id SERIAL PRIMARY KEY);"
        return DdlResult(listOf(DdlStatement(header), DdlStatement(body)))
    }

    test("timestamp stripped from header") {
        val payload = DdlNormalizer.normalize(resultWithHeader())
        payload.deterministicSql shouldNotContain "Generated:"
        payload.deterministicSql shouldContain "-- Target: postgresql"
    }

    test("different timestamps produce same deterministic SQL") {
        val a = DdlNormalizer.normalize(resultWithHeader("2026-04-14T12:00:00Z"))
        val b = DdlNormalizer.normalize(resultWithHeader("2026-04-14T18:30:00Z"))
        a.deterministicSql shouldBe b.deterministicSql
    }

    test("original DdlResult preserved in payload") {
        val result = resultWithHeader()
        val payload = DdlNormalizer.normalize(result)
        payload.result shouldBe result
    }

    test("DDL without timestamp header passes through unchanged") {
        val result = DdlResult(listOf(DdlStatement("CREATE TABLE t (id INT);")))
        val payload = DdlNormalizer.normalize(result)
        payload.deterministicSql shouldBe "CREATE TABLE t (id INT);"
    }

    test("multiple statements preserved") {
        val result = DdlResult(listOf(
            DdlStatement("-- Target: mysql | Generated: 2026-04-14T12:00:00Z"),
            DdlStatement("CREATE TABLE a (id INT);"),
            DdlStatement("CREATE TABLE b (id INT);"),
        ))
        val payload = DdlNormalizer.normalize(result)
        payload.deterministicSql shouldContain "CREATE TABLE a"
        payload.deterministicSql shouldContain "CREATE TABLE b"
        payload.deterministicSql shouldNotContain "Generated:"
    }
})
