package dev.dmigrate.driver.connection

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.nulls.shouldNotBeNull
import io.kotest.matchers.shouldBe
import java.sql.Connection
import java.sql.DriverManager
import java.sql.ResultSet

/**
 * LN-010 unit tests for [TimeoutDecoratedConnection]. Use a real
 * SQLite in-memory connection as the delegate so the decorator is
 * exercised against an actual JDBC driver — no hand-rolled fakes.
 */
class TimeoutDecoratedConnectionTest : FunSpec({

    fun openSqlite(): Connection {
        Class.forName("org.sqlite.JDBC")
        return DriverManager.getConnection("jdbc:sqlite::memory:")
    }

    test("createStatement applies queryTimeout from constructor") {
        openSqlite().use { delegate ->
            val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = 30)
            decorated.createStatement().use { stmt ->
                stmt.queryTimeout shouldBe 30
            }
        }
    }

    test("createStatement(int, int) applies queryTimeout") {
        openSqlite().use { delegate ->
            val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = 17)
            decorated.createStatement(
                ResultSet.TYPE_FORWARD_ONLY,
                ResultSet.CONCUR_READ_ONLY,
            ).use { stmt -> stmt.queryTimeout shouldBe 17 }
        }
    }

    test("createStatement(int, int, int) applies queryTimeout") {
        openSqlite().use { delegate ->
            val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = 11)
            decorated.createStatement(
                ResultSet.TYPE_FORWARD_ONLY,
                ResultSet.CONCUR_READ_ONLY,
                ResultSet.CLOSE_CURSORS_AT_COMMIT,
            ).use { stmt -> stmt.queryTimeout shouldBe 11 }
        }
    }

    test("prepareStatement(sql) applies queryTimeout") {
        openSqlite().use { delegate ->
            val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = 30)
            decorated.prepareStatement("SELECT 1").use { stmt ->
                stmt.queryTimeout shouldBe 30
            }
        }
    }

    test("prepareStatement(sql, autoGeneratedKeys) applies queryTimeout") {
        openSqlite().use { delegate ->
            val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = 7)
            decorated.prepareStatement("SELECT 1", java.sql.Statement.NO_GENERATED_KEYS).use { stmt ->
                stmt.queryTimeout shouldBe 7
            }
        }
    }

    test("prepareStatement(sql, columnIndexes) applies queryTimeout") {
        openSqlite().use { delegate ->
            // Need a real table so columnIndexes path is meaningful.
            delegate.createStatement().use { it.execute("CREATE TABLE t (id INTEGER)") }
            val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = 9)
            decorated.prepareStatement("INSERT INTO t (id) VALUES (?)", intArrayOf(1)).use { stmt ->
                stmt.queryTimeout shouldBe 9
            }
        }
    }

    test("prepareStatement(sql, columnNames) applies queryTimeout") {
        openSqlite().use { delegate ->
            delegate.createStatement().use { it.execute("CREATE TABLE t (id INTEGER)") }
            val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = 13)
            decorated.prepareStatement("INSERT INTO t (id) VALUES (?)", arrayOf("id")).use { stmt ->
                stmt.queryTimeout shouldBe 13
            }
        }
    }

    test("prepareStatement(sql, type, concurrency) applies queryTimeout") {
        openSqlite().use { delegate ->
            val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = 21)
            decorated.prepareStatement(
                "SELECT 1",
                ResultSet.TYPE_FORWARD_ONLY,
                ResultSet.CONCUR_READ_ONLY,
            ).use { stmt -> stmt.queryTimeout shouldBe 21 }
        }
    }

    test("prepareStatement(sql, type, concurrency, holdability) applies queryTimeout") {
        openSqlite().use { delegate ->
            val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = 25)
            decorated.prepareStatement(
                "SELECT 1",
                ResultSet.TYPE_FORWARD_ONLY,
                ResultSet.CONCUR_READ_ONLY,
                ResultSet.CLOSE_CURSORS_AT_COMMIT,
            ).use { stmt -> stmt.queryTimeout shouldBe 25 }
        }
    }

    test("queryTimeoutSeconds == 0 leaves the driver default — no setQueryTimeout invoked") {
        openSqlite().use { delegate ->
            val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = 0)
            decorated.createStatement().use { stmt -> stmt.queryTimeout shouldBe 0 }
            decorated.prepareStatement("SELECT 1").use { stmt -> stmt.queryTimeout shouldBe 0 }
            decorated.prepareStatement("SELECT 1", java.sql.Statement.NO_GENERATED_KEYS).use { stmt ->
                stmt.queryTimeout shouldBe 0
            }
        }
    }

    test("negative queryTimeoutSeconds is treated as disabled (defensive)") {
        openSqlite().use { delegate ->
            val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = -5)
            decorated.createStatement().use { stmt -> stmt.queryTimeout shouldBe 0 }
        }
    }

    test("non-statement methods are forwarded to the delegate") {
        openSqlite().use { delegate ->
            val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = 30)
            decorated.metaData.shouldNotBeNull()
            decorated.metaData.databaseProductName shouldBe "SQLite"
            decorated.isReadOnly shouldBe false
            decorated.autoCommit shouldBe true
        }
    }

    test("close() forwards to delegate") {
        val delegate = openSqlite()
        val decorated = TimeoutDecoratedConnection(delegate, queryTimeoutSeconds = 30)
        decorated.isClosed shouldBe false
        decorated.close()
        decorated.isClosed shouldBe true
        delegate.isClosed shouldBe true
    }
})
