-- Generated by d-migrate 0.9.5
-- Source: neutral schema v1.0.0 "All Types"
-- Target: mysql | Generated: 2026-04-05T17:28:32.375054073Z

-- [W100] DATETIME with timezone on column 'col_datetime' mapped to DATETIME in MySQL which does not support time zones.
-- Hint: Store timezone information in a separate column or use UTC consistently.
CREATE TABLE `type_test` (
    `col_identifier` INT NOT NULL AUTO_INCREMENT,
    `col_text` VARCHAR(255),
    `col_char` CHAR(2),
    `col_integer` INT,
    `col_smallint` SMALLINT,
    `col_biginteger` BIGINT,
    `col_float_single` FLOAT,
    `col_float_double` DOUBLE,
    `col_decimal` DECIMAL(10,2),
    `col_boolean` TINYINT(1),
    `col_datetime` DATETIME,
    `col_date` DATE,
    `col_time` TIME,
    `col_uuid` CHAR(36),
    `col_json` JSON,
    `col_xml` TEXT,
    `col_binary` BLOB,
    `col_email` VARCHAR(254),
    `col_enum` ENUM('a', 'b', 'c'),
    `col_array` JSON,
    PRIMARY KEY (`col_identifier`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
