-- Generated by d-migrate 1.8.0-SNAPSHOT
-- Source: neutral schema v1.0.0 "All Types"
-- Target: sqlite

-- [W200] Decimal(10,2) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [W162] Array column 'col_array' (element type 'text') is rendered as TEXT: SQLite has no native array column type, and a reverse read yields a plain text column without the element type.
-- Hint: Values are stored as text; adjust application code that expects a native array, and declare the element type in the schema file if the target has to carry it.
CREATE TABLE "type_test" (
    "col_identifier" INTEGER PRIMARY KEY AUTOINCREMENT,
    "col_text" TEXT,
    "col_char" TEXT,
    "col_integer" INTEGER,
    "col_smallint" INTEGER,
    "col_biginteger" INTEGER,
    "col_float_single" REAL,
    "col_float_double" REAL,
    "col_decimal" REAL,
    "col_boolean" INTEGER,
    "col_datetime" TEXT,
    "col_date" TEXT,
    "col_time" TEXT,
    "col_uuid" TEXT,
    "col_json" TEXT,
    "col_xml" TEXT,
    "col_binary" BLOB,
    "col_email" TEXT,
    "col_enum" TEXT CONSTRAINT "ck_type_test_col_enum" CHECK ("col_enum" IN ('a', 'b', 'c')),
    "col_array" TEXT
);
