-- Generated by d-migrate 0.9.5
-- Source: neutral schema v1.0.0 "All Types"
-- Target: postgresql | Generated: 2026-04-05T17:28:30.988863240Z

CREATE TABLE "type_test" (
    "col_identifier" SERIAL,
    "col_text" VARCHAR(255),
    "col_char" CHAR(2),
    "col_integer" INTEGER,
    "col_smallint" SMALLINT,
    "col_biginteger" BIGINT,
    "col_float_single" REAL,
    "col_float_double" DOUBLE PRECISION,
    "col_decimal" DECIMAL(10,2),
    "col_boolean" BOOLEAN,
    "col_datetime" TIMESTAMP WITH TIME ZONE,
    "col_date" DATE,
    "col_time" TIME,
    "col_uuid" UUID,
    "col_json" JSONB,
    "col_xml" XML,
    "col_binary" BYTEA,
    "col_email" VARCHAR(254),
    "col_enum" TEXT CHECK ("col_enum" IN ('a', 'b', 'c')),
    "col_array" TEXT[],
    PRIMARY KEY ("col_identifier")
);
