-- Generated by d-migrate 1.8.0-SNAPSHOT
-- Source: neutral schema v1.0.0 "All Types"
-- Target: mysql

-- [W100] DATETIME with timezone on column 'col_datetime' mapped to DATETIME in MySQL which does not support time zones.
-- Hint: Store timezone information in a separate column or use UTC consistently.
-- [W162] Array column 'col_array' (element type 'text') is rendered as JSON: MySQL has no native array column type, and a reverse read yields a plain json column without the element type.
-- Hint: Values are stored as a JSON array; adjust application code that expects a native array, and declare the element type in the schema file if the target has to carry it.
CREATE TABLE `type_test` (
    `col_identifier` INT NOT NULL AUTO_INCREMENT,
    `col_text` VARCHAR(255),
    `col_char` CHAR(2),
    `col_integer` INT,
    `col_smallint` SMALLINT,
    `col_biginteger` BIGINT,
    `col_float_single` FLOAT,
    `col_float_double` DOUBLE,
    `col_decimal` DECIMAL(10,2),
    `col_boolean` TINYINT(1),
    `col_datetime` DATETIME,
    `col_date` DATE,
    `col_time` TIME,
    `col_uuid` CHAR(36),
    `col_json` JSON,
    `col_xml` TEXT,
    `col_binary` BLOB,
    `col_email` VARCHAR(254),
    `col_enum` ENUM('a', 'b', 'c'),
    `col_array` JSON,
    PRIMARY KEY (`col_identifier`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
