-- Generated by d-migrate 1.2.0
-- Source: neutral schema v1.0.0 "All Types"
-- Target: oracle

-- [W147] Date column 'col_date' is rendered as Oracle DATE, which always carries a time component (midnight); a subsequent reverse read yields datetime, not date.
-- [W146] Time column 'col_time' is rendered as VARCHAR2(8) ('HH24:MI:SS' text): Oracle has no native time-only column type.
-- Hint: Add a CHECK constraint to validate the format if strict typing is required.
-- [W149] Array column 'col_array' is rendered as JSON: Oracle has no native array column type.
-- Hint: Values are stored as a JSON array; adjust application code that expects a native array.
CREATE TABLE "type_test" (
    "col_identifier" NUMBER(9) GENERATED ALWAYS AS IDENTITY,
    "col_text" VARCHAR2(255),
    "col_char" CHAR(2),
    "col_integer" NUMBER(9),
    "col_smallint" NUMBER(4),
    "col_biginteger" NUMBER(18),
    "col_float_single" BINARY_FLOAT,
    "col_float_double" BINARY_DOUBLE,
    "col_decimal" NUMBER(10,2),
    "col_boolean" NUMBER(1),
    "col_datetime" TIMESTAMP WITH TIME ZONE,
    "col_date" DATE,
    "col_time" VARCHAR2(8),
    "col_uuid" VARCHAR2(36),
    "col_json" JSON,
    "col_xml" XMLTYPE,
    "col_binary" BLOB,
    "col_email" VARCHAR2(254),
    "col_enum" VARCHAR2(1) CONSTRAINT "ck_type_test_col_enum" CHECK ("col_enum" IN ('a', 'b', 'c')),
    "col_array" JSON,
    CONSTRAINT "pk_type_test" PRIMARY KEY ("col_identifier")
);
