-- Generated by d-migrate 0.9.3
-- Source: neutral schema v1.0.0 "All Types"
-- Target: sqlite | Generated: 2026-04-05T17:28:33.585020301Z

-- [W200] Decimal(10,2) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "type_test" (
    "col_identifier" INTEGER PRIMARY KEY AUTOINCREMENT,
    "col_text" TEXT,
    "col_char" TEXT,
    "col_integer" INTEGER,
    "col_smallint" INTEGER,
    "col_biginteger" INTEGER,
    "col_float_single" REAL,
    "col_float_double" REAL,
    "col_decimal" REAL,
    "col_boolean" INTEGER,
    "col_datetime" TEXT,
    "col_date" TEXT,
    "col_time" TEXT,
    "col_uuid" TEXT,
    "col_json" TEXT,
    "col_xml" TEXT,
    "col_binary" BLOB,
    "col_email" TEXT,
    "col_enum" TEXT CHECK ("col_enum" IN ('a', 'b', 'c')),
    "col_array" TEXT
);
