-- Generated by d-migrate 1.0.3
-- Source: neutral schema v1.0.0 "E-Commerce System"
-- Target: mssql

-- [W137] JSON column 'metadata' is rendered as NVARCHAR(MAX): SQL Server has no native JSON column type; a reverse read yields plain text.
-- Hint: Add CHECK (ISJSON([metadata]) = 1) if the content must stay valid JSON.
CREATE TABLE [customers] (
    [id] INT IDENTITY(1,1) NOT NULL,
    [email] NVARCHAR(254) NOT NULL CONSTRAINT [uq_customers_email] UNIQUE,
    [name] NVARCHAR(100) NOT NULL,
    [metadata] NVARCHAR(MAX),
    [created_at] DATETIMEOFFSET CONSTRAINT [df_customers_created_at] DEFAULT SYSDATETIMEOFFSET(),
    CONSTRAINT [pk_customers] PRIMARY KEY ([id])
);

CREATE TABLE [orders] (
    [id] INT IDENTITY(1,1) NOT NULL,
    [customer_id] INT NOT NULL,
    [order_date] DATETIME2 NOT NULL,
    [total_amount] DECIMAL(10,2),
    [status] NVARCHAR(10) CONSTRAINT [df_orders_status] DEFAULT N'pending' CONSTRAINT [ck_orders_status] CHECK ([status] IN (N'pending', N'processing', N'shipped', N'delivered', N'cancelled')),
    [notes] NVARCHAR(MAX),
    CONSTRAINT [fk_orders_customer_id] FOREIGN KEY ([customer_id]) REFERENCES [customers] ([id]) ON DELETE NO ACTION,
    CONSTRAINT [chk_total_positive] CHECK (total_amount >= 0),
    CONSTRAINT [pk_orders] PRIMARY KEY ([id])
);

CREATE INDEX [idx_customers_email] ON [customers] ([email]);

CREATE INDEX [idx_orders_customer_date] ON [orders] ([customer_id], [order_date]);
