-- Generated by d-migrate 0.9.3
-- Source: neutral schema v1.0.0 "E-Commerce System"
-- Target: postgresql | Generated: 2026-04-05T17:28:27.388460523Z

CREATE TYPE "order_status" AS ENUM ('pending', 'processing', 'shipped', 'delivered', 'cancelled');

CREATE TABLE "customers" (
    "id" SERIAL,
    "email" VARCHAR(254) NOT NULL UNIQUE,
    "name" VARCHAR(100) NOT NULL,
    "metadata" JSONB,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "orders" (
    "id" SERIAL,
    "customer_id" INTEGER NOT NULL,
    "order_date" TIMESTAMP NOT NULL,
    "total_amount" DECIMAL(10,2),
    "status" "order_status" DEFAULT 'pending',
    "notes" TEXT,
    CONSTRAINT "fk_orders_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE RESTRICT,
    CONSTRAINT "chk_total_positive" CHECK (total_amount >= 0),
    PRIMARY KEY ("id")
);

CREATE INDEX "idx_customers_email" ON "customers" ("email");

CREATE INDEX "idx_orders_customer_date" ON "orders" ("customer_id", "order_date");
