-- Generated by d-migrate 1.2.0
-- Source: neutral schema v1.0.0 "E-Commerce System"
-- Target: oracle

CREATE TABLE "customers" (
    "id" NUMBER(9) GENERATED ALWAYS AS IDENTITY,
    "email" VARCHAR2(254) NOT NULL CONSTRAINT "uq_customers_email" UNIQUE,
    "name" VARCHAR2(100) NOT NULL,
    "metadata" JSON,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CONSTRAINT "pk_customers" PRIMARY KEY ("id")
);

CREATE TABLE "orders" (
    "id" NUMBER(9) GENERATED ALWAYS AS IDENTITY,
    "customer_id" NUMBER(9) NOT NULL,
    "order_date" DATE NOT NULL,
    "total_amount" NUMBER(10,2),
    "status" VARCHAR2(10) DEFAULT 'pending' CONSTRAINT "ck_orders_status" CHECK ("status" IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
    "notes" CLOB,
    CONSTRAINT "fk_orders_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id"),
    CONSTRAINT "chk_total_positive" CHECK (total_amount >= 0),
    CONSTRAINT "pk_orders" PRIMARY KEY ("id")
);

CREATE INDEX "idx_customers_email" ON "customers" ("email");

CREATE INDEX "idx_orders_customer_date" ON "orders" ("customer_id", "order_date");
