-- Generated by d-migrate 0.9.3
-- Source: neutral schema v1.0.0 "E-Commerce System"
-- Target: mysql | Generated: 2026-04-05T17:28:28.491959958Z

-- [W100] DATETIME with timezone on column 'created_at' mapped to DATETIME in MySQL which does not support time zones.
-- Hint: Store timezone information in a separate column or use UTC consistently.
CREATE TABLE `customers` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(254) NOT NULL UNIQUE,
    `name` VARCHAR(100) NOT NULL,
    `metadata` JSON,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `orders` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `customer_id` INT NOT NULL,
    `order_date` DATETIME NOT NULL,
    `total_amount` DECIMAL(10,2),
    `status` ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled') DEFAULT 'pending',
    `notes` TEXT,
    CONSTRAINT `fk_orders_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `chk_total_positive` CHECK (total_amount >= 0),
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX `idx_customers_email` ON `customers` (`email`);

CREATE INDEX `idx_orders_customer_date` ON `orders` (`customer_id`, `order_date`);
