-- Generated by d-migrate 1.0.3
-- Source: neutral schema v1.0.0 "Fulltext Schema"
-- Target: mysql

-- [W132] Full-text column 'search_vector' degraded to TEXT; MySQL has no full-text vector column type.
-- Hint: To restore full-text search, add a FULLTEXT index over the source text column(s); structural cross-dialect translation is a future slice.
CREATE TABLE `articles` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(200) NOT NULL,
    `body` TEXT,
    `search_vector` TEXT,
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE FULLTEXT INDEX `ft_articles` ON `articles` (`title`, `body`);
