-- Generated by d-migrate 0.9.3
-- Source: neutral schema v1.0.0 "Full Featured Schema"
-- Target: postgresql | Generated: 2026-04-05T17:28:44.787332864Z

CREATE TYPE "order_status" AS ENUM ('pending', 'shipped', 'delivered');

CREATE TYPE "address" AS (
    "street" VARCHAR(200),
    "city" VARCHAR(100)
);

CREATE DOMAIN "positive_amount" AS DECIMAL(10,2) CHECK (VALUE >= 0);

CREATE SEQUENCE "invoice_seq" START WITH 10000 INCREMENT BY 1 MINVALUE 10000 MAXVALUE 99999999 NO CYCLE CACHE 20;

CREATE SEQUENCE "simple_seq" START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE TABLE "customers" (
    "id" SERIAL,
    "name" VARCHAR(100) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "orders" (
    "id" SERIAL,
    "customer_id" INTEGER NOT NULL,
    "status" "order_status" DEFAULT 'pending',
    "date" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "uuid_field" UUID DEFAULT gen_random_uuid(),
    "active" BOOLEAN DEFAULT TRUE,
    "amount" DECIMAL(10,2) DEFAULT 0,
    CONSTRAINT "fk_orders_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "chk_amount" CHECK (amount >= 0),
    CONSTRAINT "uq_uuid" UNIQUE ("uuid_field"),
    CONSTRAINT "fk_composite" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY ("id")
) PARTITION BY RANGE ("date");

CREATE TABLE "orders_2024" PARTITION OF "orders" FOR VALUES FROM (2024-01-01) TO (2025-01-01);

CREATE TABLE "orders_2025" PARTITION OF "orders" FOR VALUES FROM (2025-01-01) TO (2026-01-01);

CREATE INDEX "idx_customer" ON "orders" USING HASH ("customer_id");

CREATE OR REPLACE VIEW "active_orders" AS
SELECT * FROM orders WHERE status != 'delivered'
;

CREATE MATERIALIZED VIEW "monthly_stats" AS
SELECT COUNT(*) FROM orders
;

CREATE OR REPLACE FUNCTION "calc_total"("p_order_id" INTEGER) RETURNS DECIMAL(10,2) AS $$
BEGIN
    RETURN 0;
END;

$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE "update_status"("p_order_id" INTEGER, "p_status" TEXT, OUT "p_affected" INTEGER) AS $$
BEGIN
    UPDATE orders SET status = p_status WHERE id = p_order_id;
END;

$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION "trg_fn_trg_updated"() RETURNS TRIGGER AS $$
NEW.updated_at = CURRENT_TIMESTAMP;

$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_updated"
    BEFORE UPDATE ON "orders"
    FOR EACH ROW
    WHEN (OLD.status != NEW.status)
    EXECUTE FUNCTION "trg_fn_trg_updated"();

-- [E053] Trigger 'trg_insert' has no body and must be manually implemented.
-- Hint: Provide a trigger body in the schema definition.
-- TODO: Implement trigger "trg_insert"
