-- Generated by d-migrate 0.2.0
-- Source: neutral schema v1.0.0 "Full Featured Schema"
-- Target: sqlite | Generated: 2026-04-05T17:29:00.223776346Z

-- [I001] Enum type 'order_status' mapped to inline TEXT + CHECK constraint in SQLite.
-- Enum type "order_status" is handled inline via CHECK constraints

-- [E052] Composite type 'address' is not supported in SQLite.
-- Hint: Flatten composite fields into individual table columns or use JSON.
-- Composite type "address" is not supported in SQLite

-- [I001] Domain type 'positive_amount' mapped to base type with inline CHECK constraint in SQLite.
-- Domain type "positive_amount" is mapped to its base type with inline CHECK in SQLite

-- [E052] Sequence 'invoice_seq' is not supported in SQLite.
-- Hint: Use INTEGER PRIMARY KEY AUTOINCREMENT or application-level sequencing.
-- Sequence "invoice_seq" is not supported in SQLite

-- [E052] Sequence 'simple_seq' is not supported in SQLite.
-- Hint: Use INTEGER PRIMARY KEY AUTOINCREMENT or application-level sequencing.
-- Sequence "simple_seq" is not supported in SQLite

CREATE TABLE "customers" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL
);

-- [W200] Decimal(10,2) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [E052] Table partitioning is not supported in SQLite for table 'orders'.
-- Hint: Partition data at the application level or use separate tables.
CREATE TABLE "orders" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "customer_id" INTEGER NOT NULL REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    "status" TEXT DEFAULT 'pending' CHECK ("status" IN ('pending', 'shipped', 'delivered')),
    "date" TEXT DEFAULT (datetime('now')),
    "uuid_field" TEXT DEFAULT (lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6)))),
    "active" INTEGER DEFAULT 1,
    "amount" REAL DEFAULT 0,
    CONSTRAINT "chk_amount" CHECK (amount >= 0),
    CONSTRAINT "uq_uuid" UNIQUE ("uuid_field"),
    CONSTRAINT "fk_composite" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- [W102] HASH index 'idx_customer' on table 'orders' is not supported in SQLite. Only BTREE is available.
-- Hint: The index has been skipped. If needed, create a standard BTREE index instead.
-- Index "idx_customer" skipped: HASH index type is not supported in SQLite

-- [E052] View 'active_orders' was written for 'postgresql' and must be manually rewritten for SQLite.
-- Hint: Rewrite the query using SQLite-compatible SQL syntax.
-- TODO: Rewrite view "active_orders" for SQLite (source dialect: postgresql)

-- [E052] View 'monthly_stats' was written for 'postgresql' and must be manually rewritten for SQLite.
-- Hint: Rewrite the query using SQLite-compatible SQL syntax.
-- TODO: Rewrite view "monthly_stats" for SQLite (source dialect: postgresql)

-- [E052] Function 'calc_total' cannot be created via DDL in SQLite.
-- Hint: Register custom functions programmatically via the SQLite C API or your application's SQLite driver.
-- Function "calc_total" is not supported in SQLite

-- [E052] Procedure 'update_status' cannot be created in SQLite.
-- Hint: Implement procedure logic at the application level.
-- Procedure "update_status" is not supported in SQLite

-- [E052] Trigger 'trg_updated' was written for 'postgresql' and must be manually rewritten for SQLite.
-- Hint: Rewrite the trigger body using SQLite-compatible syntax with BEGIN...END;.
-- TODO: Rewrite trigger "trg_updated" for SQLite (source dialect: postgresql)

-- [E052] Trigger 'trg_insert' has no body and must be manually implemented.
-- Hint: Provide a trigger body in the schema definition.
-- TODO: Implement trigger "trg_insert"
