-- Generated by d-migrate 1.0.3
-- Source: neutral schema v1.0.0 "Full Featured Schema"
-- Target: mssql

-- [E054] Composite type 'address' is not supported in SQL Server and was skipped.
-- Hint: Flatten the fields into columns or store the value as JSON text.

CREATE SEQUENCE [invoice_seq] AS BIGINT START WITH 10000 INCREMENT BY 1 MINVALUE 10000 MAXVALUE 99999999 NO CYCLE CACHE 20;

CREATE SEQUENCE [simple_seq] AS BIGINT START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE TABLE [customers] (
    [id] INT IDENTITY(1,1) NOT NULL,
    [name] NVARCHAR(100) NOT NULL,
    CONSTRAINT [pk_customers] PRIMARY KEY ([id])
);

-- [W138] UNIQUE on nullable column(s) 'uuid_field': SQL Server treats NULL as a value in unique constraints, so at most one NULL row is allowed (PostgreSQL/MySQL/SQLite allow many).
-- Hint: Use a filtered unique index (WHERE column IS NOT NULL) if multiple NULL rows must coexist.
-- [E057] Cascading referential action of foreign key 'fk_composite' ('orders' → 'customers') was rendered as NO ACTION: SQL Server rejects cascade cycles and multiple cascade paths (error 1785).
-- Hint: Implement the cascade with an AFTER DELETE/UPDATE trigger, or restructure the cascade paths.
-- [E055] RANGE partitioning of table 'orders' is not rendered for SQL Server (partition function, scheme and filegroups are not carried in the neutral model); created as a plain table.
-- Hint: Create the partition function and scheme manually and rebuild the table on the scheme.
CREATE TABLE [orders] (
    [id] INT IDENTITY(1,1) NOT NULL,
    [customer_id] INT NOT NULL,
    [status] NVARCHAR(9) CONSTRAINT [df_orders_status] DEFAULT N'pending' CONSTRAINT [ck_orders_status] CHECK ([status] IN (N'pending', N'shipped', N'delivered')),
    [date] DATETIMEOFFSET CONSTRAINT [df_orders_date] DEFAULT SYSDATETIMEOFFSET(),
    [uuid_field] UNIQUEIDENTIFIER CONSTRAINT [df_orders_uuid_field] DEFAULT NEWID(),
    [active] BIT CONSTRAINT [df_orders_active] DEFAULT 1,
    [amount] DECIMAL(10,2) CONSTRAINT [df_orders_amount] DEFAULT 0,
    [invoice_number] BIGINT CONSTRAINT [df_orders_invoice_number] DEFAULT NEXT VALUE FOR [invoice_seq],
    CONSTRAINT [fk_orders_customer_id] FOREIGN KEY ([customer_id]) REFERENCES [customers] ([id]) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT [chk_amount] CHECK (amount >= 0),
    CONSTRAINT [uq_uuid] UNIQUE ([uuid_field]),
    CONSTRAINT [fk_composite] FOREIGN KEY ([customer_id]) REFERENCES [customers] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT [pk_orders] PRIMARY KEY ([id])
);

-- [W102] HASH index 'idx_customer' has no SQL Server equivalent; created as a nonclustered index.
-- Hint: SQL Server rowstore indexes are B-tree based; review whether the index is still useful.
CREATE INDEX [idx_customer] ON [orders] ([customer_id]);

CREATE OR ALTER VIEW [active_orders] AS
SELECT * FROM orders WHERE status != 'delivered'
;

-- [W103] Materialized views are not supported in SQL Server. Created as a regular view instead.
-- Hint: Consider an indexed view (schema-bound, with restrictions) or a refreshed table.
CREATE OR ALTER VIEW [monthly_stats] AS
SELECT COUNT(*) FROM orders
;

-- [E053] Function 'calc_total' was written for 'postgresql' and must be manually rewritten for SQL Server.
-- Hint: Create the function as T-SQL (CREATE OR ALTER …) manually on the target.

-- [E053] Procedure 'update_status' was written for 'postgresql' and must be manually rewritten for SQL Server.
-- Hint: Create the procedure as T-SQL (CREATE OR ALTER …) manually on the target.

-- [E053] Trigger 'trg_updated' was written for 'postgresql' and must be manually rewritten for SQL Server.
-- Hint: Create the trigger as T-SQL (CREATE OR ALTER …) manually on the target.

-- [E053] Trigger 'trg_insert' has no body and must be manually implemented.
-- Hint: Create the trigger as T-SQL (CREATE OR ALTER …) manually on the target.
