-- Generated by d-migrate 0.9.3
-- Source: neutral schema v1.0.0 "Full Featured Schema"
-- Target: mysql | Generated: 2026-04-21T00:00:00Z

-- [E054] Composite type 'address' is not supported in MySQL and was skipped.
-- Hint: Consider restructuring the data model to avoid composite types.


CREATE TABLE `dmg_sequences` (
    `managed_by` VARCHAR(32) NOT NULL,
    `format_version` VARCHAR(32) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `next_value` BIGINT NOT NULL,
    `increment_by` BIGINT NOT NULL,
    `min_value` BIGINT NULL,
    `max_value` BIGINT NULL,
    `cycle_enabled` TINYINT(1) NOT NULL,
    `cache_size` INT NULL,
    PRIMARY KEY (`name`)
) ENGINE=InnoDB;

INSERT INTO `dmg_sequences` (`managed_by`, `format_version`, `name`, `next_value`, `increment_by`, `min_value`, `max_value`, `cycle_enabled`, `cache_size`) VALUES ('d-migrate', 'mysql-sequence-v1', 'invoice_seq', 10000, 1, 10000, 99999999, 0, 20);

INSERT INTO `dmg_sequences` (`managed_by`, `format_version`, `name`, `next_value`, `increment_by`, `min_value`, `max_value`, `cycle_enabled`, `cache_size`) VALUES ('d-migrate', 'mysql-sequence-v1', 'simple_seq', 1, 1, NULL, NULL, 0, NULL);

-- [W114] Sequence 'invoice_seq' has cache=20 but MySQL helper-table mode does not emulate preallocation; cache value is stored as metadata only.


CREATE TABLE `customers` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- [W100] DATETIME with timezone on column 'date' mapped to DATETIME in MySQL which does not support time zones.
-- Hint: Store timezone information in a separate column or use UTC consistently.
-- [W112] RANGE partition expressions may need manual adjustment for MySQL (e.g., wrapping date columns with YEAR()).
-- Hint: Review the partition key expressions and adjust for MySQL-specific syntax if needed.
-- [W115] SequenceNextVal on 'invoice_number' uses lossy MySQL trigger semantics; explicit NULL is treated like an omitted value.
CREATE TABLE `orders` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `customer_id` INT NOT NULL,
    `status` ENUM('pending', 'shipped', 'delivered') DEFAULT 'pending',
    `date` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `uuid_field` CHAR(36) DEFAULT (UUID()),
    `active` TINYINT(1) DEFAULT 1,
    `amount` DECIMAL(10,2) DEFAULT 0,
    `invoice_number` BIGINT,
    CONSTRAINT `fk_orders_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT `chk_amount` CHECK (amount >= 0),
    CONSTRAINT `uq_uuid` UNIQUE (`uuid_field`),
    CONSTRAINT `fk_composite` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY (`id`)
)
PARTITION BY RANGE (`date`) (
    PARTITION `orders_2024` VALUES LESS THAN (2025-01-01),
    PARTITION `orders_2025` VALUES LESS THAN (2026-01-01)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- [W102] HASH index 'idx_customer' is not supported on InnoDB; converted to BTREE.
-- Hint: InnoDB only supports BTREE indexes. The HASH index has been automatically converted.
CREATE INDEX `idx_customer` ON `orders` USING BTREE (`customer_id`);

CREATE OR REPLACE VIEW `active_orders` AS
SELECT * FROM orders WHERE status != 'delivered'
;

-- [W103] Materialized views are not supported in MySQL. Created as a regular view instead.
-- Hint: Consider using a table with a scheduled refresh procedure to emulate materialized views.
CREATE OR REPLACE VIEW `monthly_stats` AS
SELECT COUNT(*) FROM orders
;

DELIMITER //
/* d-migrate:mysql-sequence-v1 object=nextval */
CREATE FUNCTION `dmg_nextval`(seq_name VARCHAR(255))
RETURNS BIGINT
DETERMINISTIC
MODIFIES SQL DATA
BEGIN
    DECLARE val BIGINT;
    UPDATE `dmg_sequences` SET `next_value` = `next_value` + `increment_by` WHERE `name` = seq_name;
    SELECT `next_value` - `increment_by` INTO val FROM `dmg_sequences` WHERE `name` = seq_name;
    RETURN val;
END //
DELIMITER ;

DELIMITER //
/* d-migrate:mysql-sequence-v1 object=setval */
CREATE FUNCTION `dmg_setval`(seq_name VARCHAR(255), new_value BIGINT)
RETURNS BIGINT
DETERMINISTIC
MODIFIES SQL DATA
BEGIN
    UPDATE `dmg_sequences` SET `next_value` = new_value WHERE `name` = seq_name;
    RETURN new_value;
END //
DELIMITER ;

-- [E053] Function 'calc_total' was written for 'postgresql' and must be manually rewritten for MySQL.
-- Hint: Rewrite the function body using MySQL-compatible syntax.
-- TODO: Rewrite function `calc_total` for MySQL (source dialect: postgresql)

-- [E053] Procedure 'update_status' was written for 'postgresql' and must be manually rewritten for MySQL.
-- Hint: Rewrite the procedure body using MySQL-compatible syntax.
-- TODO: Rewrite procedure `update_status` for MySQL (source dialect: postgresql)

DELIMITER //
/* d-migrate:mysql-sequence-v1 object=sequence-trigger sequence=invoice_seq table=orders column=invoice_number */
CREATE TRIGGER `dmg_seq_orders_invoice_number_7b0a7b2f55_bi`
    BEFORE INSERT ON `orders`
    FOR EACH ROW
BEGIN
    IF NEW.`invoice_number` IS NULL THEN
        SET NEW.`invoice_number` = `dmg_nextval`('invoice_seq');
    END IF;
END //
DELIMITER ;

-- [E053] Trigger 'trg_updated' was written for 'postgresql' and must be manually rewritten for MySQL.
-- Hint: Rewrite the trigger body using MySQL-compatible syntax.
-- TODO: Rewrite trigger `trg_updated` for MySQL (source dialect: postgresql)

-- [E053] Trigger 'trg_insert' has no body and must be manually implemented.
-- Hint: Provide a trigger body in the schema definition.
-- TODO: Implement trigger `trg_insert`