-- Generated by d-migrate 1.2.0
-- Source: neutral schema v1.0.0 "Fulltext Schema"
-- Target: oracle

-- [W132] Full-text column 'search_vector' degraded to CLOB; Oracle has no full-text vector column type.
-- Hint: Declare a full-text index over the source text column(s); d-migrate renders it as an Oracle Text index.
CREATE TABLE "articles" (
    "id" NUMBER(9) GENERATED ALWAYS AS IDENTITY,
    "title" VARCHAR2(200) NOT NULL,
    "body" CLOB,
    "search_vector" CLOB,
    CONSTRAINT "pk_articles" PRIMARY KEY ("id")
);

-- [E057] Full-text index 'ft_articles' on table 'articles' covers 2 columns; an Oracle Text index covers exactly one (ORA-29851), and splitting it would change what a search matches.
-- Hint: Index a single column, or create a MULTI_COLUMN_DATASTORE preference and the index manually on the target.
