-- Generated by d-migrate 1.2.0
-- Source: neutral schema v1.0.0 "Fulltext Schema"
-- Target: oracle

-- [W132] Full-text column 'search_vector' degraded to CLOB; Oracle has no full-text vector column type.
-- Hint: To restore full-text search, create an Oracle Text index over the source text column(s) manually.
CREATE TABLE "articles" (
    "id" NUMBER(9) GENERATED ALWAYS AS IDENTITY,
    "title" VARCHAR2(200) NOT NULL,
    "body" CLOB,
    "search_vector" CLOB,
    CONSTRAINT "pk_articles" PRIMARY KEY ("id")
);

-- [E057] Full-text index 'ft_articles' on table 'articles' is not rendered for Oracle: Oracle Text indexing is not carried by the neutral model yet.
-- Hint: Create an Oracle Text index (CTXSYS.CONTEXT) manually on the target.
