-- Generated by d-migrate 0.9.7
-- Source: neutral schema v1.0.0 "Full Featured Schema"
-- Target: sqlite | Generated: 2026-05-29T11:17:09.059927160Z

-- [I001] Enum type 'order_status' mapped to inline TEXT + CHECK constraint in SQLite.
-- Enum type "order_status" is handled inline via CHECK constraints

-- [E054] Composite type 'address' is not supported in SQLite.
-- Hint: Flatten composite fields into individual table columns or use JSON.
-- Composite type "address" is not supported in SQLite

-- [I001] Domain type 'positive_amount' mapped to base type with inline CHECK constraint in SQLite.
-- Domain type "positive_amount" is mapped to its base type with inline CHECK in SQLite

CREATE TABLE IF NOT EXISTS "dmg_sequences" (
    "managed_by" TEXT NOT NULL,
    "format_version" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "next_value" INTEGER NOT NULL,
    "last_returned_value" INTEGER NULL,
    "exhausted" INTEGER NOT NULL DEFAULT 0,
    "increment_by" INTEGER NOT NULL,
    "min_value" INTEGER NULL,
    "max_value" INTEGER NULL,
    "cycle_enabled" INTEGER NOT NULL,
    "cache_size" INTEGER NULL,
    PRIMARY KEY ("name")
);

INSERT INTO "dmg_sequences" ("managed_by", "format_version", "name", "next_value", "last_returned_value", "exhausted", "increment_by", "min_value", "max_value", "cycle_enabled", "cache_size") VALUES ('d-migrate', 'sqlite-sequence-v1', 'invoice_seq', 10000, NULL, 0, 1, 10000, 99999999, 0, 20);

INSERT INTO "dmg_sequences" ("managed_by", "format_version", "name", "next_value", "last_returned_value", "exhausted", "increment_by", "min_value", "max_value", "cycle_enabled", "cache_size") VALUES ('d-migrate', 'sqlite-sequence-v1', 'simple_seq', 1, NULL, 0, 1, NULL, NULL, 0, NULL);

-- [W114] Sequence 'invoice_seq' has cache=20 but SQLite helper-table mode does not emulate preallocation; cache value is stored as metadata only.

CREATE TABLE "customers" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL
);

-- [W200] Decimal(10,2) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
-- [E055] Table partitioning is not supported in SQLite for table 'orders'.
-- Hint: Partition data at the application level or use separate tables.
-- [W115] SequenceNextVal on 'invoice_number' uses lossy SQLite trigger semantics; explicit NULL is treated like an omitted value.
-- [W121] Sequence 'invoice_seq' on column 'invoice_number' may consume values without insertion under conflict-handling INSERT forms when the column is NULL/omitted (ON CONFLICT DO UPDATE/DO NOTHING, INSERT OR IGNORE, INSERT OR FAIL on multi-row inserts). INSERTs with explicit non-NULL values bypass the sequence trigger. ON CONFLICT ABORT/ROLLBACK roll the increment back and produce no gap.
-- [W122] AFTER INSERT sequence trigger on 'orders.invoice_number' performs an UPDATE on the same table; existing user-defined UPDATE triggers will fire when PRAGMA recursive_triggers is ON — verify compatibility (e.g. audit triggers logging the sequence assignment as a data change).
-- Hint: Under the SQLite default (recursive_triggers = OFF) this warning is moot.
CREATE TABLE "orders" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "customer_id" INTEGER NOT NULL REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION,
    "status" TEXT DEFAULT 'pending' CHECK ("status" IN ('pending', 'shipped', 'delivered')),
    "date" TEXT DEFAULT (datetime('now')),
    "uuid_field" TEXT DEFAULT (lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6)))),
    "active" INTEGER DEFAULT 1,
    "amount" REAL DEFAULT 0,
    "invoice_number" INTEGER,
    CONSTRAINT "chk_amount" CHECK (amount >= 0),
    CONSTRAINT "uq_uuid" UNIQUE ("uuid_field"),
    CONSTRAINT "fk_composite" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- [W102] HASH index 'idx_customer' on table 'orders' is not supported in SQLite. Only BTREE is available.
-- Hint: The index has been skipped. If needed, create a standard BTREE index instead.
-- Index "idx_customer" skipped: HASH index type is not supported in SQLite

CREATE VIEW IF NOT EXISTS "active_orders" AS
SELECT * FROM orders WHERE status != 'delivered'
;

-- [W103] Materialized view 'monthly_stats' is not supported in SQLite. Created as a regular VIEW instead.
-- Hint: If materialization is needed, consider caching query results in a regular table via triggers or application logic.
CREATE VIEW IF NOT EXISTS "monthly_stats" AS
SELECT COUNT(*) FROM orders
;
