-- Generated by d-migrate 1.2.0
-- Source: neutral schema v1.0.0 "Full Featured Schema"
-- Target: oracle

-- [E054] Composite type 'address' is not supported in Oracle and was skipped.
-- Hint: Flatten the fields into columns, or store the value as JSON.

CREATE SEQUENCE "invoice_seq" START WITH 10000 INCREMENT BY 1 MINVALUE 10000 MAXVALUE 99999999 NOCYCLE CACHE 20;

CREATE SEQUENCE "simple_seq" START WITH 1 INCREMENT BY 1 NOMINVALUE NOMAXVALUE NOCYCLE NOCACHE;

CREATE TABLE "customers" (
    "id" NUMBER(9) GENERATED ALWAYS AS IDENTITY,
    "name" VARCHAR2(100) NOT NULL,
    CONSTRAINT "pk_customers" PRIMARY KEY ("id")
);

-- [W150] Default 'gen_uuid' on column 'uuid_field' is rendered as RAWTOHEX(SYS_GUID()): 32 hex characters without dashes, unlike the standard UUID text format.
-- Hint: Wrap with REGEXP_REPLACE to insert dashes if the standard UUID format is required.
-- [E055] RANGE partitioning of table 'orders' is not rendered for Oracle (partition clauses are not carried in the neutral model); created as a plain table.
-- Hint: Add PARTITION BY manually and rebuild the table.
CREATE TABLE "orders" (
    "id" NUMBER(9) GENERATED ALWAYS AS IDENTITY,
    "customer_id" NUMBER(9) NOT NULL,
    "status" VARCHAR2(9) DEFAULT 'pending' CONSTRAINT "ck_orders_status" CHECK ("status" IN ('pending', 'shipped', 'delivered')),
    "date" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    "uuid_field" VARCHAR2(36) DEFAULT RAWTOHEX(SYS_GUID()),
    "active" NUMBER(1) DEFAULT 1,
    "amount" NUMBER(10,2) DEFAULT 0,
    "invoice_number" NUMBER(18) DEFAULT "invoice_seq".NEXTVAL,
    CONSTRAINT "fk_orders_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE CASCADE,
    CONSTRAINT "chk_amount" CHECK (amount >= 0),
    CONSTRAINT "uq_uuid" UNIQUE ("uuid_field"),
    CONSTRAINT "fk_composite" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id"),
    CONSTRAINT "pk_orders" PRIMARY KEY ("id")
);

-- [W102] HASH index 'idx_customer' has no Oracle equivalent; created as a standard B-tree index.
-- Hint: Oracle B-tree indexes cover most access patterns; review whether the index is still useful.
CREATE INDEX "idx_customer" ON "orders" ("customer_id");

CREATE OR REPLACE FORCE VIEW "active_orders" AS
SELECT * FROM orders WHERE status != 'delivered'
;

-- [W103] Materialized views are not rendered for Oracle yet. Created as a regular view instead.
-- Hint: Oracle materialized views (Slice 10) will restore refresh semantics once built.
CREATE OR REPLACE FORCE VIEW "monthly_stats" AS
SELECT COUNT(*) FROM orders
;

-- [E053] Function 'calc_total' was written for 'postgresql' and must be manually rewritten for Oracle.
-- Hint: Create the function as PL/SQL (CREATE OR REPLACE ...) manually on the target.

-- [E053] Procedure 'update_status' was written for 'postgresql' and must be manually rewritten for Oracle.
-- Hint: Create the procedure as PL/SQL (CREATE OR REPLACE ...) manually on the target.

-- [E053] Trigger 'trg_updated' was written for 'postgresql' and must be manually rewritten for Oracle.
-- Hint: Create the trigger as PL/SQL (CREATE OR REPLACE ...) manually on the target.

-- [E053] Trigger 'trg_insert' has no body and must be manually implemented.
-- Hint: Create the trigger as PL/SQL (CREATE OR REPLACE ...) manually on the target.
