-- Generated by d-migrate 1.0.3
-- Source: neutral schema v1.0.0 "Fulltext Schema"
-- Target: sqlite

-- [W132] Full-text column 'search_vector' degraded to TEXT; SQLite full-text search is an FTS5 virtual table, not a column type.
-- Hint: To restore full-text search, create an FTS5 virtual table over the source text with sync triggers; structural cross-dialect translation is a future slice.
CREATE TABLE "articles" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "body" TEXT,
    "search_vector" TEXT
);

CREATE VIRTUAL TABLE "ft_articles" USING fts5("title", "body", content='articles');

INSERT INTO "ft_articles"("ft_articles") VALUES('rebuild');

CREATE TRIGGER "ft_articles_ai" AFTER INSERT ON "articles" BEGIN
    INSERT INTO "ft_articles"(rowid, "title", "body") VALUES (new.rowid, new."title", new."body");
END;

CREATE TRIGGER "ft_articles_ad" AFTER DELETE ON "articles" BEGIN
    INSERT INTO "ft_articles"("ft_articles", rowid, "title", "body") VALUES('delete', old.rowid, old."title", old."body");
END;

CREATE TRIGGER "ft_articles_au" AFTER UPDATE ON "articles" BEGIN
    INSERT INTO "ft_articles"("ft_articles", rowid, "title", "body") VALUES('delete', old.rowid, old."title", old."body");
    INSERT INTO "ft_articles"(rowid, "title", "body") VALUES (new.rowid, new."title", new."body");
END;
