-- Generated by d-migrate 0.9.5
-- Source: neutral schema v1.0.0 "Full Featured Schema"
-- Target: mysql | Generated: 2026-04-05T17:28:51.369672745Z

-- [E054] Composite type 'address' is not supported in MySQL and was skipped.
-- Hint: Consider restructuring the data model to avoid composite types.

-- [E056] Sequence 'invoice_seq' is not supported in MySQL without helper_table mode.
-- Hint: Add --mysql-named-sequences helper_table to enable sequence emulation.

-- [E056] Sequence 'simple_seq' is not supported in MySQL without helper_table mode.
-- Hint: Add --mysql-named-sequences helper_table to enable sequence emulation.

CREATE TABLE `customers` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- [W100] DATETIME with timezone on column 'date' mapped to DATETIME in MySQL which does not support time zones.
-- Hint: Store timezone information in a separate column or use UTC consistently.
-- [W112] RANGE partition expressions may need manual adjustment for MySQL (e.g., wrapping date columns with YEAR()).
-- Hint: Review the partition key expressions and adjust for MySQL-specific syntax if needed.
-- [E056] Sequence-based default on 'invoice_number' requires --mysql-named-sequences helper_table to generate support objects.
-- Hint: Add --mysql-named-sequences helper_table to enable sequence emulation.
CREATE TABLE `orders` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `customer_id` INT NOT NULL,
    `status` ENUM('pending', 'shipped', 'delivered') DEFAULT 'pending',
    `date` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `uuid_field` CHAR(36) DEFAULT (UUID()),
    `active` TINYINT(1) DEFAULT 1,
    `amount` DECIMAL(10,2) DEFAULT 0,
    `invoice_number` BIGINT,
    CONSTRAINT `fk_orders_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT `chk_amount` CHECK (amount >= 0),
    CONSTRAINT `uq_uuid` UNIQUE (`uuid_field`),
    CONSTRAINT `fk_composite` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY (`id`)
)
PARTITION BY RANGE (`date`) (
    PARTITION `orders_2024` VALUES LESS THAN (2025-01-01),
    PARTITION `orders_2025` VALUES LESS THAN (2026-01-01)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- [W102] HASH index 'idx_customer' is not supported on InnoDB; converted to BTREE.
-- Hint: InnoDB only supports BTREE indexes. The HASH index has been automatically converted.
CREATE INDEX `idx_customer` ON `orders` USING BTREE (`customer_id`);

CREATE OR REPLACE VIEW `active_orders` AS
SELECT * FROM orders WHERE status != 'delivered'
;

-- [W103] Materialized views are not supported in MySQL. Created as a regular view instead.
-- Hint: Consider using a table with a scheduled refresh procedure to emulate materialized views.
CREATE OR REPLACE VIEW `monthly_stats` AS
SELECT COUNT(*) FROM orders
;

-- [E053] Function 'calc_total' was written for 'postgresql' and must be manually rewritten for MySQL.
-- Hint: Rewrite the function body using MySQL-compatible syntax.

-- [E053] Procedure 'update_status' was written for 'postgresql' and must be manually rewritten for MySQL.
-- Hint: Rewrite the procedure body using MySQL-compatible syntax.

-- [E053] Trigger 'trg_updated' was written for 'postgresql' and must be manually rewritten for MySQL.
-- Hint: Rewrite the trigger body using MySQL-compatible syntax.

-- [E053] Trigger 'trg_insert' has no body and must be manually implemented.
-- Hint: Provide a trigger body in the schema definition.
