-- Generated by d-migrate 1.0.3
-- Source: neutral schema v1.0.0 "Fulltext Schema"
-- Target: postgresql

CREATE TABLE "articles" (
    "id" SERIAL,
    "title" VARCHAR(200) NOT NULL,
    "body" TEXT,
    "search_vector" tsvector,
    PRIMARY KEY ("id")
);

CREATE INDEX "ft_articles" ON "articles" USING GIST ("search_vector");
