-- Generated by d-migrate 0.9.3
-- Target: mysql (helper_table post-data)

DELIMITER //
/* d-migrate:mysql-sequence-v1 object=nextval */
CREATE FUNCTION `dmg_nextval`(seq_name VARCHAR(255))
RETURNS BIGINT
DETERMINISTIC
MODIFIES SQL DATA
BEGIN
    DECLARE val BIGINT;
    UPDATE `dmg_sequences` SET `next_value` = `next_value` + `increment_by` WHERE `name` = seq_name;
    SELECT `next_value` - `increment_by` INTO val FROM `dmg_sequences` WHERE `name` = seq_name;
    RETURN val;
END //
DELIMITER ;

DELIMITER //
/* d-migrate:mysql-sequence-v1 object=setval */
CREATE FUNCTION `dmg_setval`(seq_name VARCHAR(255), new_value BIGINT)
RETURNS BIGINT
DETERMINISTIC
MODIFIES SQL DATA
BEGIN
    UPDATE `dmg_sequences` SET `next_value` = new_value WHERE `name` = seq_name;
    RETURN new_value;
END //
DELIMITER ;

-- [E053] Function 'calc_total' was written for 'postgresql' and must be manually rewritten for MySQL.
-- Hint: Rewrite the function body using MySQL-compatible syntax.
-- TODO: Rewrite function `calc_total` for MySQL (source dialect: postgresql)

-- [E053] Procedure 'update_status' was written for 'postgresql' and must be manually rewritten for MySQL.
-- Hint: Rewrite the procedure body using MySQL-compatible syntax.
-- TODO: Rewrite procedure `update_status` for MySQL (source dialect: postgresql)

DELIMITER //
/* d-migrate:mysql-sequence-v1 object=sequence-trigger sequence=invoice_seq table=orders column=invoice_number */
CREATE TRIGGER `dmg_seq_orders_invoice_number_7b0a7b2f55_bi`
    BEFORE INSERT ON `orders`
    FOR EACH ROW
BEGIN
    IF NEW.`invoice_number` IS NULL THEN
        SET NEW.`invoice_number` = `dmg_nextval`('invoice_seq');
    END IF;
END //
DELIMITER ;

-- [E053] Trigger 'trg_updated' was written for 'postgresql' and must be manually rewritten for MySQL.
-- Hint: Rewrite the trigger body using MySQL-compatible syntax.
-- TODO: Rewrite trigger `trg_updated` for MySQL (source dialect: postgresql)

-- [E053] Trigger 'trg_insert' has no body and must be manually implemented.
-- Hint: Provide a trigger body in the schema definition.
-- TODO: Implement trigger `trg_insert`