-- Generated by d-migrate 1.0.3
-- Source: neutral schema v1.0.0 "Fulltext Schema"
-- Target: mssql

-- [W132] Full-text column 'search_vector' degraded to NVARCHAR(MAX); SQL Server has no full-text vector column type.
-- Hint: To restore full-text search, create a full-text catalog and index over the source text column(s) manually.
CREATE TABLE [articles] (
    [id] INT IDENTITY(1,1) NOT NULL,
    [title] NVARCHAR(200) NOT NULL,
    [body] NVARCHAR(MAX),
    [search_vector] NVARCHAR(MAX),
    CONSTRAINT [pk_articles] PRIMARY KEY ([id])
);

-- [W146] Full-text catalog 'ftc_articles' was created for table 'articles' alone. SQL Server shares catalogs across tables; the neutral model carries no catalog, so a shared original becomes one per table.
-- Hint: Functionally equivalent; consolidate the catalogs manually if the sharing matters.
IF NOT EXISTS (SELECT 1 FROM sys.fulltext_catalogs WHERE name = 'ftc_articles') CREATE FULLTEXT CATALOG [ftc_articles];
CREATE FULLTEXT INDEX ON [articles] ([title], [body]) KEY INDEX [pk_articles] ON [ftc_articles];
