-- Generated by d-migrate 0.9.3
-- Source: neutral schema v1.0.0 "Minimal Schema"
-- Target: mysql | Generated: 2026-04-05T17:28:19.579851092Z

CREATE TABLE `users` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
