-- Generated by d-migrate 0.9.5
-- Source: neutral schema v1.0.0 "Minimal Schema"
-- Target: postgresql | Generated: 2026-04-05T17:28:18.201693337Z

CREATE TABLE "users" (
    "id" SERIAL,
    "name" VARCHAR(100) NOT NULL,
    PRIMARY KEY ("id")
);
