-- Generated by d-migrate 1.0.3
-- Source: neutral schema v1.0.0 "Minimal Schema"
-- Target: mssql

CREATE TABLE [users] (
    [id] INT IDENTITY(1,1) NOT NULL,
    [name] NVARCHAR(100) NOT NULL,
    CONSTRAINT [pk_users] PRIMARY KEY ([id])
);
