-- Generated by d-migrate 0.9.4
-- Source: neutral schema v1.0.0 "Minimal Schema"
-- Target: sqlite | Generated: 2026-04-05T17:28:20.810559458Z

CREATE TABLE "users" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL
);
