-- Generated by d-migrate 1.2.0
-- Source: neutral schema v1.0.0 "Minimal Schema"
-- Target: oracle

CREATE TABLE "users" (
    "id" NUMBER(9) GENERATED ALWAYS AS IDENTITY,
    "name" VARCHAR2(100) NOT NULL,
    CONSTRAINT "pk_users" PRIMARY KEY ("id")
);
