-- Generated by d-migrate 1.8.0-SNAPSHOT
-- Source: neutral schema v1.0.0 "Spatial Schema"
-- Target: oracle

-- [W120] Geometry column 'location' is rendered as SDO_GEOMETRY: Oracle carries neither the subtype ('point') nor the SRID (4326) on the column. The SRID would live in USER_SDO_GEOM_METADATA, and Oracle upper-cases the table and column name in that row, so no row can describe a quoted lower- or mixed-case name like 'places.location'.
-- Hint: Use an upper-case table and column name in the schema file and register the metadata row, if the coordinate system must be declared; the spatial index and spatial queries work without it. Do not insert the row by hand for this table — Oracle would store an upper-case name, which names a different table.
-- [W120] Geometry column 'area' is rendered as SDO_GEOMETRY: Oracle carries neither the subtype ('polygon') nor the SRID (none) on the column. The SRID would live in USER_SDO_GEOM_METADATA, and Oracle upper-cases the table and column name in that row, so no row can describe a quoted lower- or mixed-case name like 'places.area'.
-- Hint: Use an upper-case table and column name in the schema file and register the metadata row, if the coordinate system must be declared; the spatial index and spatial queries work without it. Do not insert the row by hand for this table — Oracle would store an upper-case name, which names a different table.
CREATE TABLE "places" (
    "id" NUMBER(9) GENERATED ALWAYS AS IDENTITY,
    "name" VARCHAR2(100) NOT NULL,
    "location" SDO_GEOMETRY,
    "area" SDO_GEOMETRY,
    "shape" SDO_GEOMETRY,
    CONSTRAINT "pk_places" PRIMARY KEY ("id")
);
