-- Generated by d-migrate 1.2.0
-- Source: neutral schema v1.0.0 "Spatial Schema"
-- Target: oracle

-- [W120] Geometry column 'location' is rendered as SDO_GEOMETRY: Oracle carries neither the subtype ('point') nor the SRID (4326) on the column. The SRID would live in USER_SDO_GEOM_METADATA, and Oracle upper-cases the table and column name in that row, so it cannot describe a quoted lower-case table like 'places'.
-- Hint: Insert the USER_SDO_GEOM_METADATA row manually if the coordinate system must be declared; the spatial index and spatial queries work without it.
-- [W120] Geometry column 'area' is rendered as SDO_GEOMETRY: Oracle carries neither the subtype ('polygon') nor the SRID (none) on the column. The SRID would live in USER_SDO_GEOM_METADATA, and Oracle upper-cases the table and column name in that row, so it cannot describe a quoted lower-case table like 'places'.
-- Hint: Insert the USER_SDO_GEOM_METADATA row manually if the coordinate system must be declared; the spatial index and spatial queries work without it.
CREATE TABLE "places" (
    "id" NUMBER(9) GENERATED ALWAYS AS IDENTITY,
    "name" VARCHAR2(100) NOT NULL,
    "location" SDO_GEOMETRY,
    "area" SDO_GEOMETRY,
    "shape" SDO_GEOMETRY,
    CONSTRAINT "pk_places" PRIMARY KEY ("id")
);
