-- Generated by d-migrate
-- Source: neutral schema v1.0.0 "Spatial Schema"
-- Target: sqlite

CREATE TABLE "places" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL
);

SELECT AddGeometryColumn('places', 'location', 4326, 'POINT', 'XY');

SELECT AddGeometryColumn('places', 'area', 0, 'POLYGON', 'XY');

SELECT AddGeometryColumn('places', 'shape', 0, 'GEOMETRY', 'XY');
