-- Generated by d-migrate
-- Source: neutral schema v1.0.0 "Spatial Schema"
-- Target: mysql

-- [W120] SRID 4326 emitted as MySQL comment hint; full SRID constraint support depends on MySQL 8.0+
CREATE TABLE `places` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `location` POINT /*!80003 SRID 4326 */,
    `area` POLYGON,
    `shape` GEOMETRY,
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
