-- Generated by d-migrate 1.0.3
-- Source: neutral schema v1.0.0 "Spatial Schema"
-- Target: mssql

-- [W120] Geometry column 'location' is rendered as `geography`: SQL Server carries the subtype ('point') and the SRID (4326) per value, not per column.
-- Hint: Enforce the subtype/SRID with a CHECK constraint (e.g. STGeometryType()/STSrid) if required.
-- [W120] Geometry column 'area' is rendered as `geometry`: SQL Server carries the subtype ('polygon') and the SRID (none) per value, not per column.
-- Hint: Enforce the subtype/SRID with a CHECK constraint (e.g. STGeometryType()/STSrid) if required.
CREATE TABLE [places] (
    [id] INT IDENTITY(1,1) NOT NULL,
    [name] NVARCHAR(100) NOT NULL,
    [location] geography,
    [area] geometry,
    [shape] geometry,
    CONSTRAINT [pk_places] PRIMARY KEY ([id])
);
