-- Generated by d-migrate 1.0.3
-- Source: neutral schema v1.0.0 "T-SQL Routines"

CREATE TABLE [orders] (
    [id] INT IDENTITY(1,1) NOT NULL,
    [amount] DECIMAL(10,2),
    CONSTRAINT [pk_orders] PRIMARY KEY ([id])
);

CREATE OR ALTER FUNCTION [order_total](@order_id INT)
RETURNS DECIMAL(10,2) AS
BEGIN
    RETURN (SELECT SUM(amount) FROM orders WHERE id = @order_id);
END
;

CREATE OR ALTER FUNCTION [open_orders](@min_id INT)
RETURNS TABLE AS
RETURN (SELECT id, amount FROM orders WHERE id >= @min_id)
;

CREATE OR ALTER PROCEDURE [bump_amount](@order_id INT, @affected INT OUTPUT) AS
BEGIN
    UPDATE orders SET amount = amount + 1 WHERE id = @order_id;
    SET @affected = @@ROWCOUNT;
END
;

CREATE OR ALTER TRIGGER [trg_orders_audit] ON [orders]
AFTER INSERT, UPDATE AS
BEGIN
    SET NOCOUNT ON;
END
;
