-- Generated by d-migrate 0.9.4
-- Source: neutral schema v1.0.0 "View Function Dependencies"
-- Target: mysql | Generated: 2026-04-19T14:20:31.422918812Z

CREATE TABLE `orders` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `amount` DECIMAL(10,2),
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE OR REPLACE VIEW `simple_view` AS
SELECT * FROM orders WHERE amount > 0;
