-- Generated by d-migrate 0.9.1
-- Source: neutral schema v1.0.0 "View Function Dependencies"
-- Target: postgresql | Generated: 2026-04-19T14:20:30.386537878Z

CREATE TABLE "orders" (
    "id" SERIAL,
    "amount" DECIMAL(10,2),
    PRIMARY KEY ("id")
);

CREATE OR REPLACE VIEW "simple_view" AS
SELECT * FROM orders WHERE amount > 0;
