-- Generated by d-migrate 0.9.4
-- Source: neutral schema v1.0.0 "View Function Dependencies"
-- Target: sqlite | Generated: 2026-04-19T14:20:32.456998280Z

-- [W200] Decimal(10,2) mapped to REAL in SQLite. Precision may be lost.
-- Hint: Store as TEXT if exact decimal precision is required.
CREATE TABLE "orders" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "amount" REAL
);

CREATE VIEW IF NOT EXISTS "simple_view" AS
SELECT * FROM orders WHERE amount > 0;
