-- Generated by d-migrate 1.0.3
-- Source: neutral schema v1.0.0 "View Function Dependencies"
-- Target: mssql

CREATE TABLE [orders] (
    [id] INT IDENTITY(1,1) NOT NULL,
    [amount] DECIMAL(10,2),
    CONSTRAINT [pk_orders] PRIMARY KEY ([id])
);

CREATE OR ALTER VIEW [simple_view] AS
SELECT * FROM orders WHERE amount > 0;
