package dev.dmigrate.driver.sqlite

import dev.dmigrate.core.model.*
import dev.dmigrate.driver.*
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import io.kotest.matchers.string.shouldStartWith

class SqliteDdlGeneratorTest : FunSpec({

    val generator = SqliteDdlGenerator()

    // ── Helper functions ────────────────────────────────────────────

    fun schema(
        tables: Map<String, TableDefinition> = emptyMap(),
        customTypes: Map<String, CustomTypeDefinition> = emptyMap(),
        sequences: Map<String, SequenceDefinition> = emptyMap(),
        views: Map<String, ViewDefinition> = emptyMap(),
        functions: Map<String, FunctionDefinition> = emptyMap(),
        procedures: Map<String, ProcedureDefinition> = emptyMap(),
        triggers: Map<String, TriggerDefinition> = emptyMap()
    ) = SchemaDefinition(
        name = "test-schema",
        version = "1.0.0",
        customTypes = customTypes,
        tables = tables,
        sequences = sequences,
        views = views,
        functions = functions,
        procedures = procedures,
        triggers = triggers
    )

    fun table(
        columns: Map<String, ColumnDefinition> = emptyMap(),
        primaryKey: List<String> = emptyList(),
        indices: List<IndexDefinition> = emptyList(),
        constraints: List<ConstraintDefinition> = emptyList(),
        partitioning: PartitionConfig? = null
    ) = TableDefinition(
        columns = columns,
        primaryKey = primaryKey,
        indices = indices,
        constraints = constraints,
        partitioning = partitioning
    )

    fun col(
        type: NeutralType,
        required: Boolean = false,
        unique: Boolean = false,
        default: DefaultValue? = null,
        references: ReferenceDefinition? = null
    ) = ColumnDefinition(
        type = type,
        required = required,
        unique = unique,
        default = default,
        references = references
    )

    fun ref(
        table: String,
        column: String,
        onDelete: ReferentialAction? = null,
        onUpdate: ReferentialAction? = null
    ) = ReferenceDefinition(table, column, onDelete, onUpdate)

    /** Extracts the rendered SQL from DdlResult, skipping the header comment. */
    fun DdlResult.tableSql(): String {
        // Filter to actual CREATE TABLE statements
        return statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE TABLE") }
    }

    /** Collects all SQL statements from a DdlResult (excluding header). */
    fun DdlResult.allSql(): List<String> =
        statements.map { it.sql.trim() }.filter { !it.startsWith("-- Generated by") && !it.startsWith("-- Source:") }

    // ── 1. Simple table with double-quoted identifiers ──────────────

    test("simple table uses double-quoted identifiers and CREATE TABLE") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "name" to col(NeutralType.Text(maxLength = 100), required = true),
                        "email" to col(NeutralType.Email, required = true, unique = true)
                    )
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "CREATE TABLE \"users\""
        sql shouldContain "\"name\" TEXT NOT NULL"
        sql shouldContain "\"email\" TEXT NOT NULL UNIQUE"
    }

    // ── 2. Identifier type produces INTEGER PRIMARY KEY AUTOINCREMENT ─

    test("identifier column produces INTEGER PRIMARY KEY AUTOINCREMENT without separate PK clause") {
        val s = schema(
            tables = mapOf(
                "items" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "label" to col(NeutralType.Text(), required = true)
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT"
        sql shouldNotContain "PRIMARY KEY (\"id\")"
    }

    // ── 3. Composite primary key (non-identifier) ───────────────────

    test("composite primary key emits separate PRIMARY KEY clause") {
        val s = schema(
            tables = mapOf(
                "order_items" to table(
                    columns = mapOf(
                        "order_id" to col(NeutralType.Integer, required = true),
                        "product_id" to col(NeutralType.Integer, required = true),
                        "quantity" to col(NeutralType.Integer, required = true)
                    ),
                    primaryKey = listOf("order_id", "product_id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "PRIMARY KEY (\"order_id\", \"product_id\")"
    }

    // ── 4. Inline foreign key with ON DELETE action ─────────────────

    test("inline foreign key produces REFERENCES with ON DELETE action") {
        val s = schema(
            tables = mapOf(
                "categories" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                ),
                "products" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "category_id" to col(
                            NeutralType.Integer,
                            required = true,
                            references = ref("categories", "id", onDelete = ReferentialAction.CASCADE)
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val productsSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("\"products\"") && it.startsWith("CREATE TABLE") }

        productsSql shouldContain "REFERENCES \"categories\"(\"id\") ON DELETE CASCADE"
    }

    // ── 5. Enum with inline values produces TEXT + CHECK ─────────────

    test("enum with inline values produces TEXT with CHECK constraint") {
        val s = schema(
            tables = mapOf(
                "tasks" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "status" to col(
                            NeutralType.Enum(values = listOf("open", "in_progress", "done")),
                            required = true
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"status\" TEXT NOT NULL CHECK (\"status\" IN ('open', 'in_progress', 'done'))"
    }

    // ── 6. Enum with ref_type resolves values from customTypes ──────

    test("enum with ref_type resolves values from custom types and produces CHECK constraint") {
        val s = schema(
            customTypes = mapOf(
                "priority_level" to CustomTypeDefinition(
                    kind = CustomTypeKind.ENUM,
                    values = listOf("low", "medium", "high", "critical")
                )
            ),
            tables = mapOf(
                "tickets" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "priority" to col(
                            NeutralType.Enum(refType = "priority_level"),
                            required = true
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"priority\" TEXT NOT NULL CHECK (\"priority\" IN ('low', 'medium', 'high', 'critical'))"
    }

    // ── 7. Composite custom type is skipped with E052 ───────────────

    test("composite custom type emits E052 action required note") {
        val s = schema(
            customTypes = mapOf(
                "address" to CustomTypeDefinition(
                    kind = CustomTypeKind.COMPOSITE,
                    fields = mapOf(
                        "street" to col(NeutralType.Text()),
                        "city" to col(NeutralType.Text())
                    )
                )
            )
        )
        val result = generator.generate(s)
        val notes = result.notes

        notes.any { it.code == "E052" && it.objectName == "address" } shouldBe true
        notes.any { it.message.contains("Composite type") } shouldBe true
    }

    // ── 8. Sequence is skipped with E052 ────────────────────────────

    test("sequence is skipped with E052 and added to skippedObjects") {
        val s = schema(
            sequences = mapOf(
                "order_seq" to SequenceDefinition(start = 1000, increment = 1)
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "sequence" && it.name == "order_seq" } shouldBe true
        result.notes.any { it.code == "E052" && it.objectName == "order_seq" } shouldBe true
    }

    // ── 9. Partitioning is skipped with E052 ────────────────────────

    test("table with partitioning emits E052 warning") {
        val s = schema(
            tables = mapOf(
                "events" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "created_at" to col(NeutralType.DateTime(), required = true)
                    ),
                    primaryKey = listOf("id"),
                    partitioning = PartitionConfig(
                        type = PartitionType.RANGE,
                        key = listOf("created_at")
                    )
                )
            )
        )
        val result = generator.generate(s)
        val notes = result.notes

        notes.any { it.code == "E052" && it.message.contains("partitioning") } shouldBe true
    }

    // ── 10. HASH index emits W102 warning and is skipped ────────────

    test("HASH index emits W102 warning and is skipped") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "email" to col(NeutralType.Email, required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_users_email",
                            columns = listOf("email"),
                            type = IndexType.HASH
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val notes = result.notes

        notes.any { it.code == "W102" && it.objectName == "idx_users_email" } shouldBe true
        // The actual CREATE INDEX should not appear
        result.statements.none {
            it.sql.trim().startsWith("CREATE INDEX \"idx_users_email\"") ||
                it.sql.trim().startsWith("CREATE UNIQUE INDEX \"idx_users_email\"")
        } shouldBe true
    }

    // ── 11. GIN/GIST/BRIN indices emit W102 warning ─────────────────

    test("GIN index emits W102 warning and is skipped") {
        val s = schema(
            tables = mapOf(
                "docs" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "content" to col(NeutralType.Json)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_docs_content",
                            columns = listOf("content"),
                            type = IndexType.GIN
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)

        result.notes.any { it.code == "W102" && it.message.contains("GIN") } shouldBe true
    }

    test("GIST index emits W102 warning and is skipped") {
        val s = schema(
            tables = mapOf(
                "locations" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "geom" to col(NeutralType.Text())
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_locations_geom",
                            columns = listOf("geom"),
                            type = IndexType.GIST
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)

        result.notes.any { it.code == "W102" && it.message.contains("GIST") } shouldBe true
    }

    test("BRIN index emits W102 warning and is skipped") {
        val s = schema(
            tables = mapOf(
                "logs" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "ts" to col(NeutralType.DateTime())
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_logs_ts",
                            columns = listOf("ts"),
                            type = IndexType.BRIN
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)

        result.notes.any { it.code == "W102" && it.message.contains("BRIN") } shouldBe true
    }

    // ── 12. BTREE index generates CREATE INDEX ──────────────────────

    test("BTREE index generates CREATE INDEX statement") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "email" to col(NeutralType.Email, required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_users_email",
                            columns = listOf("email"),
                            type = IndexType.BTREE
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val indexSql = result.statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE INDEX") }

        indexSql shouldBe "CREATE INDEX \"idx_users_email\" ON \"users\" (\"email\");"
    }

    test("BTREE unique index generates CREATE UNIQUE INDEX") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "email" to col(NeutralType.Email, required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_users_email_uniq",
                            columns = listOf("email"),
                            type = IndexType.BTREE,
                            unique = true
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val indexSql = result.statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE UNIQUE INDEX") }

        indexSql shouldBe "CREATE UNIQUE INDEX \"idx_users_email_uniq\" ON \"users\" (\"email\");"
    }

    // ── 13. Circular FK produces E019 error and skipped objects ──────

    test("circular foreign keys produce E019 error and are added to skipped objects") {
        val s = schema(
            tables = mapOf(
                "table_a" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "b_id" to col(
                            NeutralType.Integer,
                            references = ref("table_b", "id")
                        )
                    ),
                    primaryKey = listOf("id")
                ),
                "table_b" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "a_id" to col(
                            NeutralType.Integer,
                            references = ref("table_a", "id")
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)

        // Circular FK edges should produce E019 notes
        result.notes.any { it.code == "E019" } shouldBe true

        // Should have skipped objects of type "foreign_key"
        result.skippedObjects.any { it.type == "foreign_key" } shouldBe true
    }

    // ── 14. View uses CREATE VIEW IF NOT EXISTS (no OR REPLACE) ─────

    test("view produces CREATE VIEW IF NOT EXISTS without OR REPLACE") {
        val s = schema(
            views = mapOf(
                "active_users" to ViewDefinition(
                    query = "SELECT * FROM users WHERE active = 1"
                )
            )
        )
        val result = generator.generate(s)
        val viewSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("VIEW") && !it.startsWith("--") }

        viewSql shouldStartWith "CREATE VIEW IF NOT EXISTS \"active_users\""
        viewSql shouldNotContain "OR REPLACE"
        viewSql shouldContain "SELECT * FROM users WHERE active = 1"
    }

    // ── 15. Materialized view becomes regular VIEW + W103 warning ───

    test("materialized view is created as regular VIEW with W103 warning") {
        val s = schema(
            views = mapOf(
                "stats_summary" to ViewDefinition(
                    query = "SELECT count(*) as cnt FROM events",
                    materialized = true
                )
            )
        )
        val result = generator.generate(s)
        val viewSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("VIEW") && !it.startsWith("--") }

        viewSql shouldStartWith "CREATE VIEW IF NOT EXISTS \"stats_summary\""
        viewSql shouldNotContain "MATERIALIZED"
        result.notes.any { it.code == "W103" && it.objectName == "stats_summary" } shouldBe true
    }

    // ── 16. Function is skipped with E052 ───────────────────────────

    test("function is skipped with E052 and added to skippedObjects") {
        val s = schema(
            functions = mapOf(
                "calculate_total" to FunctionDefinition(
                    body = "RETURN a + b;",
                    language = "sql"
                )
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "function" && it.name == "calculate_total" } shouldBe true
        result.notes.any { it.code == "E052" && it.objectName == "calculate_total" } shouldBe true
    }

    // ── 17. Procedure is skipped with E052 ──────────────────────────

    test("procedure is skipped with E052 and added to skippedObjects") {
        val s = schema(
            procedures = mapOf(
                "cleanup_old_data" to ProcedureDefinition(
                    body = "DELETE FROM logs WHERE created_at < date('now', '-30 days');",
                    language = "sql"
                )
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "procedure" && it.name == "cleanup_old_data" } shouldBe true
        result.notes.any { it.code == "E052" && it.objectName == "cleanup_old_data" } shouldBe true
    }

    // ── 18. Trigger with sqlite source_dialect produces CREATE TRIGGER

    test("trigger with sqlite source dialect produces CREATE TRIGGER with BEGIN...END") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "updated_at" to col(NeutralType.DateTime())
                    ),
                    primaryKey = listOf("id")
                )
            ),
            triggers = mapOf(
                "trg_users_updated" to TriggerDefinition(
                    table = "users",
                    event = TriggerEvent.UPDATE,
                    timing = TriggerTiming.AFTER,
                    forEach = TriggerForEach.ROW,
                    body = "    UPDATE users SET updated_at = datetime('now') WHERE id = NEW.id;",
                    sourceDialect = "sqlite"
                )
            )
        )
        val result = generator.generate(s)
        val triggerSql = result.statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE TRIGGER") }

        triggerSql shouldContain "CREATE TRIGGER \"trg_users_updated\""
        triggerSql shouldContain "AFTER UPDATE ON \"users\""
        triggerSql shouldContain "FOR EACH ROW"
        triggerSql shouldContain "BEGIN"
        triggerSql shouldContain "END;"
    }

    test("trigger with null source dialect produces CREATE TRIGGER") {
        val s = schema(
            tables = mapOf(
                "items" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                )
            ),
            triggers = mapOf(
                "trg_items_insert" to TriggerDefinition(
                    table = "items",
                    event = TriggerEvent.INSERT,
                    timing = TriggerTiming.BEFORE,
                    forEach = TriggerForEach.ROW,
                    condition = "NEW.id > 0",
                    body = "    SELECT RAISE(ABORT, 'invalid id');"
                )
            )
        )
        val result = generator.generate(s)
        val triggerSql = result.statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE TRIGGER") }

        triggerSql shouldContain "CREATE TRIGGER \"trg_items_insert\""
        triggerSql shouldContain "BEFORE INSERT ON \"items\""
        triggerSql shouldContain "WHEN NEW.id > 0"
        triggerSql shouldContain "BEGIN"
        triggerSql shouldContain "END;"
    }

    // ── 19. Trigger with different source_dialect is skipped with E052

    test("trigger with non-sqlite source dialect is skipped with E052") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                )
            ),
            triggers = mapOf(
                "trg_pg_notify" to TriggerDefinition(
                    table = "users",
                    event = TriggerEvent.INSERT,
                    timing = TriggerTiming.AFTER,
                    body = "PERFORM pg_notify('user_created', NEW.id::text);",
                    sourceDialect = "postgresql"
                )
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "trigger" && it.name == "trg_pg_notify" } shouldBe true
        result.notes.any { it.code == "E052" && it.objectName == "trg_pg_notify" } shouldBe true
    }

    // ── 20. Decimal type maps to REAL with W200 precision warning ───

    test("decimal column maps to REAL with W200 precision loss warning") {
        val s = schema(
            tables = mapOf(
                "invoices" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "amount" to col(NeutralType.Decimal(precision = 18, scale = 4), required = true)
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"amount\" REAL NOT NULL"
        result.notes.any {
            it.code == "W200" && it.objectName == "invoices.amount" && it.message.contains("Decimal(18,4)")
        } shouldBe true
    }

    // ── 21. Boolean default renders as 1 / 0 ────────────────────────

    test("boolean column with default true renders DEFAULT 1") {
        val s = schema(
            tables = mapOf(
                "settings" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "active" to col(
                            NeutralType.BooleanType,
                            required = true,
                            default = DefaultValue.BooleanLiteral(true)
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"active\" INTEGER NOT NULL DEFAULT 1"
    }

    test("boolean column with default false renders DEFAULT 0") {
        val s = schema(
            tables = mapOf(
                "settings" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "disabled" to col(
                            NeutralType.BooleanType,
                            required = true,
                            default = DefaultValue.BooleanLiteral(false)
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"disabled\" INTEGER NOT NULL DEFAULT 0"
    }

    // ── 22. Datetime default renders (datetime('now')) ───────────────

    test("datetime column with current_timestamp default renders datetime now") {
        val s = schema(
            tables = mapOf(
                "events" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "created_at" to col(
                            NeutralType.DateTime(),
                            required = true,
                            default = DefaultValue.FunctionCall("current_timestamp")
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "DEFAULT (datetime('now'))"
    }

    // ── 23. Rollback generates DROP statements ──────────────────────

    test("rollback generates DROP TABLE statement") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "name" to col(NeutralType.Text(), required = true)
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generateRollback(s)
        val dropSql = result.statements.map { it.sql.trim() }

        dropSql.any { it.startsWith("DROP TABLE IF EXISTS \"users\"") } shouldBe true
    }

    test("rollback generates DROP VIEW for IF NOT EXISTS views") {
        val s = schema(
            views = mapOf(
                "recent_events" to ViewDefinition(
                    query = "SELECT * FROM events ORDER BY created_at DESC LIMIT 100"
                )
            )
        )
        val result = generator.generateRollback(s)
        val dropSql = result.statements.map { it.sql.trim() }

        dropSql.any { it.startsWith("DROP VIEW IF EXISTS \"recent_events\"") } shouldBe true
    }

    test("rollback generates DROP INDEX for BTREE indices") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "email" to col(NeutralType.Email, required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_users_email",
                            columns = listOf("email"),
                            type = IndexType.BTREE
                        )
                    )
                )
            )
        )
        val result = generator.generateRollback(s)
        val dropSql = result.statements.map { it.sql.trim() }

        dropSql.any { it.startsWith("DROP INDEX IF EXISTS \"idx_users_email\"") } shouldBe true
    }

    test("rollback generates DROP TRIGGER for sqlite triggers") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                )
            ),
            triggers = mapOf(
                "trg_users_audit" to TriggerDefinition(
                    table = "users",
                    event = TriggerEvent.INSERT,
                    timing = TriggerTiming.AFTER,
                    body = "    INSERT INTO audit_log(action) VALUES ('insert');",
                    sourceDialect = "sqlite"
                )
            )
        )
        val result = generator.generateRollback(s)
        val dropSql = result.statements.map { it.sql.trim() }

        dropSql.any { it.startsWith("DROP TRIGGER IF EXISTS \"trg_users_audit\"") } shouldBe true
    }

    // ── 24. No table options (ENGINE, CHARSET) ──────────────────────

    test("generated DDL does not contain ENGINE or CHARSET table options") {
        val s = schema(
            tables = mapOf(
                "simple" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "value" to col(NeutralType.Text())
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val rendered = result.render()

        rendered shouldNotContain "ENGINE"
        rendered shouldNotContain "CHARSET"
        rendered shouldNotContain "COLLATE"
        rendered shouldNotContain "DEFAULT CHARSET"
    }

    // ── Additional edge-case tests ──────────────────────────────────

    test("dialect is SQLITE") {
        generator.dialect shouldBe DatabaseDialect.SQLITE
    }

    test("header contains schema name and target sqlite") {
        val s = schema()
        val result = generator.generate(s)
        val header = result.statements.first().sql

        header shouldContain "d-migrate"
        header shouldContain "test-schema"
        header shouldContain "sqlite"
    }

    test("enum with ref_type but no custom type definition still produces TEXT without CHECK") {
        val s = schema(
            tables = mapOf(
                "records" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "category" to col(
                            NeutralType.Enum(refType = "missing_type"),
                            required = true
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"category\" TEXT NOT NULL"
        sql shouldNotContain "CHECK"
    }

    test("inline foreign key with ON UPDATE action") {
        val s = schema(
            tables = mapOf(
                "parents" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                ),
                "children" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "parent_id" to col(
                            NeutralType.Integer,
                            references = ref(
                                "parents", "id",
                                onDelete = ReferentialAction.SET_NULL,
                                onUpdate = ReferentialAction.CASCADE
                            )
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val childrenSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("\"children\"") && it.startsWith("CREATE TABLE") }

        childrenSql shouldContain "REFERENCES \"parents\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE"
    }

    test("view with incompatible source dialect is skipped with E052") {
        val s = schema(
            views = mapOf(
                "pg_view" to ViewDefinition(
                    query = "SELECT * FROM pg_catalog.pg_tables",
                    sourceDialect = "postgresql"
                )
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "view" && it.name == "pg_view" } shouldBe true
        result.notes.any { it.code == "E052" && it.objectName == "pg_view" } shouldBe true
    }

    test("index without explicit name gets auto-generated name") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "name" to col(NeutralType.Text(), required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            columns = listOf("name"),
                            type = IndexType.BTREE
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val indexSql = result.statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE INDEX") }

        indexSql shouldContain "idx_users_name"
    }

    test("trigger with no body is skipped") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                )
            ),
            triggers = mapOf(
                "trg_empty" to TriggerDefinition(
                    table = "users",
                    event = TriggerEvent.INSERT,
                    timing = TriggerTiming.AFTER,
                    body = null
                )
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "trigger" && it.name == "trg_empty" } shouldBe true
        result.notes.any { it.code == "E052" && it.objectName == "trg_empty" } shouldBe true
    }

    test("view with no query is skipped") {
        val s = schema(
            views = mapOf(
                "empty_view" to ViewDefinition(query = null)
            )
        )
        val result = generator.generate(s)

        result.skippedObjects.any { it.type == "view" && it.name == "empty_view" } shouldBe true
    }

    test("domain custom type emits informational note") {
        val s = schema(
            customTypes = mapOf(
                "positive_int" to CustomTypeDefinition(
                    kind = CustomTypeKind.DOMAIN,
                    baseType = "integer",
                    check = "VALUE > 0"
                )
            )
        )
        val result = generator.generate(s)
        val notes = result.notes

        notes.any { it.code == "I001" && it.objectName == "positive_int" } shouldBe true
    }

    test("enum custom type emits informational note") {
        val s = schema(
            customTypes = mapOf(
                "status" to CustomTypeDefinition(
                    kind = CustomTypeKind.ENUM,
                    values = listOf("active", "inactive")
                )
            )
        )
        val result = generator.generate(s)
        val notes = result.notes

        notes.any { it.code == "I001" && it.objectName == "status" } shouldBe true
    }

    test("constraint FOREIGN_KEY clause generates correctly") {
        val s = schema(
            tables = mapOf(
                "departments" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                ),
                "employees" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "dept_id" to col(NeutralType.Integer, required = true)
                    ),
                    primaryKey = listOf("id"),
                    constraints = listOf(
                        ConstraintDefinition(
                            name = "fk_emp_dept",
                            type = ConstraintType.FOREIGN_KEY,
                            columns = listOf("dept_id"),
                            references = ConstraintReferenceDefinition(
                                table = "departments",
                                columns = listOf("id"),
                                onDelete = ReferentialAction.CASCADE
                            )
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val empSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("\"employees\"") && it.startsWith("CREATE TABLE") }

        empSql shouldContain "CONSTRAINT \"fk_emp_dept\" FOREIGN KEY (\"dept_id\") REFERENCES \"departments\" (\"id\") ON DELETE CASCADE"
    }

    test("constraint CHECK clause generates correctly") {
        val s = schema(
            tables = mapOf(
                "products" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "price" to col(NeutralType.Decimal(10, 2), required = true)
                    ),
                    primaryKey = listOf("id"),
                    constraints = listOf(
                        ConstraintDefinition(
                            name = "chk_positive_price",
                            type = ConstraintType.CHECK,
                            expression = "price > 0"
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "CONSTRAINT \"chk_positive_price\" CHECK (price > 0)"
    }

    test("constraint UNIQUE clause generates correctly") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "email" to col(NeutralType.Email, required = true),
                        "username" to col(NeutralType.Text(), required = true)
                    ),
                    primaryKey = listOf("id"),
                    constraints = listOf(
                        ConstraintDefinition(
                            name = "uq_email_username",
                            type = ConstraintType.UNIQUE,
                            columns = listOf("email", "username")
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "CONSTRAINT \"uq_email_username\" UNIQUE (\"email\", \"username\")"
    }

    test("constraint EXCLUDE is not supported and emits E052") {
        val s = schema(
            tables = mapOf(
                "reservations" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "room" to col(NeutralType.Integer, required = true)
                    ),
                    primaryKey = listOf("id"),
                    constraints = listOf(
                        ConstraintDefinition(
                            name = "excl_room_time",
                            type = ConstraintType.EXCLUDE,
                            expression = "room WITH ="
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)

        result.notes.any { it.code == "E052" && it.objectName == "excl_room_time" } shouldBe true
    }

    test("multiple tables with foreign key dependencies are topologically sorted") {
        val s = schema(
            tables = mapOf(
                "orders" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "customer_id" to col(
                            NeutralType.Integer,
                            required = true,
                            references = ref("customers", "id")
                        )
                    ),
                    primaryKey = listOf("id")
                ),
                "customers" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "name" to col(NeutralType.Text(), required = true)
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val createTables = result.statements
            .map { it.sql.trim() }
            .filter { it.startsWith("CREATE TABLE") }

        // customers should appear before orders because orders depends on customers
        val customersIdx = createTables.indexOfFirst { it.contains("\"customers\"") }
        val ordersIdx = createTables.indexOfFirst { it.contains("\"orders\"") }

        (customersIdx < ordersIdx) shouldBe true
    }

    test("rollback statements are in reverse order") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "name" to col(NeutralType.Text())
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_users_name",
                            columns = listOf("name"),
                            type = IndexType.BTREE
                        )
                    )
                )
            )
        )
        val result = generator.generateRollback(s)
        val dropStatements = result.statements.map { it.sql.trim() }

        // Index should be dropped before the table (reverse of create order)
        val dropIndexIdx = dropStatements.indexOfFirst { it.contains("DROP INDEX") }
        val dropTableIdx = dropStatements.indexOfFirst { it.contains("DROP TABLE") }

        (dropIndexIdx < dropTableIdx) shouldBe true
    }

    test("empty schema generates only header") {
        val s = schema()
        val result = generator.generate(s)

        result.statements shouldHaveSize 1
        result.statements.first().sql shouldContain "Generated by d-migrate"
        result.skippedObjects.shouldBeEmpty()
    }

    test("enum column with inline values and default value") {
        val s = schema(
            tables = mapOf(
                "tasks" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "priority" to col(
                            NeutralType.Enum(values = listOf("low", "medium", "high")),
                            required = true,
                            default = DefaultValue.StringLiteral("medium")
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"priority\" TEXT NOT NULL DEFAULT 'medium' CHECK (\"priority\" IN ('low', 'medium', 'high'))"
    }

    test("string default value with single quote is escaped") {
        val s = schema(
            tables = mapOf(
                "notes" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "content" to col(
                            NeutralType.Text(),
                            default = DefaultValue.StringLiteral("it's a test")
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "DEFAULT 'it''s a test'"
    }

    test("identifier column without autoIncrement still uses INTEGER PRIMARY KEY AUTOINCREMENT") {
        // NeutralType.Identifier defaults autoIncrement=false, but in the generator
        // the special path only fires when autoIncrement is true.
        val s = schema(
            tables = mapOf(
                "items" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = false)),
                        "name" to col(NeutralType.Text())
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        // With autoIncrement=false, it still maps to INTEGER PRIMARY KEY AUTOINCREMENT via typeMapper
        // but uses the default columnSql path since the special branch checks autoIncrement
        sql shouldContain "\"id\""
    }

    test("multiple indices on same table are all generated") {
        val s = schema(
            tables = mapOf(
                "users" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "email" to col(NeutralType.Email, required = true),
                        "name" to col(NeutralType.Text(), required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_users_email",
                            columns = listOf("email"),
                            type = IndexType.BTREE,
                            unique = true
                        ),
                        IndexDefinition(
                            name = "idx_users_name",
                            columns = listOf("name"),
                            type = IndexType.BTREE
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val indexStatements = result.statements
            .map { it.sql.trim() }
            .filter { it.startsWith("CREATE INDEX") || it.startsWith("CREATE UNIQUE INDEX") }

        indexStatements shouldHaveSize 2
    }

    test("multi-column BTREE index generates correct SQL") {
        val s = schema(
            tables = mapOf(
                "events" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "user_id" to col(NeutralType.Integer, required = true),
                        "created_at" to col(NeutralType.DateTime(), required = true)
                    ),
                    primaryKey = listOf("id"),
                    indices = listOf(
                        IndexDefinition(
                            name = "idx_events_user_date",
                            columns = listOf("user_id", "created_at"),
                            type = IndexType.BTREE
                        )
                    )
                )
            )
        )
        val result = generator.generate(s)
        val indexSql = result.statements
            .map { it.sql.trim() }
            .first { it.startsWith("CREATE INDEX") }

        indexSql shouldBe "CREATE INDEX \"idx_events_user_date\" ON \"events\" (\"user_id\", \"created_at\");"
    }

    test("enum with ref_type and inline reference generates REFERENCES clause") {
        val s = schema(
            customTypes = mapOf(
                "status_type" to CustomTypeDefinition(
                    kind = CustomTypeKind.ENUM,
                    values = listOf("active", "inactive")
                )
            ),
            tables = mapOf(
                "statuses" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                ),
                "accounts" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "status" to col(
                            NeutralType.Enum(refType = "status_type"),
                            required = true,
                            references = ref("statuses", "id", onDelete = ReferentialAction.RESTRICT)
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val accountsSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("\"accounts\"") && it.startsWith("CREATE TABLE") }

        accountsSql shouldContain "CHECK (\"status\" IN ('active', 'inactive'))"
        accountsSql shouldContain "REFERENCES \"statuses\"(\"id\") ON DELETE RESTRICT"
    }

    test("enum with inline values and reference generates both CHECK and REFERENCES") {
        val s = schema(
            tables = mapOf(
                "lookup" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true))
                    ),
                    primaryKey = listOf("id")
                ),
                "records" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "kind" to col(
                            NeutralType.Enum(values = listOf("a", "b", "c")),
                            required = true,
                            references = ref("lookup", "id", onDelete = ReferentialAction.NO_ACTION)
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val recordsSql = result.statements
            .map { it.sql.trim() }
            .first { it.contains("\"records\"") && it.startsWith("CREATE TABLE") }

        recordsSql shouldContain "CHECK (\"kind\" IN ('a', 'b', 'c'))"
        recordsSql shouldContain "REFERENCES \"lookup\"(\"id\") ON DELETE NO ACTION"
    }

    test("number literal default renders correctly") {
        val s = schema(
            tables = mapOf(
                "counters" to table(
                    columns = mapOf(
                        "id" to col(NeutralType.Identifier(autoIncrement = true)),
                        "count" to col(
                            NeutralType.Integer,
                            required = true,
                            default = DefaultValue.NumberLiteral(42)
                        )
                    ),
                    primaryKey = listOf("id")
                )
            )
        )
        val result = generator.generate(s)
        val sql = result.tableSql()

        sql shouldContain "\"count\" INTEGER NOT NULL DEFAULT 42"
    }
})
