package dev.dmigrate.integration

import dev.dmigrate.migration.ArtifactRelativePath
import dev.dmigrate.migration.MigrationArtifact
import dev.dmigrate.migration.MigrationBundle
import dev.dmigrate.migration.MigrationDdlPayload
import dev.dmigrate.migration.MigrationRollback
import dev.dmigrate.migration.MigrationTool
import dev.dmigrate.migration.ToolExportResult
import dev.dmigrate.migration.ToolMigrationExporter

/**
 * Renders a Knex.js CommonJS migration from a [MigrationBundle].
 *
 * Produces exactly one JavaScript file:
 * - `<version>.js`
 *
 * Uses `exports.up` / `exports.down` with sequential `knex.raw()`
 * calls from `MigrationDdlPayload.result.statements`.
 */
class KnexMigrationExporter : ToolMigrationExporter {

    override val tool = MigrationTool.KNEX

    override fun render(bundle: MigrationBundle): ToolExportResult {
        val identity = bundle.identity
        val fileName = "${identity.version}.js"

        val js = buildString {
            appendLine("/**")
            appendLine(" * Migration: ${identity.version} ${identity.slug}")
            appendLine(" * Target: ${identity.dialect.name.lowercase()}")
            appendLine(" * Generated by d-migrate")
            appendLine(" */")
            appendLine()
            appendLine("exports.up = async function(knex) {")
            appendRawCalls(bundle.up)
            appendLine("};")

            when (val rollback = bundle.rollback) {
                is MigrationRollback.NotRequested -> {}
                is MigrationRollback.Requested -> {
                    appendLine()
                    appendLine("exports.down = async function(knex) {")
                    appendRawCalls(rollback.down)
                    appendLine("};")
                }
            }
        }

        return ToolExportResult(
            artifacts = listOf(
                MigrationArtifact(
                    relativePath = ArtifactRelativePath.of(fileName),
                    kind = "migration",
                    content = js,
                )
            ),
        )
    }

    internal companion object {
        private val COMMENT_ONLY = Regex("^(\\s*--[^\n]*\n?)*$")

        fun StringBuilder.appendRawCalls(payload: MigrationDdlPayload) {
            for (statement in payload.result.statements) {
                if (statement.sql.isBlank()) continue
                if (COMMENT_ONLY.matches(statement.sql)) continue
                val escaped = RenderHelpers.escapeJavaScript(statement.sql)
                appendLine("    await knex.raw(`$escaped`);")
            }
        }
    }
}
