package dev.dmigrate.driver.oracle

import dev.dmigrate.core.data.ColumnDescriptor
import dev.dmigrate.driver.data.SequenceAdjustment
import dev.dmigrate.driver.metadata.JdbcOperations
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.shouldBe
import io.mockk.every
import io.mockk.mockk
import io.mockk.verify
import java.sql.Connection

class OracleSchemaSyncTest : FunSpec({

    fun rig(
        identityColumn: String? = "id",
        generation: String = "ALWAYS",
        sequenceName: String = "ISEQ\$\$_1",
        increment: Long = 1L,
        maxValue: Long? = 42L,
        limitValueLastNumber: Long = 1L,
    ): Pair<OracleSchemaSync, JdbcOperations> {
        val jdbc = mockk<JdbcOperations>(relaxed = true)
        every { jdbc.querySingle(match { it.contains("CURRENT_SCHEMA") }) } returns mapOf("schema_name" to "APP")
        every { jdbc.queryList(match { it.contains("all_tab_identity_cols") }, any(), any()) } returns
            identityColumn?.let {
                listOf(
                    mapOf<String, Any?>(
                        "column_name" to it, "generation_type" to generation,
                        "sequence_name" to sequenceName, "increment_by" to increment,
                    ),
                )
            }.orEmpty()
        every { jdbc.querySingle(match { it.contains("MAX(") }) } returns
            maxValue?.let { mapOf("max_value" to it) } ?: mapOf("max_value" to null)
        every { jdbc.querySingle(match { it.contains("all_sequences") }, any(), any()) } returns
            mapOf("last_number" to limitValueLastNumber)
        return OracleSchemaSync { jdbc } to jdbc
    }

    fun column(name: String) = ColumnDescriptor(name = name, nullable = false)

    test("reseeds via ALTER TABLE MODIFY ... (START WITH n): ALTER SEQUENCE is blocked for system-generated sequences") {
        val (sync, jdbc) = rig()
        val adjustments = sync.reseedGenerators(
            conn = mockk<Connection>(), table = "orders",
            importedColumns = listOf(column("id"), column("name")), truncatePerformed = false,
        )
        adjustments shouldBe listOf(SequenceAdjustment("orders", "id", "ISEQ\$\$_1", 43L))
        verify {
            jdbc.execute(
                "ALTER TABLE \"APP\".\"orders\" MODIFY \"id\" GENERATED ALWAYS AS IDENTITY (START WITH 43)",
            )
        }
    }

    test("increment comes from the catalog, not assumed as 1") {
        val (sync, jdbc) = rig(maxValue = 100L, increment = 10L)
        sync.reseedGenerators(mockk<Connection>(), "orders", listOf(column("id")), false) shouldBe
            listOf(SequenceAdjustment("orders", "id", "ISEQ\$\$_1", 110L))
        verify {
            jdbc.execute(
                "ALTER TABLE \"APP\".\"orders\" MODIFY \"id\" GENERATED ALWAYS AS IDENTITY (START WITH 110)",
            )
        }
    }

    test("a currently BY DEFAULT column (mid-toggle) reseeds with BY DEFAULT, not an assumed ALWAYS") {
        val (sync, jdbc) = rig(generation = "BY DEFAULT")
        sync.reseedGenerators(mockk<Connection>(), "orders", listOf(column("id")), false)
        verify {
            jdbc.execute(
                "ALTER TABLE \"APP\".\"orders\" MODIFY \"id\" GENERATED BY DEFAULT AS IDENTITY (START WITH 43)",
            )
        }
    }

    test("no identity column means no adjustment") {
        val (sync, _) = rig(identityColumn = null)
        sync.reseedGenerators(mockk<Connection>(), "orders", listOf(column("id")), false).shouldBeEmpty()
    }

    test("identity column not imported and no truncate is a no-op") {
        val (sync, _) = rig()
        sync.reseedGenerators(mockk<Connection>(), "orders", listOf(column("name")), false).shouldBeEmpty()
    }

    test("empty table after truncate uses START WITH LIMIT VALUE and reports the catalog readback") {
        val (sync, jdbc) = rig(maxValue = null, limitValueLastNumber = 1000L)
        val adjustments = sync.reseedGenerators(mockk<Connection>(), "orders", emptyList(), truncatePerformed = true)
        adjustments shouldBe listOf(SequenceAdjustment("orders", "id", "ISEQ\$\$_1", 1000L))
        verify {
            jdbc.execute(
                "ALTER TABLE \"APP\".\"orders\" MODIFY \"id\" GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE)",
            )
        }
    }

    test("no rows and no truncate leaves the identity untouched") {
        val (sync, jdbc) = rig(maxValue = null)
        sync.reseedGenerators(mockk<Connection>(), "orders", listOf(column("id")), truncatePerformed = false)
            .shouldBeEmpty()
        verify(exactly = 0) { jdbc.execute(match { it.contains("ALTER TABLE") && it.contains("IDENTITY") }) }
    }
})
