package dev.dmigrate.driver.oracle

import dev.dmigrate.core.diff.ColumnDiff
import dev.dmigrate.core.diff.SchemaDiff
import dev.dmigrate.core.diff.TableDiff
import dev.dmigrate.core.diff.ValueChange
import dev.dmigrate.core.diff.migration.DiffPlanner
import dev.dmigrate.core.diff.migration.RenameProjectionCapabilities
import dev.dmigrate.core.diff.migration.RenameProjectionDialect
import dev.dmigrate.core.diff.migration.overlay.MigrationOverlay
import dev.dmigrate.core.diff.migration.overlay.MigrationOverlayDocument
import dev.dmigrate.core.diff.migration.overlay.MigrationOverlayKinds
import dev.dmigrate.core.diff.migration.overlay.RenameMappingOverlayEntry
import dev.dmigrate.core.model.ColumnDefinition
import dev.dmigrate.core.model.ColumnGeneration
import dev.dmigrate.core.model.ConstraintDefinition
import dev.dmigrate.core.model.ConstraintReferenceDefinition
import dev.dmigrate.core.model.ConstraintType
import dev.dmigrate.core.model.DefaultValue
import dev.dmigrate.core.model.IdentityMode
import dev.dmigrate.core.model.IndexColumn
import dev.dmigrate.core.model.IndexDefinition
import dev.dmigrate.core.model.NeutralType
import dev.dmigrate.core.model.PartitionConfig
import dev.dmigrate.core.model.PartitionType
import dev.dmigrate.core.model.SchemaDefinition
import dev.dmigrate.core.model.TableDefinition
import dev.dmigrate.driver.DdlGenerationOptions
import io.kotest.assertions.withClue
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldContain
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.ints.shouldBeGreaterThan
import io.kotest.matchers.ints.shouldBeLessThanOrEqual
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldEndWith
import dev.dmigrate.core.diff.migration.overlay.MigrationOverlayBinding

/**
 * Der Tabellen-Neubau, mit dem Oracle eine bestehende Spalte doch noch zur
 * Identity-Spalte bekommt.
 *
 * Gepruefte Zusicherungen: die Kopie behaelt die vorhandenen Schluessel, der
 * Zaehler steht danach ueber dem groessten davon, alles was an der Tabelle
 * haengt kommt genau einmal zurueck — und die Faelle, in denen der Neubau
 * lieber blockt als zu raten.
 */
class OracleRebuildTest : FunSpec({

    val gen = OracleDiffDdlGenerator()
    val planner = DiffPlanner()

    fun idColumn(identity: Boolean, mode: IdentityMode = IdentityMode.ALWAYS) = ColumnDefinition(
        type = if (identity) NeutralType.Identifier(autoIncrement = true) else NeutralType.BigInteger,
        generation = if (identity) ColumnGeneration.Identity(mode = mode) else null,
        ordinal = 1,
    )

    val identityChange = ColumnDiff(
        name = "id",
        type = ValueChange(NeutralType.BigInteger, NeutralType.Identifier(autoIncrement = true)),
    )

    fun users(
        identity: Boolean,
        mode: IdentityMode = IdentityMode.ALWAYS,
        extraColumns: Map<String, ColumnDefinition> = emptyMap(),
        indices: List<IndexDefinition> = emptyList(),
        partitioning: PartitionConfig? = null,
    ) = TableDefinition(
        columns = linkedMapOf("id" to idColumn(identity, mode)) + extraColumns,
        primaryKey = listOf("id"),
        indices = indices,
        partitioning = partitioning,
    )

    fun schemaOf(vararg tables: Pair<String, TableDefinition>) =
        SchemaDefinition(name = "App", version = "1", tables = linkedMapOf(*tables))

    fun plan(
        diff: SchemaDiff,
        current: SchemaDefinition,
        desired: SchemaDefinition,
        overlays: List<MigrationOverlayDocument> = emptyList(),
    ) = planner.plan(
        current, desired, diff, overlays,
        capabilities = RenameProjectionCapabilities.fileOnly(RenameProjectionDialect.ORACLE),
    )

    fun renderUp(
        diff: SchemaDiff,
        current: SchemaDefinition,
        desired: SchemaDefinition,
        options: DdlGenerationOptions = DdlGenerationOptions(),
        overlays: List<MigrationOverlayDocument> = emptyList(),
    ) = gen.generateUp(plan(diff, current, desired, overlays), options)

    val plainDiff = SchemaDiff(tablesChanged = listOf(TableDiff("users", columnsChanged = listOf(identityChange))))

    test("the copy runs against a BY DEFAULT column so the existing keys survive") {
        // GENERATED ALWAYS lehnt den eingefuegten Schluessel mit ORA-32795 ab;
        // der Neubau vergaebe dann neue. Die Zwischentabelle nimmt ihn deshalb
        // an, und erst der Reseed setzt den Zielmodus.
        val result = renderUp(plainDiff, schemaOf("users" to users(false)), schemaOf("users" to users(true)))
        val sqls = result.statements.map { it.sql }

        sqls[0] shouldContain "GENERATED BY DEFAULT AS IDENTITY"
        sqls[1] shouldContain "SELECT \"id\" FROM \"users\""
        sqls.last { it.contains("MODIFY") } shouldContain "GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE)"
    }

    test("a BY DEFAULT target keeps its mode in the reseed") {
        val result = renderUp(
            plainDiff,
            schemaOf("users" to users(false)),
            schemaOf("users" to users(true, mode = IdentityMode.BY_DEFAULT)),
        )
        result.statements.map { it.sql }.last { it.contains("MODIFY") } shouldContain
            "GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)"
    }

    test("the temp table name is stable for the same input and fits Oracle's 128 characters") {
        val ops = plan(plainDiff, schemaOf("users" to users(false)), schemaOf("users" to users(true))).operations
        val long = "t".repeat(200)

        OracleRebuildPlanner.tempTableName(long, ops) shouldBe OracleRebuildPlanner.tempTableName(long, ops)
        OracleRebuildPlanner.tempTableName(long, ops).length shouldBeLessThanOrEqual 128
        // Gekuerzt wird der Tabellenteil, nicht der unterscheidende Hash.
        OracleRebuildPlanner.tempTableName(long, ops) shouldNotBe
            OracleRebuildPlanner.tempTableName(long, emptyList())
    }

    test("an index on the rebuilt table comes back exactly once") {
        // Einzeln gerendert liefe das CREATE INDEX gegen ORA-00955: der Neubau
        // hat den Index schon angelegt.
        val index = IndexDefinition(name = "ix_users_email", columns = listOf(IndexColumn("email")))
        val email = mapOf("email" to ColumnDefinition(NeutralType.Text(maxLength = 100), ordinal = 2))
        val diff = SchemaDiff(
            tablesChanged = listOf(
                TableDiff("users", columnsChanged = listOf(identityChange), indicesAdded = listOf(index)),
            ),
        )
        val result = renderUp(
            diff,
            schemaOf("users" to users(false, extraColumns = email)),
            schemaOf("users" to users(true, extraColumns = email, indices = listOf(index))),
        )

        result.statements.map { it.sql }.filter { it.contains("ix_users_email") } shouldHaveSize 1
        result.operationsSkipped.shouldBeEmpty()
    }

    test("a column added alongside the identity change is filled from its default") {
        // Die Zwischentabelle traegt keinen Default -- der Wert muss im SELECT
        // stehen, sonst kaeme die neue Spalte leer heraus.
        val note = mapOf(
            "note" to ColumnDefinition(
                NeutralType.Text(maxLength = 20), default = DefaultValue.StringLiteral("n/a"), ordinal = 2,
            ),
        )
        val diff = SchemaDiff(
            tablesChanged = listOf(
                TableDiff("users", columnsChanged = listOf(identityChange), columnsAdded = note),
            ),
        )
        val result = renderUp(
            diff, schemaOf("users" to users(false)), schemaOf("users" to users(true, extraColumns = note)),
        )

        result.statements.map { it.sql }.first { it.startsWith("INSERT INTO") } shouldContain
            "SELECT \"id\", 'n/a' FROM \"users\""
    }

    test("a renamed column is read from its old name") {
        val old = mapOf("mail" to ColumnDefinition(NeutralType.Text(maxLength = 100), ordinal = 2))
        val new = mapOf("email" to ColumnDefinition(NeutralType.Text(maxLength = 100), ordinal = 2))
        val diff = SchemaDiff(
            tablesChanged = listOf(
                TableDiff(
                    "users",
                    columnsChanged = listOf(identityChange),
                    columnsAdded = new,
                    columnsRemoved = old,
                ),
            ),
        )
        val overlay = MigrationOverlayDocument(
            source = "ovl/rename.json",
            overlay = MigrationOverlay(
                overlayKind = MigrationOverlayKinds.RENAME_MAPPING,
                binding = MigrationOverlayBinding.Transition("src-fp", "dst-fp"),
                dialect = "oracle",
                entries = listOf(
                    RenameMappingOverlayEntry(
                        id = "rename-column-mail",
                        objectType = "column",
                        fromName = "users.mail",
                        toName = "users.email",
                    ),
                ),
                createdAt = "2026-09-08T08:00:00Z",
                createdByVersion = "d-migrate-test",
            ).withComputedHash(),
        )
        val result = renderUp(
            diff,
            schemaOf("users" to users(false, extraColumns = old)),
            schemaOf("users" to users(true, extraColumns = new)),
            overlays = listOf(overlay),
        )
        val insert = result.statements.map { it.sql }.first { it.startsWith("INSERT INTO") }

        // Die Umbenennung geht im Neubau auf; die Kopie muss ihr folgen, sonst
        // faende sie die Quellspalte nicht und die Werte gingen verloren.
        withClue(insert) {
            insert shouldContain "(\"id\", \"email\")"
            insert shouldContain "SELECT \"id\", \"mail\" FROM \"users\""
        }
    }

    test("an inbound foreign key is put back after the rename") {
        // DROP TABLE ... CASCADE CONSTRAINTS raeumt ihn mit ab; ohne das
        // Wiederanlegen verschwaende er still.
        val orders = TableDefinition(
            columns = linkedMapOf("user_id" to ColumnDefinition(NeutralType.BigInteger, ordinal = 1)),
            constraints = listOf(
                ConstraintDefinition(
                    name = "fk_orders_user",
                    type = ConstraintType.FOREIGN_KEY,
                    columns = listOf("user_id"),
                    references = ConstraintReferenceDefinition(table = "users", columns = listOf("id")),
                ),
            ),
        )
        val result = renderUp(
            plainDiff,
            schemaOf("users" to users(false), "orders" to orders),
            schemaOf("users" to users(true), "orders" to orders),
        )
        val sqls = result.statements.map { it.sql }

        sqls.any { it.contains("\"orders\"") && it.contains("fk_orders_user") } shouldBe true
        sqls.indexOfFirst { it.contains("fk_orders_user") } shouldBeGreaterThan
            sqls.indexOfFirst { it.contains("RENAME TO") }
    }

    test("a child table created in the same migration is left to its own CREATE TABLE") {
        // Sein Fremdschluessel wurde nie abgeraeumt, und die Tabelle gibt es
        // zum Zeitpunkt des Neubaus noch nicht.
        val orders = TableDefinition(
            columns = linkedMapOf("user_id" to ColumnDefinition(NeutralType.BigInteger, ordinal = 1)),
            constraints = listOf(
                ConstraintDefinition(
                    name = "fk_orders_user",
                    type = ConstraintType.FOREIGN_KEY,
                    columns = listOf("user_id"),
                    references = ConstraintReferenceDefinition(table = "users", columns = listOf("id")),
                ),
            ),
        )
        OracleRebuildPlanner.inboundForeignKeys(
            targetSchema = schemaOf("users" to users(true), "orders" to orders),
            sourceSchema = schemaOf("users" to users(false)),
            table = "users",
        ).shouldBeEmpty()
    }

    test("a partitioning change blocks instead of silently dropping the partitions") {
        val partitions = PartitionConfig(type = PartitionType.RANGE, key = listOf("id"))
        val diff = SchemaDiff(
            tablesChanged = listOf(
                TableDiff(
                    "users",
                    columnsChanged = listOf(identityChange),
                    partitioning = ValueChange(null, partitions),
                ),
            ),
        )
        val result = renderUp(
            diff,
            schemaOf("users" to users(false)),
            schemaOf("users" to users(true, partitioning = partitions)),
        )

        result.statements.shouldBeEmpty()
        result.diagnostics.map { it.code } shouldContain "DIALECT_UNSUPPORTED_OPERATION"
    }

    test("--strict-gap-operations blocks the rebuild, which is a gap by construction") {
        val result = renderUp(
            plainDiff,
            schemaOf("users" to users(false)),
            schemaOf("users" to users(true)),
            DdlGenerationOptions(strictGapOperations = true),
        )

        result.statements.shouldBeEmpty()
        result.diagnostics.map { it.code } shouldContain "OPERATION_HAS_GAP_STRICT_BLOCKED"
    }

    test("every statement of the rebuild carries the whole bucket, not just the trigger") {
        // Sonst faellt alles, was der Neubau miterledigt, aus der Buchhaltung
        // und der Runner meldete es als nicht gerendert.
        val index = IndexDefinition(name = "ix_users_email", columns = listOf(IndexColumn("email")))
        val email = mapOf("email" to ColumnDefinition(NeutralType.Text(maxLength = 100), ordinal = 2))
        val diff = SchemaDiff(
            tablesChanged = listOf(
                TableDiff("users", columnsChanged = listOf(identityChange), indicesAdded = listOf(index)),
            ),
        )
        val planned = plan(
            diff,
            schemaOf("users" to users(false, extraColumns = email)),
            schemaOf("users" to users(true, extraColumns = email, indices = listOf(index))),
        )
        val result = gen.generateUp(planned, DdlGenerationOptions())

        result.operationsRendered shouldBe planned.operations.map { it.id }.toSet()
        result.statements.forEach { it.operationIds shouldBe result.operationsRendered }
        result.requiresConfirmation shouldBe true
    }

    test("the temp table is dropped by the rebuild itself — no name survives the run") {
        val result = renderUp(plainDiff, schemaOf("users" to users(false)), schemaOf("users" to users(true)))
        val sqls = result.statements.map { it.sql }

        // Die Zwischentabelle wird umbenannt, nicht geloescht: nach dem
        // RENAME traegt sie den Zielnamen, und ihr Zwischenname existiert
        // nicht mehr.
        val temp = OracleRebuildPlanner.tempTableName(
            "users",
            plan(plainDiff, schemaOf("users" to users(false)), schemaOf("users" to users(true))).operations,
        )
        sqls.first() shouldContain temp
        sqls.first { it.startsWith("ALTER TABLE") && it.contains("RENAME TO") } shouldEndWith
            "RENAME TO \"users\";"
        sqls.drop(sqls.indexOfFirst { it.contains("RENAME TO") } + 1).none { it.contains(temp) } shouldBe true
    }
})
