package dev.dmigrate.driver.oracle

import dev.dmigrate.core.diff.ColumnDiff
import dev.dmigrate.core.diff.SchemaDiff
import dev.dmigrate.core.diff.TableDiff
import dev.dmigrate.core.diff.ValueChange
import dev.dmigrate.core.diff.migration.DiffPlanner
import dev.dmigrate.core.model.ColumnDefinition
import dev.dmigrate.core.model.ColumnGeneration
import dev.dmigrate.core.model.IdentityMode
import dev.dmigrate.core.model.NeutralType
import dev.dmigrate.core.model.SchemaDefinition
import dev.dmigrate.core.model.TableDefinition
import dev.dmigrate.driver.DdlGenerationOptions
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain

/**
 * Die Uebergaenge einer `AlterColumnGeneration`, die **kein** Ausdruckswechsel
 * sind — auf Oracle, live gegen 23 gemessen:
 *
 * | Uebergang | Oracle |
 * | --- | --- |
 * | berechnet → gewoehnlich | `MODIFY (c <typ>)`; der Wert wird **materialisiert**, nicht verworfen |
 * | Identity-Modus | `MODIFY (c GENERATED … AS IDENTITY)` |
 * | Identity → gewoehnlich | `MODIFY (c DROP IDENTITY)`; Werte bleiben, Sequenz verschwindet |
 * | gewoehnlich → Identity | `ORA-30673` |
 * | gewoehnlich → berechnet | `ORA-54026` |
 */
class OracleDiffGenerationTransitionTest : FunSpec({

    val gen = OracleDiffDdlGenerator()
    val planner = DiffPlanner()

    fun schema(generation: ColumnGeneration?) = SchemaDefinition(
        name = "App",
        version = "1",
        tables = mapOf(
            "order_line" to TableDefinition(
                columns = linkedMapOf(
                    "id" to ColumnDefinition(NeutralType.Integer, required = true),
                    "line_total" to ColumnDefinition(NeutralType.Integer, generation = generation),
                ),
                primaryKey = listOf("id"),
            ),
        ),
    )

    fun requiredSchema(generation: ColumnGeneration?) = SchemaDefinition(
        name = "App",
        version = "1",
        tables = mapOf(
            "order_line" to TableDefinition(
                columns = linkedMapOf(
                    "id" to ColumnDefinition(NeutralType.Integer, required = true),
                    "line_total" to ColumnDefinition(
                        NeutralType.Integer,
                        required = true,
                        generation = generation,
                    ),
                ),
                primaryKey = listOf("id"),
            ),
        ),
    )

    fun renderGenerationChange(before: ColumnGeneration?, after: ColumnGeneration?) = gen.generateUp(
        planner.plan(
            schema(before),
            schema(after),
            SchemaDiff(
                tablesChanged = listOf(
                    TableDiff(
                        name = "order_line",
                        columnsChanged = listOf(
                            ColumnDiff(name = "line_total", generation = ValueChange(before, after)),
                        ),
                    ),
                ),
            ),
        ),
        DdlGenerationOptions(),
    )

    val virtual = ColumnGeneration.Computed("\"qty\" * \"price\"", stored = false)

    /**
     * `column-generation-diff-unmapped.md`: `MODIFY (c <typ>)` nimmt Oracle
     * zwar an, aendert aber nichts (die Zeile, die die urspruengliche Zusage
     * widerlegt hat — live durch den vollen Migrationspfad gemessen). Der
     * Spaltentausch umgeht das: eine Zwischenspalte kopiert den
     * eingefrorenen Wert, bevor die berechnete Spalte weicht.
     */
    test("a computed column becomes ordinary via swap: add temp, copy, drop, rename, reassert") {
        val result = renderGenerationChange(virtual, null)
        val sqls = result.statements.map { it.sql }
        sqls.size shouldBe 5
        sqls[0] shouldContain "ADD (\"line_total__dmg_swap\""
        sqls[1] shouldBe "UPDATE \"order_line\" SET \"line_total__dmg_swap\" = \"line_total\";"
        sqls[2] shouldContain "DROP COLUMN \"line_total\""
        sqls[3] shouldBe "ALTER TABLE \"order_line\" RENAME COLUMN \"line_total__dmg_swap\" TO \"line_total\";"
        sqls[4] shouldContain "MODIFY (\"line_total\""
        sqls[4] shouldNotContain "GENERATED"
        result.destructiveOperations.size shouldBe 1
    }

    test("the identity mode is switched in place") {
        val result = renderGenerationChange(
            ColumnGeneration.Identity(IdentityMode.ALWAYS),
            ColumnGeneration.Identity(IdentityMode.BY_DEFAULT),
        )
        result.statements.single().sql shouldContain "MODIFY \"line_total\" GENERATED BY DEFAULT AS IDENTITY"
    }

    test("identity is dropped in place, and the values stay") {
        val result = renderGenerationChange(ColumnGeneration.Identity(IdentityMode.ALWAYS), null)
        result.statements.single().sql shouldContain "MODIFY \"line_total\" DROP IDENTITY"
    }

    /**
     * Oracle nimmt der Spalte mit der Identity auch ihr implizites `NOT NULL`
     * (live gemessen: `required` kippte auf false und der Post-Compare meldete
     * Drift). Verlangt das Soll sie weiter als Pflichtfeld, zieht der Renderer
     * den Zwang mit einer zweiten Anweisung nach.
     */
    test("a required column keeps its NOT NULL when the identity goes") {
        val result = gen.generateUp(
            planner.plan(
                requiredSchema(ColumnGeneration.Identity(IdentityMode.ALWAYS)),
                requiredSchema(null),
                SchemaDiff(
                    tablesChanged = listOf(
                        TableDiff(
                            name = "order_line",
                            columnsChanged = listOf(
                                ColumnDiff(
                                    name = "line_total",
                                    generation = ValueChange(ColumnGeneration.Identity(IdentityMode.ALWAYS), null),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
            DdlGenerationOptions(),
        )
        val sql = result.statements.map { it.sql }
        sql.size shouldBe 2
        sql[0] shouldContain "DROP IDENTITY"
        sql[1] shouldContain "NOT NULL"
    }

    test("making an ordinary column an identity one is refused with ORA-30673") {
        val result = renderGenerationChange(null, ColumnGeneration.Identity(IdentityMode.BY_DEFAULT))
        result.statements.shouldBeEmpty()
        val message = result.diagnostics.single().message
        message shouldContain "would make"
        message shouldContain "ORA-30673"
    }

    test("an ordinary column becomes computed via DROP + ADD, no data copy") {
        val result = renderGenerationChange(null, virtual)
        val sqls = result.statements.map { it.sql }
        sqls.size shouldBe 2
        sqls[0] shouldContain "DROP COLUMN \"line_total\""
        sqls[1] shouldContain "ADD (\"line_total\""
        sqls[1] shouldContain "GENERATED ALWAYS AS"
        result.destructiveOperations.size shouldBe 1
    }

    test("an encumbered column (part of the primary key) blocks the swap with a precise reason") {
        fun schemaWithIdGeneration(generation: ColumnGeneration?) = SchemaDefinition(
            name = "App",
            version = "1",
            tables = mapOf(
                "order_line" to TableDefinition(
                    columns = linkedMapOf(
                        "id" to ColumnDefinition(NeutralType.Integer, required = true, generation = generation),
                        "qty" to ColumnDefinition(NeutralType.Integer, required = true),
                    ),
                    primaryKey = listOf("id"),
                ),
            ),
        )
        val result = gen.generateUp(
            planner.plan(
                schemaWithIdGeneration(null),
                schemaWithIdGeneration(virtual),
                SchemaDiff(
                    tablesChanged = listOf(
                        TableDiff(
                            name = "order_line",
                            columnsChanged = listOf(ColumnDiff(name = "id", generation = ValueChange(null, virtual))),
                        ),
                    ),
                ),
            ),
            DdlGenerationOptions(),
        )
        result.statements.shouldBeEmpty()
        result.diagnostics.single().message shouldContain "part of the primary key"
    }

    test("swapping identity for a computation is refused, not reported as an expression change") {
        val result = renderGenerationChange(ColumnGeneration.Identity(IdentityMode.ALWAYS), virtual)
        result.statements.shouldBeEmpty()
        val message = result.diagnostics.single().message
        message shouldContain "swaps identity and computation"
        message shouldNotContain "would drop the computed expression"
    }
})
