package dev.dmigrate.driver.oracle

import dev.dmigrate.core.diff.ColumnDiff
import dev.dmigrate.core.diff.SchemaDiff
import dev.dmigrate.core.diff.TableDiff
import dev.dmigrate.core.diff.ValueChange
import dev.dmigrate.core.diff.migration.DiffPlanner
import dev.dmigrate.core.model.ColumnDefinition
import dev.dmigrate.core.model.ColumnGeneration
import dev.dmigrate.core.model.IdentityMode
import dev.dmigrate.core.model.NeutralType
import dev.dmigrate.core.model.SchemaDefinition
import dev.dmigrate.core.model.TableDefinition
import dev.dmigrate.driver.DdlGenerationOptions
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain

/**
 * Die Uebergaenge einer `AlterColumnGeneration`, die **kein** Ausdruckswechsel
 * sind — auf Oracle, live gegen 23 gemessen:
 *
 * | Uebergang | Oracle |
 * | --- | --- |
 * | berechnet → gewoehnlich | `MODIFY (c <typ>)`; der Wert wird **materialisiert**, nicht verworfen |
 * | Identity-Modus | `MODIFY (c GENERATED … AS IDENTITY)` |
 * | Identity → gewoehnlich | `MODIFY (c DROP IDENTITY)`; Werte bleiben, Sequenz verschwindet |
 * | gewoehnlich → Identity | `ORA-30673` |
 * | gewoehnlich → berechnet | `ORA-54026` |
 */
class OracleDiffGenerationTransitionTest : FunSpec({

    val gen = OracleDiffDdlGenerator()
    val planner = DiffPlanner()

    fun schema(generation: ColumnGeneration?) = SchemaDefinition(
        name = "App",
        version = "1",
        tables = mapOf(
            "order_line" to TableDefinition(
                columns = linkedMapOf(
                    "id" to ColumnDefinition(NeutralType.Integer, required = true),
                    "line_total" to ColumnDefinition(NeutralType.Integer, generation = generation),
                ),
                primaryKey = listOf("id"),
            ),
        ),
    )

    fun requiredSchema(generation: ColumnGeneration?) = SchemaDefinition(
        name = "App",
        version = "1",
        tables = mapOf(
            "order_line" to TableDefinition(
                columns = linkedMapOf(
                    "id" to ColumnDefinition(NeutralType.Integer, required = true),
                    "line_total" to ColumnDefinition(
                        NeutralType.Integer,
                        required = true,
                        generation = generation,
                    ),
                ),
                primaryKey = listOf("id"),
            ),
        ),
    )

    fun renderGenerationChange(before: ColumnGeneration?, after: ColumnGeneration?) = gen.generateUp(
        planner.plan(
            schema(before),
            schema(after),
            SchemaDiff(
                tablesChanged = listOf(
                    TableDiff(
                        name = "order_line",
                        columnsChanged = listOf(
                            ColumnDiff(name = "line_total", generation = ValueChange(before, after)),
                        ),
                    ),
                ),
            ),
        ),
        DdlGenerationOptions(),
    )

    val virtual = ColumnGeneration.Computed("\"qty\" * \"price\"", stored = false)

    /**
     * Die Zeile, die eine frueher hier stehende Zusage widerlegt hat: Oracle
     * **nimmt** `MODIFY (c <typ>)` auf einer virtuellen Spalte an — und aendert
     * nichts. Durch den ganzen Migrationspfad gemessen stand danach weiterhin
     * `generation=Computed("qty"*2)` im Reverse. Eine angenommene Anweisung ist
     * eben noch keine wirksame.
     */
    test("turning a computed column into an ordinary one is refused: the MODIFY changes nothing") {
        val result = renderGenerationChange(virtual, null)
        result.statements.shouldBeEmpty()
        val message = result.diagnostics.single().message
        message shouldContain "accepts"
        message shouldContain "still virtual"
    }

    test("the identity mode is switched in place") {
        val result = renderGenerationChange(
            ColumnGeneration.Identity(IdentityMode.ALWAYS),
            ColumnGeneration.Identity(IdentityMode.BY_DEFAULT),
        )
        result.statements.single().sql shouldContain "MODIFY \"line_total\" GENERATED BY DEFAULT AS IDENTITY"
    }

    test("identity is dropped in place, and the values stay") {
        val result = renderGenerationChange(ColumnGeneration.Identity(IdentityMode.ALWAYS), null)
        result.statements.single().sql shouldContain "MODIFY \"line_total\" DROP IDENTITY"
    }

    /**
     * Oracle nimmt der Spalte mit der Identity auch ihr implizites `NOT NULL`
     * (live gemessen: `required` kippte auf false und der Post-Compare meldete
     * Drift). Verlangt das Soll sie weiter als Pflichtfeld, zieht der Renderer
     * den Zwang mit einer zweiten Anweisung nach.
     */
    test("a required column keeps its NOT NULL when the identity goes") {
        val result = gen.generateUp(
            planner.plan(
                requiredSchema(ColumnGeneration.Identity(IdentityMode.ALWAYS)),
                requiredSchema(null),
                SchemaDiff(
                    tablesChanged = listOf(
                        TableDiff(
                            name = "order_line",
                            columnsChanged = listOf(
                                ColumnDiff(
                                    name = "line_total",
                                    generation = ValueChange(ColumnGeneration.Identity(IdentityMode.ALWAYS), null),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
            DdlGenerationOptions(),
        )
        val sql = result.statements.map { it.sql }
        sql.size shouldBe 2
        sql[0] shouldContain "DROP IDENTITY"
        sql[1] shouldContain "NOT NULL"
    }

    test("making an ordinary column an identity one is refused with ORA-30673") {
        val result = renderGenerationChange(null, ColumnGeneration.Identity(IdentityMode.BY_DEFAULT))
        result.statements.shouldBeEmpty()
        val message = result.diagnostics.single().message
        message shouldContain "would make"
        message shouldContain "ORA-30673"
    }

    test("making an ordinary column computed is refused with ORA-54026") {
        val result = renderGenerationChange(null, virtual)
        result.statements.shouldBeEmpty()
        val message = result.diagnostics.single().message
        message shouldContain "would make the ordinary column"
        message shouldContain "ORA-54026"
    }

    test("swapping identity for a computation is refused, not reported as an expression change") {
        val result = renderGenerationChange(ColumnGeneration.Identity(IdentityMode.ALWAYS), virtual)
        result.statements.shouldBeEmpty()
        val message = result.diagnostics.single().message
        message shouldContain "swaps identity and computation"
        message shouldNotContain "would drop the computed expression"
    }
})
