package dev.dmigrate.driver.postgresql

import dev.dmigrate.core.model.*
import dev.dmigrate.driver.SchemaReadNote
import dev.dmigrate.driver.SchemaReadSeverity

/**
 * Pure functions for mapping PostgreSQL metadata to neutral types.
 * Extracted from [PostgresSchemaReader] for unit-testability.
 */
internal object PostgresTypeMapping {

    data class MappingResult(
        val type: NeutralType,
        val generation: ColumnGeneration? = null,
        val note: SchemaReadNote? = null,
    )

    data class ColumnInput(
        val dataType: String,
        val udtName: String,
        val isPkCol: Boolean,
        val isIdentity: Boolean,
        val identityGeneration: String?,
        val colDefault: String?,
        val generatedSequenceName: String?,
        val charMaxLen: Int?,
        val numPrecision: Int?,
        val numScale: Int?,
        val tableName: String,
        val colName: String,
        // VA2 (Spatial): aus geometry_columns/geography_columns gelesener
        // PostGIS-Subtyp (POINT/…) + SRID; null, wenn keine PostGIS-Spalte.
        val geometrySubtype: String? = null,
        val geometrySrid: Int? = null,
        /** `information_schema.columns.udt_schema` — das Schema des Typs. */
        val udtSchema: String? = null,
        /** Das Schema, in dem die PostGIS-Extension liegt (null: nicht installiert). */
        val postgisSchema: String? = null,
    )

    fun mapColumn(input: ColumnInput): MappingResult {
        val dt = input.dataType.lowercase()
        val udt = input.udtName.lowercase()

        // N5: a `nextval` default is identity/serial ONLY for a true IDENTITY
        // column or a serial PK. A non-PK `DEFAULT nextval('s')` is a named-
        // sequence reference (→ SequenceNextVal default), not an identity column.
        val isGenerated = input.isIdentity || (isSerialDefault(input.colDefault) && input.isPkCol)
        if (isGenerated && (udt == "int8" || dt == "bigint")) {
            return MappingResult(
                NeutralType.BigInteger,
                generation = identityGeneration(input),
            )
        }

        // Legacy 32-bit serial/identity PKs keep the existing Identifier contract —
        // **ausser** einer echten IDENTITY-Spalte mit `ALWAYS`.
        //
        // `identifier` traegt keinen Modus; der PostgreSQL-Generator rendert ihn
        // als `SERIAL`, und `SERIAL` nimmt einen ausdruecklich gesetzten Wert an.
        // `integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY` wurde damit schon
        // PostgreSQL → PostgreSQL zu `SERIAL`, und kein Vergleich zweier Reverses
        // sah es — der Verlust war still und auf dem Rueckweg in denselben
        // Dialekt vermeidbar. Eine solche Spalte liest deshalb wie der Zweig fuer
        // Nicht-Schluesselspalten: ihr Basistyp plus `generation: identity`.
        //
        // `BY DEFAULT` und `serial` behalten den `identifier`-Vertrag: dort
        // verspricht das Modell nichts, was das Rendern bricht.
        //
        // **Nur `integer`** (`bigint` laeuft schon durch den Zweig darueber).
        // Ein `smallint` bleibt `identifier`, obwohl derselbe Modus dort
        // genauso verlorengeht: das Modell traegt eine Identity nur auf
        // `integer` und `biginteger` (`E130`, `SchemaColumnValidationRules`
        // im Hexagon), und der
        // PostgreSQL-Generator rendert sie fuer keinen anderen Typ
        // ([PostgresColumnConstraintHelper]). Eine als `smallint` +
        // `identity(always)` gelesene Spalte liesse `schema generate` aus dem
        // eigenen Reverse abbrechen — aus einem verlustbehafteten, aber
        // lauffaehigen Weg wuerde ein abbrechender. Welche Breiten der
        // `identifier`-Vertrag traegt, ist eine eigene Frage
        // (`docs/planning/next/reader-treue-3-spatial.md`).
        if (input.isPkCol && isGenerated) {
            if (isAlwaysIdentity(input) && dt == "integer") {
                return MappingResult(NeutralType.Integer, generation = identityGeneration(input))
            }
            return MappingResult(NeutralType.Identifier(autoIncrement = true))
        }

        // Eine Identity-Spalte, die **nicht** im Primaerschluessel liegt und
        // kein `bigint` ist, fiel hier heraus: der Zweig oben faengt nur
        // `bigint`, der darunter nur den Primaerschluessel. Uebrig blieb ein
        // gewoehnliches `integer` -- gemessen an 18.6 kam
        // `counter int GENERATED BY DEFAULT AS IDENTITY` als
        // `type=Integer, generation=null, default=null` zurueck, und ein
        // `schema generate` daraus erzeugte eine Spalte ohne Generator. Der Typ
        // bleibt, was er ist; die Identity gehoert ins Modell.
        if (isGenerated) {
            mapIntegerTypes(dt)?.let { return it.copy(generation = identityGeneration(input)) }
        }

        return mapIntegerTypes(dt)
            ?: mapStringTypes(dt, input.charMaxLen)
            ?: mapNumericTypes(dt, input.numPrecision, input.numScale, "${input.tableName}.${input.colName}")
            ?: mapTemporalTypes(dt)
            ?: mapSpecialTypes(dt, udt, input)
            ?: MappingResult(
                type = NeutralType.Text(),
                note = SchemaReadNote(
                    severity = SchemaReadSeverity.WARNING, code = "R301",
                    objectName = "${input.tableName}.${input.colName}",
                    message = "Unknown PostgreSQL type '${input.dataType}' (udt: ${input.udtName}) mapped to text",
                ),
            )
    }

    /**
     * Eine echte `GENERATED ALWAYS AS IDENTITY`-Spalte. Ein `serial` traegt
     * `identity_generation = null` und faellt damit nicht darunter.
     */
    private fun isAlwaysIdentity(input: ColumnInput): Boolean =
        input.isIdentity && input.identityGeneration?.equals("always", ignoreCase = true) == true

    private fun identityGeneration(input: ColumnInput): ColumnGeneration.Identity =
        ColumnGeneration.Identity(
            mode = when (input.identityGeneration?.lowercase()) {
                "always" -> IdentityMode.ALWAYS
                else -> IdentityMode.BY_DEFAULT
            },
            sequenceName = input.generatedSequenceName,
            legacySerialSyntax = !input.isIdentity && isSerialDefault(input.colDefault),
        )

    private fun mapIntegerTypes(dt: String): MappingResult? = when (dt) {
        "integer" -> MappingResult(NeutralType.Integer)
        "bigint" -> MappingResult(NeutralType.BigInteger)
        "smallint" -> MappingResult(NeutralType.SmallInt)
        "boolean" -> MappingResult(NeutralType.BooleanType)
        else -> null
    }

    private fun mapStringTypes(dt: String, charMaxLen: Int?): MappingResult? = when (dt) {
        "text" -> MappingResult(NeutralType.Text())
        "character varying" -> MappingResult(NeutralType.Text(maxLength = charMaxLen))
        "character" -> MappingResult(NeutralType.Char(length = charMaxLen ?: 1))
        else -> null
    }

    private fun mapNumericTypes(
        dt: String,
        numPrecision: Int?,
        numScale: Int?,
        objectName: String,
    ): MappingResult? = when (dt) {
        "numeric", "decimal" -> if (numPrecision != null && numScale != null) {
            MappingResult(NeutralType.Decimal(numPrecision, numScale))
        } else {
            MappingResult(NeutralType.Float(), note = unboundedNumericNote(objectName))
        }
        "real" -> MappingResult(NeutralType.Float(FloatPrecision.SINGLE))
        "double precision" -> MappingResult(NeutralType.Float(FloatPrecision.DOUBLE))
        else -> null
    }

    /**
     * `numeric` ohne Praezision wird Gleitkomma — auch auf dem Rueckweg in
     * denselben Dialekt. PostgreSQL rechnet eine ungebundene `numeric` exakt,
     * `double precision` binaer; der Unterschied ist keine Darstellungsfrage,
     * sondern ein Rechenergebnis. Das neutrale Modell traegt keine
     * ungebundene Dezimalzahl (die Modellfrage liegt woanders), der Verlust
     * wird deshalb benannt statt behoben.
     */
    private fun unboundedNumericNote(objectName: String) = SchemaReadNote(
        severity = SchemaReadSeverity.WARNING,
        code = "R404",
        objectName = objectName,
        message = "PostgreSQL 'numeric' without precision mapped to float: the neutral model has no " +
            "unbounded decimal, and a rendered column is binary floating point.",
        hint = "Declare precision and scale on the source column, or fix them in the schema file, " +
            "if exact decimal arithmetic must survive.",
    )

    private fun mapTemporalTypes(dt: String): MappingResult? = when (dt) {
        "timestamp without time zone" -> MappingResult(NeutralType.DateTime(timezone = false))
        "timestamp with time zone" -> MappingResult(NeutralType.DateTime(timezone = true))
        "date" -> MappingResult(NeutralType.Date)
        "time without time zone", "time with time zone" -> MappingResult(NeutralType.Time)
        else -> null
    }

    private fun mapSpecialTypes(
        dt: String,
        udt: String,
        input: ColumnInput,
    ): MappingResult? {
        val objectName = "${input.tableName}.${input.colName}"
        return when (dt) {
            "uuid" -> MappingResult(NeutralType.Uuid)
            // `json` und `jsonb` sind dasselbe neutrale `json`; nur `json` verliert
            // dabei etwas (siehe [jsonTextualNote]).
            "jsonb" -> MappingResult(NeutralType.Json)
            "json" -> MappingResult(NeutralType.Json, note = jsonTextualNote(objectName))
            "xml" -> MappingResult(NeutralType.Xml)
            "bytea" -> MappingResult(NeutralType.Binary)
            // ADR 0015: tsvector is a first-class neutral FullText type — captured
            // faithfully instead of degrading to text (R301).
            "tsvector" -> MappingResult(NeutralType.FullText)
            "user-defined" -> mapUserDefined(
                udtName = udt,
                tableName = input.tableName,
                colName = input.colName,
                geometrySubtype = input.geometrySubtype,
                geometrySrid = input.geometrySrid,
                udtSchema = input.udtSchema,
                postgisSchema = input.postgisSchema,
            )
            "array" -> mapArrayColumn(udt, objectName)
            else -> null
        }
    }

    /**
     * Eine `json`-Spalte kommt als neutrales `json` und wird auf dem Rueckweg
     * `jsonb` gerendert. Beim Uebertragen aendern sich damit die **Daten**:
     * `jsonb` normalisiert, verwirft doppelte Schluessel, ordnet die Schluessel
     * um und entfernt bedeutungslosen Leerraum. `jsonb` selbst verliert
     * nichts und meldet nichts.
     */
    private fun jsonTextualNote(objectName: String) = SchemaReadNote(
        severity = SchemaReadSeverity.WARNING,
        code = "R402",
        objectName = objectName,
        message = "PostgreSQL 'json' mapped to neutral 'json', which renders as 'jsonb': the stored text " +
            "is normalised — key order, duplicate keys and insignificant whitespace are lost.",
        hint = "Keep the column as text if the exact document text matters; 'jsonb' itself loses nothing.",
    )

    /**
     * Eine Array-Spalte samt der Note ihrer Elementart.
     *
     * Zwei Faelle sind laut: ein Element, das der Reverse nicht benennt
     * (`date[]`, `inet[]` — es liest `text`), meldet `R301` wie jeder andere
     * `else`-Fallback; ein `json[]` meldet `R402`, weil sein Element denselben
     * Weg nimmt wie eine `json`-Spalte.
     */
    private fun mapArrayColumn(udt: String, objectName: String): MappingResult {
        val elementUdt = udt.removePrefix("_")
        val known = knownArrayElementType(elementUdt)
        val note = when {
            known == null -> SchemaReadNote(
                severity = SchemaReadSeverity.WARNING,
                code = "R301",
                objectName = objectName,
                message = "Unknown PostgreSQL array element type '$elementUdt' mapped to text",
                hint = "Review the column and adjust the element type in the schema file if needed.",
            )
            elementUdt == "json" -> jsonTextualNote(objectName)
            else -> null
        }
        return MappingResult(NeutralType.Array(known ?: "text"), note = note)
    }

    /**
     * Ein benutzerdefinierter Typ: PostGIS-Spalte oder Anwendertyp.
     *
     * Welcher von beidem, entscheidet [PostgresPostgisType] — am Namen **und
     * am Schema**, denn `geometry` und `geography` sind gewoehnliche
     * Typnamen, die auch ein Anwendertyp tragen darf.
     */
    fun mapUserDefined(
        udtName: String,
        tableName: String,
        colName: String,
        geometrySubtype: String? = null,
        geometrySrid: Int? = null,
        udtSchema: String? = null,
        postgisSchema: String? = null,
    ): MappingResult {
        val postgis = PostgresPostgisType.mapColumn(
            udtName = udtName,
            udtSchema = udtSchema,
            postgisSchema = postgisSchema,
            objectName = "$tableName.$colName",
            subtype = geometrySubtype,
            srid = geometrySrid,
        )
        return postgis ?: MappingResult(NeutralType.Enum(refType = udtName))
    }

    fun mapArrayElementType(elementUdt: String): String = knownArrayElementType(elementUdt) ?: "text"

    /**
     * Die Elementart, **die der Reverse benennt** — oder `null`, wenn er sie
     * nicht kennt. Der Unterschied traegt zwei Entscheidungen: `null` ist der
     * `else`-Fallback und damit meldepflichtig (`R301`,
     * `spec/type-mapping.md` Abschnitt 8), und der PostgreSQL-Generator
     * rendert genau diesen Satz in seinem Typ (`PostgresTypeMapper.elementSql`).
     */
    private fun knownArrayElementType(elementUdt: String): String? = when (elementUdt) {
        "int4", "int2" -> "integer"
        "int8" -> "biginteger"
        "text", "varchar", "bpchar" -> "text"
        "bool" -> "boolean"
        "uuid" -> "uuid"
        "float4", "float8" -> "float"
        "numeric" -> "decimal"
        "json", "jsonb" -> "json"
        else -> null
    }

    fun isSerialDefault(default: String?): Boolean {
        if (default == null) return false
        return default.lowercase().contains("nextval(")
    }

    /** N5: the bare sequence name out of `nextval('schema.seq'::regclass)`, or null. */
    fun sequenceNameFromNextval(default: String?): String? {
        val raw = Regex("""nextval\('([^']+)'""", RegexOption.IGNORE_CASE)
            .find(default ?: return null)?.groupValues?.get(1) ?: return null
        return raw.substringAfterLast('.').removeSurrounding("\"")
    }

    fun parseDefault(raw: String?): DefaultValue? {
        if (raw == null) return null
        val trimmed = raw.trim()
        parseFunctionDefault(trimmed)?.let { return it }
        return when {
            trimmed.equals("NULL", ignoreCase = true) -> null
            trimmed.startsWith("nextval(") -> null
            trimmed.equals("true", ignoreCase = true) -> DefaultValue.BooleanLiteral(true)
            trimmed.equals("false", ignoreCase = true) -> DefaultValue.BooleanLiteral(false)
            trimmed.startsWith("'") && trimmed.contains("'::") -> {
                val value = trimmed.substringAfter("'").substringBefore("'::")
                DefaultValue.StringLiteral(value.replace("''", "'"))
            }
            trimmed.startsWith("'") && trimmed.endsWith("'") ->
                DefaultValue.StringLiteral(trimmed.substring(1, trimmed.length - 1).replace("''", "'"))
            trimmed.toLongOrNull() != null -> DefaultValue.NumberLiteral(trimmed.toLong())
            trimmed.toDoubleOrNull() != null -> DefaultValue.NumberLiteral(trimmed.toDouble())
            trimmed.contains("::") -> {
                val literal = trimmed.substringBefore("::")
                if (literal.startsWith("'") && literal.endsWith("'")) {
                    DefaultValue.StringLiteral(literal.substring(1, literal.length - 1))
                } else {
                    literal.toLongOrNull()?.let { DefaultValue.NumberLiteral(it) }
                        ?: literal.toDoubleOrNull()?.let { DefaultValue.NumberLiteral(it) }
                        ?: DefaultValue.FunctionCall(trimmed)
                }
            }
            else -> DefaultValue.FunctionCall(trimmed)
        }
    }

    /** Recognised PostgreSQL function/keyword defaults, normalised to canonical names. */
    private fun parseFunctionDefault(trimmed: String): DefaultValue.FunctionCall? = when {
        trimmed.equals("CURRENT_TIMESTAMP", ignoreCase = true) ||
            trimmed.equals("now()", ignoreCase = true) -> DefaultValue.FunctionCall("current_timestamp")
        trimmed.equals("CURRENT_DATE", ignoreCase = true) -> DefaultValue.FunctionCall("current_date")
        trimmed.equals("CURRENT_TIME", ignoreCase = true) -> DefaultValue.FunctionCall("current_time")
        trimmed.equals("gen_random_uuid()", ignoreCase = true) -> DefaultValue.FunctionCall("gen_uuid")
        else -> null
    }

    fun mapParamType(pgType: String): String = when (pgType.lowercase()) {
        "int4", "integer" -> "integer"
        "int8", "bigint" -> "biginteger"
        "int2", "smallint" -> "smallint"
        "text", "varchar", "bpchar", "character varying" -> "text"
        "bool", "boolean" -> "boolean"
        "float4", "real" -> "float"
        "float8", "double precision" -> "float"
        "numeric", "decimal" -> "decimal"
        "uuid" -> "uuid"
        "json", "jsonb" -> "json"
        "bytea" -> "binary"
        "void" -> "void"
        else -> pgType
    }

    fun mapCompositeFieldType(pgType: String): NeutralType =
        knownCompositeFieldType(pgType) ?: NeutralType.Text()

    /**
     * Das Feld eines zusammengesetzten Typs samt seiner Note.
     *
     * Dieselben stillen Rueckfaelle wie an einer Spalte, an derselben Klasse
     * gemessen: `numeric` ohne Praezision wird Gleitkomma (`R404`), ein
     * unbekannter Feldtyp wird `text` (`R301`), und ein `json`-Feld rendert
     * als `jsonb` zurueck (`R402`) — `CREATE TYPE … AS (…)` schreibt den
     * Feldtyp durch denselben Mapper wie eine Spalte. `spec/type-mapping.md`,
     * Abschnitt 8, verlangt fuer den `else`-Fallback ohnehin eine Note; sie
     * fehlte hier.
     */
    fun compositeField(pgType: String, objectName: String): MappingResult {
        val lower = pgType.lowercase().trim()
        val known = knownCompositeFieldType(pgType)
        val unbounded = (lower.startsWith("numeric") || lower.startsWith("decimal")) &&
            Regex("\\((\\d+),(\\d+)\\)").find(lower) == null
        return when {
            known == null -> MappingResult(
                NeutralType.Text(),
                note = SchemaReadNote(
                    severity = SchemaReadSeverity.WARNING,
                    code = "R301",
                    objectName = objectName,
                    message = "Unknown PostgreSQL composite field type '$pgType' mapped to text",
                    hint = "Review the field and adjust the type in the schema file if needed.",
                ),
            )
            unbounded -> MappingResult(known, note = unboundedNumericNote(objectName))
            // Wie an der Spalte: `json` verliert den gespeicherten Text, `jsonb`
            // verliert nichts und meldet nichts.
            lower == "json" -> MappingResult(known, note = jsonTextualNote(objectName))
            else -> MappingResult(known)
        }
    }

    private fun knownCompositeFieldType(pgType: String): NeutralType? {
        val lower = pgType.lowercase().trim()
        return when {
            lower == "integer" || lower == "int4" -> NeutralType.Integer
            lower == "bigint" || lower == "int8" -> NeutralType.BigInteger
            lower == "smallint" || lower == "int2" -> NeutralType.SmallInt
            lower == "text" -> NeutralType.Text()
            lower == "boolean" || lower == "bool" -> NeutralType.BooleanType
            lower.startsWith("character varying") || lower.startsWith("varchar") -> {
                val len = Regex("\\((\\d+)\\)").find(lower)?.groupValues?.get(1)?.toIntOrNull()
                NeutralType.Text(maxLength = len)
            }
            lower.startsWith("numeric") || lower.startsWith("decimal") -> {
                val match = Regex("\\((\\d+),(\\d+)\\)").find(lower)
                if (match != null) NeutralType.Decimal(match.groupValues[1].toInt(), match.groupValues[2].toInt())
                else NeutralType.Float()
            }
            lower == "uuid" -> NeutralType.Uuid
            lower == "json" || lower == "jsonb" -> NeutralType.Json
            lower == "bytea" -> NeutralType.Binary
            lower == "date" -> NeutralType.Date
            lower == "time" || lower.startsWith("time ") -> NeutralType.Time
            lower.startsWith("timestamp") -> NeutralType.DateTime(timezone = lower.contains("with time zone"))
            else -> null
        }
    }
}
