package dev.dmigrate.driver.postgresql

import dev.dmigrate.core.model.*
import dev.dmigrate.driver.SchemaReadNote
import dev.dmigrate.driver.SchemaReadSeverity

/**
 * Pure functions for mapping PostgreSQL metadata to neutral types.
 * Extracted from [PostgresSchemaReader] for unit-testability.
 */
internal object PostgresTypeMapping {

    data class MappingResult(
        val type: NeutralType,
        val generation: ColumnGeneration? = null,
        val note: SchemaReadNote? = null,
    )

    data class ColumnInput(
        val dataType: String,
        val udtName: String,
        val isPkCol: Boolean,
        val isIdentity: Boolean,
        val identityGeneration: String?,
        val colDefault: String?,
        val generatedSequenceName: String?,
        val charMaxLen: Int?,
        val numPrecision: Int?,
        val numScale: Int?,
        val tableName: String,
        val colName: String,
        // VA2 (Spatial): aus geometry_columns gelesener PostGIS-Subtyp (POINT/…)
        // + SRID einer `geometry`-Spalte; null, wenn keine PostGIS-Geometrie.
        val geometrySubtype: String? = null,
        val geometrySrid: Int? = null,
    )

    fun mapColumn(input: ColumnInput): MappingResult {
        val dt = input.dataType.lowercase()
        val udt = input.udtName.lowercase()

        // N5: a `nextval` default is identity/serial ONLY for a true IDENTITY
        // column or a serial PK. A non-PK `DEFAULT nextval('s')` is a named-
        // sequence reference (→ SequenceNextVal default), not an identity column.
        val isGenerated = input.isIdentity || (isSerialDefault(input.colDefault) && input.isPkCol)
        if (isGenerated && (udt == "int8" || dt == "bigint")) {
            return MappingResult(
                NeutralType.BigInteger,
                generation = identityGeneration(input),
            )
        }

        // Legacy 32-bit serial/identity PKs keep the existing Identifier contract.
        if (input.isPkCol && isGenerated) {
            return when {
                udt == "int4" || udt == "int2" || dt == "integer" || dt == "smallint" ->
                    MappingResult(NeutralType.Identifier(autoIncrement = true))
                else -> MappingResult(NeutralType.Identifier(autoIncrement = true))
            }
        }

        // Eine Identity-Spalte, die **nicht** im Primaerschluessel liegt und
        // kein `bigint` ist, fiel hier heraus: der Zweig oben faengt nur
        // `bigint`, der darunter nur den Primaerschluessel. Uebrig blieb ein
        // gewoehnliches `integer` -- gemessen an 18.6 kam
        // `counter int GENERATED BY DEFAULT AS IDENTITY` als
        // `type=Integer, generation=null, default=null` zurueck, und ein
        // `schema generate` daraus erzeugte eine Spalte ohne Generator. Der Typ
        // bleibt, was er ist; die Identity gehoert ins Modell.
        if (isGenerated) {
            mapIntegerTypes(dt)?.let { return it.copy(generation = identityGeneration(input)) }
        }

        return mapIntegerTypes(dt)
            ?: mapStringTypes(dt, input.charMaxLen)
            ?: mapNumericTypes(dt, input.numPrecision, input.numScale, "${input.tableName}.${input.colName}")
            ?: mapTemporalTypes(dt)
            ?: mapSpecialTypes(dt, udt, input.tableName, input.colName, input.geometrySubtype, input.geometrySrid)
            ?: MappingResult(
                type = NeutralType.Text(),
                note = SchemaReadNote(
                    severity = SchemaReadSeverity.WARNING, code = "R301",
                    objectName = "${input.tableName}.${input.colName}",
                    message = "Unknown PostgreSQL type '${input.dataType}' (udt: ${input.udtName}) mapped to text",
                ),
            )
    }

    private fun identityGeneration(input: ColumnInput): ColumnGeneration.Identity =
        ColumnGeneration.Identity(
            mode = when (input.identityGeneration?.lowercase()) {
                "always" -> IdentityMode.ALWAYS
                else -> IdentityMode.BY_DEFAULT
            },
            sequenceName = input.generatedSequenceName,
            legacySerialSyntax = !input.isIdentity && isSerialDefault(input.colDefault),
        )

    private fun mapIntegerTypes(dt: String): MappingResult? = when (dt) {
        "integer" -> MappingResult(NeutralType.Integer)
        "bigint" -> MappingResult(NeutralType.BigInteger)
        "smallint" -> MappingResult(NeutralType.SmallInt)
        "boolean" -> MappingResult(NeutralType.BooleanType)
        else -> null
    }

    private fun mapStringTypes(dt: String, charMaxLen: Int?): MappingResult? = when (dt) {
        "text" -> MappingResult(NeutralType.Text())
        "character varying" -> MappingResult(NeutralType.Text(maxLength = charMaxLen))
        "character" -> MappingResult(NeutralType.Char(length = charMaxLen ?: 1))
        else -> null
    }

    private fun mapNumericTypes(
        dt: String,
        numPrecision: Int?,
        numScale: Int?,
        objectName: String,
    ): MappingResult? = when (dt) {
        "numeric", "decimal" -> if (numPrecision != null && numScale != null) {
            MappingResult(NeutralType.Decimal(numPrecision, numScale))
        } else {
            MappingResult(NeutralType.Float(), note = unboundedNumericNote(objectName))
        }
        "real" -> MappingResult(NeutralType.Float(FloatPrecision.SINGLE))
        "double precision" -> MappingResult(NeutralType.Float(FloatPrecision.DOUBLE))
        else -> null
    }

    /**
     * `numeric` ohne Praezision wird Gleitkomma — auch auf dem Rueckweg in
     * denselben Dialekt. PostgreSQL rechnet eine ungebundene `numeric` exakt,
     * `double precision` binaer; der Unterschied ist keine Darstellungsfrage,
     * sondern ein Rechenergebnis. Das neutrale Modell traegt keine
     * ungebundene Dezimalzahl (die Modellfrage liegt woanders), der Verlust
     * wird deshalb benannt statt behoben.
     */
    private fun unboundedNumericNote(objectName: String) = SchemaReadNote(
        severity = SchemaReadSeverity.WARNING,
        code = "R404",
        objectName = objectName,
        message = "PostgreSQL 'numeric' without precision mapped to float: the neutral model has no " +
            "unbounded decimal, and a rendered column is binary floating point.",
        hint = "Declare precision and scale on the source column, or fix them in the schema file, " +
            "if exact decimal arithmetic must survive.",
    )

    private fun mapTemporalTypes(dt: String): MappingResult? = when (dt) {
        "timestamp without time zone" -> MappingResult(NeutralType.DateTime(timezone = false))
        "timestamp with time zone" -> MappingResult(NeutralType.DateTime(timezone = true))
        "date" -> MappingResult(NeutralType.Date)
        "time without time zone", "time with time zone" -> MappingResult(NeutralType.Time)
        else -> null
    }

    private fun mapSpecialTypes(
        dt: String,
        udt: String,
        tableName: String,
        colName: String,
        geometrySubtype: String?,
        geometrySrid: Int?,
    ): MappingResult? = when (dt) {
        "uuid" -> MappingResult(NeutralType.Uuid)
        // `json` und `jsonb` sind dasselbe neutrale `json`; nur `json` verliert
        // dabei etwas (siehe [jsonTextualNote]).
        "jsonb" -> MappingResult(NeutralType.Json)
        "json" -> MappingResult(NeutralType.Json, note = jsonTextualNote("$tableName.$colName"))
        "xml" -> MappingResult(NeutralType.Xml)
        "bytea" -> MappingResult(NeutralType.Binary)
        // ADR 0015: tsvector is a first-class neutral FullText type — captured
        // faithfully instead of degrading to text (R301).
        "tsvector" -> MappingResult(NeutralType.FullText)
        "user-defined" -> mapUserDefined(udt, tableName, colName, geometrySubtype, geometrySrid)
        "array" -> mapArrayColumn(udt, "$tableName.$colName")
        else -> null
    }

    /**
     * Eine `json`-Spalte kommt als neutrales `json` und wird auf dem Rueckweg
     * `jsonb` gerendert. Beim Uebertragen aendern sich damit die **Daten**:
     * `jsonb` normalisiert, verwirft doppelte Schluessel, ordnet die Schluessel
     * um und entfernt bedeutungslosen Leerraum. `jsonb` selbst verliert
     * nichts und meldet nichts.
     */
    private fun jsonTextualNote(objectName: String) = SchemaReadNote(
        severity = SchemaReadSeverity.WARNING,
        code = "R402",
        objectName = objectName,
        message = "PostgreSQL 'json' mapped to neutral 'json', which renders as 'jsonb': the stored text " +
            "is normalised — key order, duplicate keys and insignificant whitespace are lost.",
        hint = "Keep the column as text if the exact document text matters; 'jsonb' itself loses nothing.",
    )

    /**
     * Eine Array-Spalte samt der Note ihrer Elementart.
     *
     * Zwei Faelle sind laut: ein Element, das der Reverse nicht benennt
     * (`date[]`, `inet[]` — es liest `text`), meldet `R301` wie jeder andere
     * `else`-Fallback; ein `json[]` meldet `R402`, weil sein Element denselben
     * Weg nimmt wie eine `json`-Spalte.
     */
    private fun mapArrayColumn(udt: String, objectName: String): MappingResult {
        val elementUdt = udt.removePrefix("_")
        val known = knownArrayElementType(elementUdt)
        val note = when {
            known == null -> SchemaReadNote(
                severity = SchemaReadSeverity.WARNING,
                code = "R301",
                objectName = objectName,
                message = "Unknown PostgreSQL array element type '$elementUdt' mapped to text",
                hint = "Review the column and adjust the element type in the schema file if needed.",
            )
            elementUdt == "json" -> jsonTextualNote(objectName)
            else -> null
        }
        return MappingResult(NeutralType.Array(known ?: "text"), note = note)
    }

    fun mapUserDefined(
        udtName: String,
        tableName: String,
        colName: String,
        geometrySubtype: String? = null,
        geometrySrid: Int? = null,
    ): MappingResult {
        if (udtName == "geometry") return MappingResult(
            // VA2: Subtyp + SRID aus geometry_columns (null → GEOMETRY / keine SRID).
            type = NeutralType.Geometry(
                geometryType = GeometryType.of(geometrySubtype),
                srid = geometrySrid,
            ),
            note = SchemaReadNote(
                severity = SchemaReadSeverity.INFO,
                code = "R401",
                objectName = "$tableName.$colName",
                message = "PostGIS geometry column uses the PostGIS extension",
                hint = "Extension installation is reported separately by reverse note R400",
            ),
        )
        return MappingResult(NeutralType.Enum(refType = udtName))
    }

    fun mapArrayElementType(elementUdt: String): String = knownArrayElementType(elementUdt) ?: "text"

    /**
     * Die Elementart, **die der Reverse benennt** — oder `null`, wenn er sie
     * nicht kennt. Der Unterschied traegt zwei Entscheidungen: `null` ist der
     * `else`-Fallback und damit meldepflichtig (`R301`,
     * [spec/type-mapping.md] Abschnitt 8), und der PostgreSQL-Generator
     * rendert genau diesen Satz in seinem Typ (`PostgresTypeMapper.elementSql`).
     */
    private fun knownArrayElementType(elementUdt: String): String? = when (elementUdt) {
        "int4", "int2" -> "integer"
        "int8" -> "biginteger"
        "text", "varchar", "bpchar" -> "text"
        "bool" -> "boolean"
        "uuid" -> "uuid"
        "float4", "float8" -> "float"
        "numeric" -> "decimal"
        "json", "jsonb" -> "json"
        else -> null
    }

    fun isSerialDefault(default: String?): Boolean {
        if (default == null) return false
        return default.lowercase().contains("nextval(")
    }

    /** N5: the bare sequence name out of `nextval('schema.seq'::regclass)`, or null. */
    fun sequenceNameFromNextval(default: String?): String? {
        val raw = Regex("""nextval\('([^']+)'""", RegexOption.IGNORE_CASE)
            .find(default ?: return null)?.groupValues?.get(1) ?: return null
        return raw.substringAfterLast('.').removeSurrounding("\"")
    }

    fun parseDefault(raw: String?): DefaultValue? {
        if (raw == null) return null
        val trimmed = raw.trim()
        parseFunctionDefault(trimmed)?.let { return it }
        return when {
            trimmed.equals("NULL", ignoreCase = true) -> null
            trimmed.startsWith("nextval(") -> null
            trimmed.equals("true", ignoreCase = true) -> DefaultValue.BooleanLiteral(true)
            trimmed.equals("false", ignoreCase = true) -> DefaultValue.BooleanLiteral(false)
            trimmed.startsWith("'") && trimmed.contains("'::") -> {
                val value = trimmed.substringAfter("'").substringBefore("'::")
                DefaultValue.StringLiteral(value.replace("''", "'"))
            }
            trimmed.startsWith("'") && trimmed.endsWith("'") ->
                DefaultValue.StringLiteral(trimmed.substring(1, trimmed.length - 1).replace("''", "'"))
            trimmed.toLongOrNull() != null -> DefaultValue.NumberLiteral(trimmed.toLong())
            trimmed.toDoubleOrNull() != null -> DefaultValue.NumberLiteral(trimmed.toDouble())
            trimmed.contains("::") -> {
                val literal = trimmed.substringBefore("::")
                if (literal.startsWith("'") && literal.endsWith("'")) {
                    DefaultValue.StringLiteral(literal.substring(1, literal.length - 1))
                } else {
                    literal.toLongOrNull()?.let { DefaultValue.NumberLiteral(it) }
                        ?: literal.toDoubleOrNull()?.let { DefaultValue.NumberLiteral(it) }
                        ?: DefaultValue.FunctionCall(trimmed)
                }
            }
            else -> DefaultValue.FunctionCall(trimmed)
        }
    }

    /** Recognised PostgreSQL function/keyword defaults, normalised to canonical names. */
    private fun parseFunctionDefault(trimmed: String): DefaultValue.FunctionCall? = when {
        trimmed.equals("CURRENT_TIMESTAMP", ignoreCase = true) ||
            trimmed.equals("now()", ignoreCase = true) -> DefaultValue.FunctionCall("current_timestamp")
        trimmed.equals("CURRENT_DATE", ignoreCase = true) -> DefaultValue.FunctionCall("current_date")
        trimmed.equals("CURRENT_TIME", ignoreCase = true) -> DefaultValue.FunctionCall("current_time")
        trimmed.equals("gen_random_uuid()", ignoreCase = true) -> DefaultValue.FunctionCall("gen_uuid")
        else -> null
    }

    fun mapParamType(pgType: String): String = when (pgType.lowercase()) {
        "int4", "integer" -> "integer"
        "int8", "bigint" -> "biginteger"
        "int2", "smallint" -> "smallint"
        "text", "varchar", "bpchar", "character varying" -> "text"
        "bool", "boolean" -> "boolean"
        "float4", "real" -> "float"
        "float8", "double precision" -> "float"
        "numeric", "decimal" -> "decimal"
        "uuid" -> "uuid"
        "json", "jsonb" -> "json"
        "bytea" -> "binary"
        "void" -> "void"
        else -> pgType
    }

    fun mapCompositeFieldType(pgType: String): NeutralType =
        knownCompositeFieldType(pgType) ?: NeutralType.Text()

    /**
     * Das Feld eines zusammengesetzten Typs samt seiner Note.
     *
     * Dieselben zwei stillen Rueckfaelle wie an einer Spalte, an derselben
     * Klasse gemessen: `numeric` ohne Praezision wird Gleitkomma (`R404`),
     * ein unbekannter Feldtyp wird `text` (`R301`). `spec/type-mapping.md`,
     * Abschnitt 8, verlangt fuer den `else`-Fallback ohnehin eine Note; sie
     * fehlte hier.
     */
    fun compositeField(pgType: String, objectName: String): MappingResult {
        val lower = pgType.lowercase().trim()
        val known = knownCompositeFieldType(pgType)
        val unbounded = (lower.startsWith("numeric") || lower.startsWith("decimal")) &&
            Regex("\\((\\d+),(\\d+)\\)").find(lower) == null
        return when {
            known == null -> MappingResult(
                NeutralType.Text(),
                note = SchemaReadNote(
                    severity = SchemaReadSeverity.WARNING,
                    code = "R301",
                    objectName = objectName,
                    message = "Unknown PostgreSQL composite field type '$pgType' mapped to text",
                    hint = "Review the field and adjust the type in the schema file if needed.",
                ),
            )
            unbounded -> MappingResult(known, note = unboundedNumericNote(objectName))
            else -> MappingResult(known)
        }
    }

    private fun knownCompositeFieldType(pgType: String): NeutralType? {
        val lower = pgType.lowercase().trim()
        return when {
            lower == "integer" || lower == "int4" -> NeutralType.Integer
            lower == "bigint" || lower == "int8" -> NeutralType.BigInteger
            lower == "smallint" || lower == "int2" -> NeutralType.SmallInt
            lower == "text" -> NeutralType.Text()
            lower == "boolean" || lower == "bool" -> NeutralType.BooleanType
            lower.startsWith("character varying") || lower.startsWith("varchar") -> {
                val len = Regex("\\((\\d+)\\)").find(lower)?.groupValues?.get(1)?.toIntOrNull()
                NeutralType.Text(maxLength = len)
            }
            lower.startsWith("numeric") || lower.startsWith("decimal") -> {
                val match = Regex("\\((\\d+),(\\d+)\\)").find(lower)
                if (match != null) NeutralType.Decimal(match.groupValues[1].toInt(), match.groupValues[2].toInt())
                else NeutralType.Float()
            }
            lower == "uuid" -> NeutralType.Uuid
            lower == "json" || lower == "jsonb" -> NeutralType.Json
            lower == "bytea" -> NeutralType.Binary
            lower == "date" -> NeutralType.Date
            lower == "time" || lower.startsWith("time ") -> NeutralType.Time
            lower.startsWith("timestamp") -> NeutralType.DateTime(timezone = lower.contains("with time zone"))
            else -> null
        }
    }
}
