package dev.dmigrate.driver.connection

import java.sql.CallableStatement
import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.Statement

/**
 * Connection-Wrapper, der jede via [createStatement]/[prepareStatement]/
 * [prepareCall] erzeugte JDBC-Statement-Instanz mit `setQueryTimeout(...)`
 * versieht. Implementiert die Cancel-Reaktions-Schwelle aus
 * implementation-plan-0.9.6 §4.1: jeder atomar-nicht-cancelbare
 * Driver-Aufruf bricht innerhalb des Budgets ab.
 *
 * Direkte Aufrufe an [getMetaData] (z.B. `conn.metaData.getPrimaryKeys`)
 * sind **nicht** durch diesen Decorator abgedeckt — sie gehen durch
 * Driver-Code unter Umgehung des [Statement]-Objekts. Sie werden
 * stattdessen durch die separat in `HikariConnectionPool.borrow()`
 * gesetzte [Connection.setNetworkTimeout] zeitlich begrenzt
 * (Plan §5.3, `DatabaseMetaData`-Quirk).
 *
 * [queryTimeoutSeconds] `<= 0` bedeutet "nicht setzen" — der Treiber-
 * Default greift. [PoolSettings.statementTimeoutMs] = `0` ist der
 * dokumentierte Disable-Pfad (Plan §4.2).
 *
 * Klasse ist `internal`, weil der einzige Konstruktions-Pfad über
 * [HikariConnectionPool.borrow] läuft. Tests im selben Modul können
 * sie direkt instanziieren.
 */
internal class TimeoutDecoratedConnection(
    private val delegate: Connection,
    private val queryTimeoutSeconds: Int,
) : Connection by delegate {

    override fun createStatement(): Statement =
        delegate.createStatement().apply { applyTimeout() }

    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement =
        delegate.createStatement(resultSetType, resultSetConcurrency).apply { applyTimeout() }

    override fun createStatement(
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int,
    ): Statement =
        delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability)
            .apply { applyTimeout() }

    override fun prepareStatement(sql: String): PreparedStatement =
        delegate.prepareStatement(sql).apply { applyTimeout() }

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement =
        delegate.prepareStatement(sql, autoGeneratedKeys).apply { applyTimeout() }

    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement =
        delegate.prepareStatement(sql, columnIndexes).apply { applyTimeout() }

    override fun prepareStatement(sql: String, columnNames: Array<String>): PreparedStatement =
        delegate.prepareStatement(sql, columnNames).apply { applyTimeout() }

    override fun prepareStatement(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int,
    ): PreparedStatement =
        delegate.prepareStatement(sql, resultSetType, resultSetConcurrency).apply { applyTimeout() }

    override fun prepareStatement(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int,
    ): PreparedStatement =
        delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability)
            .apply { applyTimeout() }

    override fun prepareCall(sql: String): CallableStatement =
        delegate.prepareCall(sql).apply { applyTimeout() }

    override fun prepareCall(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int,
    ): CallableStatement =
        delegate.prepareCall(sql, resultSetType, resultSetConcurrency).apply { applyTimeout() }

    override fun prepareCall(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int,
    ): CallableStatement =
        delegate.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability)
            .apply { applyTimeout() }

    private fun Statement.applyTimeout() {
        if (queryTimeoutSeconds > 0) {
            queryTimeout = queryTimeoutSeconds
        }
    }
}
