package dev.dmigrate.server.core.error

enum class ToolErrorCode {
    AUTH_REQUIRED,
    FORBIDDEN_PRINCIPAL,
    POLICY_REQUIRED,
    POLICY_DENIED,
    IDEMPOTENCY_KEY_REQUIRED,
    IDEMPOTENCY_CONFLICT,
    RESOURCE_NOT_FOUND,
    VALIDATION_ERROR,
    RATE_LIMITED,
    OPERATION_TIMEOUT,
    PAYLOAD_TOO_LARGE,
    UPLOAD_SESSION_EXPIRED,
    UPLOAD_SESSION_ABORTED,
    UNSUPPORTED_MEDIA_TYPE,
    UNSUPPORTED_TOOL_OPERATION,
    PROMPT_HYGIENE_BLOCKED,
    TENANT_SCOPE_DENIED,
    INTERNAL_AGENT_ERROR,
}
