package dev.dmigrate.driver.oracle

import dev.dmigrate.driver.DatabaseDialect
import dev.dmigrate.driver.connection.ConnectionPool
import dev.dmigrate.driver.connection.asJdbc
import dev.dmigrate.driver.data.DataWriter
import dev.dmigrate.driver.data.ImportOptions
import dev.dmigrate.driver.data.OnConflict
import dev.dmigrate.driver.data.TableImportSession
import dev.dmigrate.driver.data.TriggerMode
import dev.dmigrate.driver.data.loadTargetColumns
import dev.dmigrate.driver.data.runSuppressing
import dev.dmigrate.driver.metadata.JdbcMetadataSession
import dev.dmigrate.driver.metadata.JdbcOperations
import java.sql.Connection

/**
 * Oracle [DataWriter] (ADR 0052 Slice 3).
 *
 * Eigenheiten gegenüber den anderen Dialekten:
 * - **`disableFkChecks`**: Oracle kennt kein globales `SET FOREIGN_KEY_CHECKS=0`
 *   (MySQL/SQLite); die Session deaktiviert die eigenen FK-Constraints der
 *   Zieltabelle einzeln (`ALTER TABLE ... DISABLE CONSTRAINT <name>`, DDL mit
 *   implizitem Commit -- deshalb außerhalb der Import-Transaktion) und schaltet
 *   sie im Cleanup wieder scharf ([OracleTableImportSession]).
 * - **Identity**: Oracle kennt kein `OVERRIDING SYSTEM VALUE` (`ORA-00926`,
 *   real verifiziert) -- eine `GENERATED ALWAYS AS IDENTITY`-Spalte im Chunk
 *   schaltet die Session deshalb vor dem ersten Insert per `ALTER TABLE ...
 *   MODIFY <col> GENERATED BY DEFAULT AS IDENTITY` temporär um und zurück im
 *   Cleanup ([OracleTableImportSession]); `GENERATED BY DEFAULT` braucht
 *   keine Umschaltung.
 * - **Konflikte**: Oracle kennt kein `INSERT IGNORE`/`ON CONFLICT`; `skip` und
 *   `update` laufen über `MERGE` (siehe [OracleInsertSql]).
 * - **Virtuelle Spalten** (`GENERATED ALWAYS AS (...) VIRTUAL`) lehnt der
 *   Import benennend ab, statt den Treiberfehler durchzureichen.
 */
class OracleDataWriter(
    private val jdbcFactory: (Connection) -> JdbcOperations = ::JdbcMetadataSession,
) : DataWriter {

    override val dialect: DatabaseDialect = DatabaseDialect.ORACLE

    override fun schemaSync() = OracleSchemaSync(jdbcFactory)

    /**
     * LN-013 Clean-Load-Kompensation: FK-Constraints tabellenweise aussetzen,
     * leeren, wieder scharf schalten. `TRUNCATE TABLE` scheidet aus -- Oracle
     * verbietet es für referenzierte Tabellen ohne `CASCADE` (das würde
     * abhängige Zeilen mitlöschen, nicht gewünscht).
     */
    override fun truncateTables(pool: ConnectionPool, tables: List<String>) {
        if (tables.isEmpty()) return
        pool.borrow().use { handle ->
            val conn = handle.asJdbc()
            val jdbc = jdbcFactory(conn)
            val savedAutoCommit = conn.autoCommit
            val schema = OracleIdentifiers.currentSchema(jdbc)
            val qualified = tables.map { OracleQualifiedTableName.parse(it, schema) }
            try {
                conn.autoCommit = true
                suspendDeleteRecheck(jdbc, qualified)
            } finally {
                conn.autoCommit = savedAutoCommit
            }
        }
    }

    /**
     * Setzt je Tabelle ihre eigenen FK-Constraints aus, leert alle, und
     * schaltet **jede ausgesetzte** Tabelle einzeln wieder scharf. Ein Fehler
     * mitten im Aussetzen darf keine Tabelle dauerhaft ungeprüft lassen, und
     * ein Fehler beim Re-Enable darf den ursprünglichen nicht verdecken.
     */
    private fun suspendDeleteRecheck(jdbc: JdbcOperations, tables: List<OracleQualifiedTableName>) {
        val suspended = mutableListOf<Pair<OracleQualifiedTableName, List<String>>>()
        var failure: Throwable? = null
        try {
            for (t in tables) {
                val fks = OracleMetadataQueries.listForeignKeys(jdbc, t.schema, t.table).map { it.name }
                for (fk in fks) disableConstraint(jdbc, t, fk)
                suspended += t to fks
            }
            for (t in tables) jdbc.execute("DELETE FROM ${t.quotedPath()}")
        } catch (t: Throwable) {
            failure = t
        }
        for ((table, fks) in suspended) {
            for (fk in fks) {
                runCatching { enableConstraint(jdbc, table, fk) }
                    .onFailure { reenable -> failure?.addSuppressed(reenable) ?: run { failure = reenable } }
            }
        }
        failure?.let { throw it }
    }

    override fun openTable(
        pool: ConnectionPool,
        table: String,
        options: ImportOptions,
    ): TableImportSession {
        check(options.triggerMode == TriggerMode.FIRE) {
            "triggerMode=${options.triggerMode} is not supported for Oracle -- " +
                "the Runner should have validated this via DialectCapabilities"
        }

        val conn = pool.borrow().asJdbc()
        val jdbc = jdbcFactory(conn)
        var savedAutoCommit: Boolean? = null
        var disabledTable: OracleQualifiedTableName? = null
        var disabledFkConstraints: List<String> = emptyList()
        try {
            savedAutoCommit = conn.autoCommit
            val schema = OracleIdentifiers.currentSchema(jdbc)
            val qualified = OracleQualifiedTableName.parse(table, schema)
            val targetColumns = loadTargetColumns(conn, qualified.quotedPath(), EMPTY_ROWS_CLAUSE)
            val identities = OracleMetadataQueries.identityColumns(jdbc, qualified.schema, qualified.table)
            val generatedAlwaysColumns = identities.filter { it.generation == "ALWAYS" }
                .mapTo(mutableSetOf()) { it.column }
            val virtualColumns = OracleMetadataQueries.virtualColumns(jdbc, qualified.schema, qualified.table)
            val primaryKeyColumns = if (options.onConflict == OnConflict.ABORT) {
                emptyList()
            } else {
                OracleMetadataQueries.listPrimaryKeyColumns(jdbc, qualified.schema, qualified.table).also {
                    require(it.isNotEmpty()) {
                        "Target table '$table' has no primary key; " +
                            "onConflict=${options.onConflict.name.lowercase()} requires a primary key on Oracle"
                    }
                }
            }

            if (!conn.autoCommit) conn.autoCommit = true
            if (options.disableFkChecks) {
                val fks = OracleMetadataQueries.listForeignKeys(jdbc, qualified.schema, qualified.table).map { it.name }
                for (fk in fks) disableConstraint(jdbc, qualified, fk)
                disabledTable = qualified
                disabledFkConstraints = fks
            }

            // §6.14 nicht-atomares Truncate: vor der Import-Transaktion, damit die
            // Tabelle auch bei einem späteren Fehler leer bleibt.
            if (options.truncate) {
                jdbc.execute("DELETE FROM ${qualified.quotedPath()}")
            }

            conn.autoCommit = false

            val session = OracleTableImportSession(
                conn = conn,
                savedAutoCommit = savedAutoCommit,
                table = table,
                qualifiedTable = qualified,
                targetColumns = targetColumns,
                primaryKeyColumns = primaryKeyColumns,
                generatedAlwaysColumns = generatedAlwaysColumns,
                virtualColumns = virtualColumns,
                disabledFkConstraints = disabledFkConstraints,
                options = options,
                jdbc = jdbc,
                schemaSync = OracleSchemaSync(jdbcFactory),
            )
            if (options.truncate) session.markTruncatePerformed()
            return session
        } catch (t: Throwable) {
            t.runSuppressing {
                val recovered = disabledTable
                if (recovered != null) {
                    if (!conn.autoCommit) conn.autoCommit = true
                    for (fk in disabledFkConstraints) enableConstraint(jdbc, recovered, fk)
                }
            }
            t.runSuppressing { if (!conn.autoCommit) conn.rollback() }
            t.runSuppressing { if (savedAutoCommit != null) conn.autoCommit = savedAutoCommit }
            t.runSuppressing { conn.close() }
            throw t
        }
    }

    private fun disableConstraint(jdbc: JdbcOperations, table: OracleQualifiedTableName, constraint: String) {
        jdbc.execute("ALTER TABLE ${table.quotedPath()} DISABLE CONSTRAINT ${OracleIdentifiers.quote(constraint)}")
    }

    /**
     * `ENABLE NOVALIDATE`, nicht das Oracle-Default `ENABLE VALIDATE`: mit
     * disabled Constraint eingefuegte Zeilen koennen die Bedingung
     * verletzen (das ist der Zweck von `disableFkChecks`), und `VALIDATE`
     * prueft beim Re-Enable alle Bestandszeilen -- ein Fund gegen den
     * Testcontainer, der sonst mit `ORA-02298` genau dort scheitert, wo
     * `disableFkChecks` gebraucht wird. `NOVALIDATE` schaltet den
     * Constraint fuer kuenftige DML scharf, ohne Altbestand zu pruefen.
     */
    private fun enableConstraint(jdbc: JdbcOperations, table: OracleQualifiedTableName, constraint: String) {
        jdbc.execute(
            "ALTER TABLE ${table.quotedPath()} ENABLE NOVALIDATE CONSTRAINT ${OracleIdentifiers.quote(constraint)}",
        )
    }

    internal companion object {
        /** Oracle kennt kein `LIMIT`; die Metadaten-Probe läuft über ein leeres Prädikat. */
        const val EMPTY_ROWS_CLAUSE = "WHERE 1 = 0"
    }
}
