package dev.dmigrate.driver.oracle

import dev.dmigrate.core.data.ImportSchemaMismatchException
import dev.dmigrate.driver.data.AbstractTableImportSession
import dev.dmigrate.driver.data.ImportOptions
import dev.dmigrate.driver.data.JdbcForeignValueNormalizer
import dev.dmigrate.driver.data.OnConflict
import dev.dmigrate.driver.data.SequenceAdjustment
import dev.dmigrate.driver.data.TargetColumn
import dev.dmigrate.driver.data.WriteResult
import dev.dmigrate.driver.metadata.JdbcOperations
import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.Statement

/**
 * Import-Session für Oracle.
 *
 * - `abort` → gebatchtes `INSERT`.
 * - `skip` → `MERGE` **ohne** `WHEN MATCHED`-Zweig: Oracle meldet je
 *   Batch-Element exakt 1 (eingefügt) oder 0 (Match, nichts getan) betroffene
 *   Zeilen -- dieselbe Unterscheidung wie PostgreSQLs `ON CONFLICT DO
 *   NOTHING`, siehe [OracleInsertSql].
 * - `update` → `MERGE` mit `WHEN MATCHED`- UND `WHEN NOT MATCHED`-Zweig:
 *   beide melden 1 betroffene Zeile, aus der Batch-Zählung nicht
 *   unterscheidbar -- gebucht als `rowsUnknown` statt geraten.
 * - `MERGE` braucht einen Schlüssel für `skip` UND `update` (bindet ihn im
 *   `ON`-Prädikat); der Writer verlangt dafür einen Primärschlüssel.
 * - **Kein `OVERRIDING SYSTEM VALUE`**: anders als PostgreSQL/DB2 kennt
 *   Oracles `INSERT`/`MERGE` diese SQL:2003-Klausel nicht (real gegen den
 *   Testcontainer verifiziert: `ORA-00926`). Enthält der Chunk eine
 *   `GENERATED ALWAYS AS IDENTITY`-Spalte, schaltet die Session die
 *   Tabelle stattdessen vor dem ersten Insert per `ALTER TABLE ... MODIFY
 *   <col> GENERATED BY DEFAULT AS IDENTITY` temporär um (DDL mit
 *   implizitem Commit, deshalb lazy beim ersten `write()`, wenn noch keine
 *   Zeile dieser Tabelle in der Transaktion aussteht) und zurück auf
 *   `GENERATED ALWAYS AS IDENTITY` im Cleanup -- dieselbe
 *   Umschalten-und-zurückschalten-Form wie beim FK-Disable unten, nur auf
 *   die Identity-Eigenschaft der Spalte statt auf eine Constraint bezogen.
 *   `GENERATED BY DEFAULT` braucht keine Umschaltung.
 * - `disableFkChecks`: Oracle kennt kein globales `SET FOREIGN_KEY_CHECKS=0`
 *   (MySQL) -- die Session deaktiviert die **eigenen** FK-Constraints der
 *   Zieltabelle einzeln (`ALTER TABLE ... DISABLE CONSTRAINT <name>`, DDL
 *   mit implizitem Commit, deshalb außerhalb der Import-Transaktion) und
 *   schaltet sie im Cleanup mit `ENABLE NOVALIDATE` wieder scharf --
 *   Oracles Default `ENABLE VALIDATE` würde am während der Deaktivierung
 *   eingefügten (bewusst nicht constraint-konformen) Bestand mit
 *   `ORA-02298` scheitern.
 */
internal class OracleTableImportSession(
    conn: Connection,
    savedAutoCommit: Boolean,
    table: String,
    private val qualifiedTable: OracleQualifiedTableName,
    targetColumns: List<TargetColumn>,
    primaryKeyColumns: List<String>,
    private val generatedAlwaysColumns: Set<String>,
    private val virtualColumns: Set<String>,
    private val disabledFkConstraints: List<String>,
    options: ImportOptions,
    private val jdbc: JdbcOperations,
    private val schemaSync: OracleSchemaSync,
) : AbstractTableImportSession(conn, savedAutoCommit, table, targetColumns, primaryKeyColumns, options) {

    private var fkReenabled: Boolean = false
    private var toggledIdentityColumns: List<String> = emptyList()

    /**
     * `MERGE` bindet die Schlüsselspalten aus der `src`-Zeile -- fehlt eine im
     * Chunk, gäbe es nur ein unverständliches Binding-Problem vom Treiber.
     * Gilt hier auch für `skip` (die Basisklasse prüft nur `update`, weil
     * PG/MySQL dort eine schlüsselfreie Form haben).
     */
    override fun validateUpsertColumns(resolvedTargetColumns: List<TargetColumn>) {
        super.validateUpsertColumns(resolvedTargetColumns)
        if (options.onConflict != OnConflict.SKIP || primaryKeyColumns.isEmpty()) return
        val imported = resolvedTargetColumns.mapTo(mutableSetOf()) { it.name }
        val missing = primaryKeyColumns.filterNot { it in imported }
        if (missing.isNotEmpty()) {
            throw ImportSchemaMismatchException(
                "onConflict=skip for table '$table' requires all primary key columns on Oracle " +
                    "(the MERGE predicate binds them); missing ${missing.joinToString()}",
            )
        }
    }

    override fun buildInsertSql(importedTargetColumns: List<TargetColumn>): String {
        rejectVirtualColumns(importedTargetColumns)
        toggleIdentityIfNeeded(importedTargetColumns)
        return OracleInsertSql.build(qualifiedTable, importedTargetColumns, primaryKeyColumns, options.onConflict)
    }

    override fun executeChunk(
        importedTargetColumns: List<TargetColumn>,
        rows: List<Array<Any?>>,
    ): WriteResult = when (options.onConflict) {
        OnConflict.ABORT -> executeAbortChunk(importedTargetColumns, rows)
        OnConflict.SKIP -> executeSkipChunk(importedTargetColumns, rows)
        OnConflict.UPDATE -> executeUpdateChunk(importedTargetColumns, rows)
    }

    override fun bindRow(
        stmt: PreparedStatement,
        importedTargetColumns: List<TargetColumn>,
        row: Array<Any?>,
    ) {
        importedTargetColumns.forEachIndexed { index, targetColumn ->
            val value = row[index]
            if (value == null) {
                stmt.setNull(index + 1, targetColumn.jdbcType)
            } else {
                stmt.setObject(index + 1, JdbcForeignValueNormalizer.normalize(value))
            }
        }
    }

    private fun executeAbortChunk(importedTargetColumns: List<TargetColumn>, rows: List<Array<Any?>>): WriteResult {
        val counts = addBatchAndExecute(importedTargetColumns, rows)
        var inserted = 0L
        for (count in counts) inserted += if (affected(count)) 1L else 0L
        return WriteResult(rowsInserted = inserted, rowsUpdated = 0, rowsSkipped = 0)
    }

    private fun executeSkipChunk(importedTargetColumns: List<TargetColumn>, rows: List<Array<Any?>>): WriteResult {
        val counts = addBatchAndExecute(importedTargetColumns, rows)
        var inserted = 0L
        var skipped = 0L
        for (count in counts) if (affected(count)) inserted++ else skipped++
        return WriteResult(rowsInserted = inserted, rowsUpdated = 0, rowsSkipped = skipped)
    }

    private fun executeUpdateChunk(importedTargetColumns: List<TargetColumn>, rows: List<Array<Any?>>): WriteResult {
        val counts = addBatchAndExecute(importedTargetColumns, rows)
        var unknown = 0L
        for (count in counts) unknown += if (affected(count)) 1L else 0L
        return WriteResult(rowsInserted = 0, rowsUpdated = 0, rowsSkipped = 0, rowsUnknown = unknown)
    }

    private fun addBatchAndExecute(importedTargetColumns: List<TargetColumn>, rows: List<Array<Any?>>): IntArray {
        val stmt = preparedStatement!!
        for (row in rows) {
            bindRow(stmt, importedTargetColumns, row)
            stmt.addBatch()
        }
        return stmt.executeBatch()
    }

    private fun affected(count: Int): Boolean = count == Statement.SUCCESS_NO_INFO || count > 0

    override fun reseedSequences(): List<SequenceAdjustment> = schemaSync.reseedGenerators(
        conn = conn,
        table = table,
        importedColumns = importedColumns.orEmpty(),
        truncatePerformed = truncatePerformed,
    )

    override fun finishDialectCleanup(): Throwable? {
        val fkFailure = reenableFkConstraints()
        val identityFailure = restoreIdentityColumns()
        if (fkFailure != null && identityFailure != null) {
            fkFailure.addSuppressed(identityFailure)
            return fkFailure
        }
        return fkFailure ?: identityFailure
    }

    override fun closeFinally() {
        reenableFkConstraints()?.let(::recordCleanupFailure)
        restoreIdentityColumns()?.let(::recordCleanupFailure)
        runCatching { conn.autoCommit = savedAutoCommit }.onFailure(::recordCleanupFailure)
    }

    /**
     * Schaltet jede `GENERATED ALWAYS`-Identity-Spalte, die im Chunk
     * enthalten ist, einmalig auf `GENERATED BY DEFAULT` um (DDL, impliziter
     * Commit -- unschaedlich hier, weil noch keine Zeile dieser Tabelle in
     * der Transaktion aussteht: `buildInsertSql` laeuft vor dem ersten
     * `addBatch()`). `GENERATED BY DEFAULT` akzeptiert explizite Werte ohne
     * jede Klausel, exakt wie eine normale Spalte.
     */
    private fun toggleIdentityIfNeeded(importedTargetColumns: List<TargetColumn>) {
        if (toggledIdentityColumns.isNotEmpty()) return
        val toToggle = importedTargetColumns.map { it.name }.filter { it in generatedAlwaysColumns }
        if (toToggle.isEmpty()) return
        if (!conn.autoCommit) conn.autoCommit = true
        for (name in toToggle) {
            jdbc.execute(
                "ALTER TABLE ${qualifiedTable.quotedPath()} MODIFY ${OracleIdentifiers.quote(name)} " +
                    "GENERATED BY DEFAULT AS IDENTITY",
            )
        }
        toggledIdentityColumns = toToggle
        conn.autoCommit = false
    }

    /**
     * Schaltet die umgeschalteten Spalten zurueck auf `GENERATED ALWAYS`.
     * Wie bei [reenableFkConstraints] ist ein nicht zurueckgeschalteter
     * Zustand DB-weit sichtbar (keine Connection-lokale Session-Einstellung
     * wie MSSQLs `IDENTITY_INSERT`) -- ein Fehler wird deshalb gemeldet,
     * nicht durch Verwerfen der Connection "geloest".
     */
    private fun restoreIdentityColumns(): Throwable? {
        if (toggledIdentityColumns.isEmpty()) return null
        return runCatching {
            if (!conn.autoCommit) conn.autoCommit = true
            for (name in toggledIdentityColumns) {
                jdbc.execute(
                    "ALTER TABLE ${qualifiedTable.quotedPath()} MODIFY ${OracleIdentifiers.quote(name)} " +
                        "GENERATED ALWAYS AS IDENTITY",
                )
            }
            toggledIdentityColumns = emptyList()
        }.exceptionOrNull()
    }

    /**
     * `ENABLE NOVALIDATE` (nicht Oracles Default `ENABLE VALIDATE`, real
     * verifiziert): waehrend `disableFkChecks` eingefuegte Zeilen koennen
     * die Bedingung verletzen -- das ist der Zweck dieser Option -- und
     * `VALIDATE` prueft beim Re-Enable den gesamten Bestand, scheitert also
     * genau dort mit `ORA-02298`, wo `disableFkChecks` gebraucht wird.
     * `NOVALIDATE` schaltet den Constraint fuer kuenftige DML scharf, ohne
     * Altbestand zu pruefen.
     *
     * Die `ALTER TABLE`-DDL committet implizit -- unproblematisch an dieser
     * Stelle, weil [finishTable]/[close] erst nach dem letzten
     * `commitChunk()` laufen, es also keine offene DML-Transaktion mehr gibt.
     * Anders als MSSQLs `IDENTITY_INSERT` ist ein nicht wieder aktivierter
     * Constraint **kein** Connection-lokaler, sondern ein DB-weiter Zustand --
     * ein Fehler hier wird deshalb gemeldet (`recordCleanupFailure`/
     * `FinishTableResult.PartialFailure`), nicht durch Verwerfen der
     * Connection "gelöst".
     */
    private fun reenableFkConstraints(): Throwable? {
        if (fkReenabled || disabledFkConstraints.isEmpty()) return null
        return runCatching {
            if (!conn.autoCommit) conn.autoCommit = true
            for (name in disabledFkConstraints) {
                jdbc.execute(
                    "ALTER TABLE ${qualifiedTable.quotedPath()} ENABLE NOVALIDATE CONSTRAINT " +
                        OracleIdentifiers.quote(name),
                )
            }
            fkReenabled = true
        }.exceptionOrNull()
    }

    private fun rejectVirtualColumns(importedTargetColumns: List<TargetColumn>) {
        val offending = importedTargetColumns.map { it.name }.filter { it in virtualColumns }
        if (offending.isEmpty()) return
        throw ImportSchemaMismatchException(
            "Target table '$table' has virtual column(s) ${offending.joinToString()}; Oracle does not allow " +
                "writing them. Exclude the column(s) from the export/transfer.",
        )
    }
}
