package dev.dmigrate.driver.oracle

import dev.dmigrate.core.diff.migration.DiffOperation
import dev.dmigrate.core.model.ConstraintType
import dev.dmigrate.core.model.IdentityMode
import dev.dmigrate.core.model.SchemaDefinition
import dev.dmigrate.core.model.TableDefinition
import dev.dmigrate.core.model.inOrdinalOrder
import dev.dmigrate.driver.DatabaseDialect
import dev.dmigrate.driver.SqlIdentifiers
import dev.dmigrate.driver.TransformationNote
import dev.dmigrate.driver.migration.MigrationBlockedReason

/**
 * Baut eine Tabelle neu, wenn Oracle eine Spalte nicht nachtraeglich zur
 * Identity-Spalte machen kann: anlegen, kopieren, alte loeschen, umbenennen.
 *
 * **Die Reihenfolge ist gemessen** (Oracle 23, 2026-09-08), nicht abgeleitet:
 *
 * 1. Die Zwischentabelle traegt die Identity-Spalte als `GENERATED BY DEFAULT`
 *    — nur so nimmt sie die **vorhandenen Schluesselwerte** an. Ein
 *    `GENERATED ALWAYS` lehnte den Einfuegewert mit `ORA-32795` ab, und der
 *    Neubau vergaebe neue Schluessel.
 * 2. Kopiert wird einschliesslich der Identity-Spalte; die alten Werte bleiben
 *    also stehen (gemessen: 7 und 42 ueberleben).
 * 3. Nach dem Umbenennen setzt
 *    `MODIFY <col> GENERATED <modus> AS IDENTITY (START WITH LIMIT VALUE)`
 *    den Zielmodus **und** den Zaehler ueber den groessten vorhandenen Wert
 *    (gemessen: der naechste Insert bekommt 43).
 *
 * **Die Zwischentabelle entsteht nackt** — nur Spalten. Constraints und
 * Indizes tragen schema-globale Namen; auf der Zwischentabelle angelegt
 * kollidierten sie mit denen der noch bestehenden alten Tabelle
 * (`ORA-00955`). Sie kommen deshalb erst nach dem Umbenennen dazu, unter
 * ihren echten Namen.
 *
 * **Eingehende Fremdschluessel** raeumt `DROP TABLE … CASCADE CONSTRAINTS`
 * mit ab. Der Neubau legt sie danach aus dem Zielschema wieder an; ohne das
 * verschwaenden sie still.
 */
internal object OracleRebuildRenderer {

    private val typeMapper = OracleTypeMapper()
    private fun quoteIdentifier(name: String): String = SqlIdentifiers.quoteIdentifier(name, DatabaseDialect.ORACLE)
    private val columnHelper = OracleColumnConstraintHelper(quoteIdentifier = ::quoteIdentifier, typeMapper = typeMapper)
    private val indexBuilder = OracleIndexDdlBuilder(quoteIdentifier = ::quoteIdentifier)

    fun render(rebuild: OracleRebuildPlanner.Rebuild, ctx: OracleDiffRenderContext) {
        val (table, trigger, bucket) = rebuild
        val targetSchema = ctx.schemaForDirection()
        val sourceSchema = ctx.schemaOppositeOfDirection()
        val target = targetSchema?.tables?.get(table)
        val source = sourceSchema?.tables?.get(table)
        if (targetSchema == null || target == null || source == null) {
            return block(
                bucket, ctx,
                "Rebuilding table '$table' needs both the current and the desired definition, but the " +
                    "DiffResult carries only one of them for this direction.",
                "ORACLE_TABLE_NOT_IN_SCHEMA", MigrationBlockedReason.MANUAL_ACTION_REQUIRED,
            )
        }
        if (target.partitioning != source.partitioning) {
            return block(
                bucket, ctx,
                "Table '$table' would be rebuilt while its partitioning changes; this path carries the " +
                    "existing partitioning over and cannot alter it.",
                "DIALECT_UNSUPPORTED_OPERATION", MigrationBlockedReason.DIALECT_UNSUPPORTED_OPERATION,
            )
        }
        if (ctx.options.strictGapOperations) {
            return block(
                bucket, ctx,
                "Rebuilding table '$table' drops and re-creates it, which leaves a window in which the table " +
                    "is absent (`hasGap = true`), and `--strict-gap-operations` is set.",
                "OPERATION_HAS_GAP_STRICT_BLOCKED", MigrationBlockedReason.MANUAL_ACTION_REQUIRED,
            )
        }

        val notes = mutableListOf<TransformationNote>()
        val statements = statementsFor(rebuild, ctx, targetSchema, sourceSchema, target, source, notes)
            ?: return block(
                bucket, ctx,
                "Table '$table' cannot be rebuilt: at least one of its constraints or indices is not " +
                    "renderable for Oracle" + notes.firstOrNull()?.let { " (${it.message})" }.orEmpty(),
                "ORACLE_CONSTRAINT_NOT_RENDERABLE", MigrationBlockedReason.MANUAL_ACTION_REQUIRED,
            )

        statements.forEach { ctx.emitRebuild(bucket, trigger, it) }
        ctx.carryOverNotes(trigger, notes)
        ctx.addInfoDiagnostic(
            code = "ORACLE_TABLE_REBUILT_FOR_IDENTITY",
            operationId = trigger.id,
            message = "Table '$table' is rebuilt (create, copy, drop, rename) because Oracle cannot turn an " +
                "existing column into an identity column (ORA-30673). The copy runs against a " +
                "GENERATED BY DEFAULT column, so the existing key values survive; the counter is reseeded " +
                "afterwards with START WITH LIMIT VALUE.",
        )
    }

    @Suppress("ReturnCount")
    private fun statementsFor(
        rebuild: OracleRebuildPlanner.Rebuild,
        ctx: OracleDiffRenderContext,
        targetSchema: SchemaDefinition,
        sourceSchema: SchemaDefinition?,
        target: TableDefinition,
        source: TableDefinition,
        notes: MutableList<TransformationNote>,
    ): List<String>? {
        val (table, _, bucket) = rebuild
        val temp = OracleRebuildPlanner.tempTableName(table, bucket)
        val unkeyable = target.columns.filterValues { typeMapper.isUnkeyable(it.type) }.keys
        val known = OracleIdentifierRequoter.knownIdentifiers(targetSchema)

        // Die Zwischentabelle: nur Spalten, Identity-Spalten in der
        // annehmenden Form.
        val declarations = target.columns.inOrdinalOrder().map { (name, col) ->
            columnHelper.generateColumnSql(
                temp, name, col, targetSchema, notes,
                identityModeOverride = IdentityMode.BY_DEFAULT.takeIf { OracleRebuildPlanner.isIdentity(col) },
                inlineNamedConstraints = false,
            )
        }
        val statements = mutableListOf<String>()
        statements += "CREATE TABLE ${ctx.sql.quote(temp)} (\n" +
            declarations.joinToString(",\n") { "    $it" } + "\n);"
        statements += copyStatement(table, temp, target, source, bucket, ctx)
        statements += "DROP TABLE ${ctx.sql.quote(table)} CASCADE CONSTRAINTS PURGE;"
        statements += "ALTER TABLE ${ctx.sql.quote(temp)} RENAME TO ${ctx.sql.quote(table)};"

        for ((name, col) in target.columns.inOrdinalOrder()) {
            if (!OracleRebuildPlanner.isIdentity(col)) continue
            statements += reseedStatement(table, name, OracleIdentity.modeOf(col), ctx)
        }
        if (target.primaryKey.isNotEmpty()) {
            val lobKeys = target.primaryKey.filter { it in unkeyable }
            if (lobKeys.isNotEmpty()) {
                notes += columnHelper.unkeyableKeyNote(table, "pk_$table", "PRIMARY KEY", lobKeys)
            } else {
                val cols = target.primaryKey.joinToString(", ") { ctx.sql.quote(it) }
                statements += "ALTER TABLE ${ctx.sql.quote(table)} ADD CONSTRAINT " +
                    "${ctx.sql.quote("pk_$table")} PRIMARY KEY ($cols);"
            }
        }
        statements += columnLevelConstraints(table, target, targetSchema, ctx)
        for (constraint in target.constraints.sortedBy { it.name }) {
            val clause = columnHelper.generateConstraintClause(table, constraint, unkeyable, notes, known)
                ?: return null
            statements += "ALTER TABLE ${ctx.sql.quote(table)} ADD $clause;"
        }
        for ((colName, col) in target.columns.inOrdinalOrder()) {
            val ref = col.references ?: continue
            statements += "ALTER TABLE ${ctx.sql.quote(table)} ADD " +
                columnHelper.buildForeignKeyClause(
                    "fk_${table}_$colName", listOf(colName), ref.table, listOf(ref.column), ref.onDelete, notes,
                ) + ";"
        }
        for (index in target.indices) {
            val statement = indexBuilder.render(table, target, index, unkeyable)
            if (statement.sql.isNotBlank()) statements += statement.sql
            notes += statement.notes
        }
        for (inbound in OracleRebuildPlanner.inboundForeignKeys(targetSchema, sourceSchema, table)) {
            val childUnkeyable = targetSchema.tables[inbound.childTable]
                ?.columns?.filterValues { typeMapper.isUnkeyable(it.type) }?.keys.orEmpty()
            val clause = columnHelper
                .generateConstraintClause(inbound.childTable, inbound.constraint, childUnkeyable, notes, known)
                ?: return null
            statements += "ALTER TABLE ${ctx.sql.quote(inbound.childTable)} ADD $clause;"
        }
        return statements
    }

    /**
     * Die benannten Spalten-Constraints (`UNIQUE`, Enum-CHECK) unter ihren
     * echten Namen — die Zwischentabelle traegt sie nicht.
     *
     * Uebersprungen wird, was die Tabelle schon als eigenen Constraint fuehrt:
     * der Reverse liefert eine UNIQUE-Spalte in **beiden** Formen, und zweimal
     * angelegt antwortet Oracle mit `ORA-02261`.
     */
    private fun columnLevelConstraints(
        table: String,
        target: TableDefinition,
        targetSchema: SchemaDefinition,
        ctx: OracleDiffRenderContext,
    ): List<String> {
        val alreadyConstrained = target.constraints
            .filter { it.type == ConstraintType.UNIQUE }
            .mapNotNull { it.columns?.singleOrNull() }
            .toSet() + setOfNotNull(target.primaryKey.singleOrNull())
        return target.columns.inOrdinalOrder().flatMap { (name, col) ->
            val skipUnique = name in alreadyConstrained
            columnHelper
                .columnLevelConstraintClauses(table, name, if (skipUnique) col.copy(unique = false) else col, targetSchema)
                .map { "ALTER TABLE ${ctx.sql.quote(table)} ADD $it;" }
        }
    }

    /**
     * `START WITH LIMIT VALUE` setzt den Zaehler auf den groessten vorhandenen
     * Wert plus Schrittweite — genau das, was der Neubau braucht, damit der
     * naechste Insert nicht auf einen kopierten Schluessel laeuft.
     */
    private fun reseedStatement(
        table: String,
        column: String,
        mode: IdentityMode,
        ctx: OracleDiffRenderContext,
    ): String {
        val modeSql = if (mode == IdentityMode.ALWAYS) "ALWAYS" else "BY DEFAULT"
        return "ALTER TABLE ${ctx.sql.quote(table)} MODIFY ${ctx.sql.quote(column)} " +
            "GENERATED $modeSql AS IDENTITY (START WITH LIMIT VALUE);"
    }

    /**
     * Die Kopie. Eine Zielspalte ohne Quelle wird aus ihrem Default gefuellt —
     * die Zwischentabelle traegt zu diesem Zeitpunkt keinen, der Wert muss
     * also im `SELECT` stehen.
     */
    private fun copyStatement(
        table: String,
        temp: String,
        target: TableDefinition,
        source: TableDefinition,
        bucket: List<DiffOperation>,
        ctx: OracleDiffRenderContext,
    ): String {
        val sources = OracleRebuildPlanner.columnSources(source, target, bucket, ctx.direction)
        val targetCols = sources.joinToString(", ") { (name, _) -> ctx.sql.quote(name) }
        val selectList = sources.joinToString(", ") { (name, origin) ->
            when (origin) {
                is OracleRebuildPlanner.ColumnSource.From -> ctx.sql.quote(origin.column)
                OracleRebuildPlanner.ColumnSource.Fill ->
                    target.columns[name]?.default
                        ?.let { typeMapper.toDefaultSql(it, target.columns.getValue(name).type) }
                        ?: "NULL"
            }
        }
        return "INSERT INTO ${ctx.sql.quote(temp)} ($targetCols) SELECT $selectList FROM ${ctx.sql.quote(table)};"
    }

    private fun block(
        bucket: List<DiffOperation>,
        ctx: OracleDiffRenderContext,
        message: String,
        code: String,
        reason: MigrationBlockedReason,
    ) {
        bucket.forEach { ctx.skip(it, message, code) }
        ctx.addBlocker(reason, bucket.map { it.id }.toSet())
    }
}
