package dev.dmigrate.driver

import io.kotest.assertions.withClue
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import io.kotest.matchers.string.shouldStartWith

class DdlScriptTest : FunSpec({

    val result = DdlResult(
        listOf(
            DdlStatement("-- Generated by d-migrate\n-- Target: mssql"),
            DdlStatement("CREATE TABLE [t] (\n    [id] INT\n);"),
            DdlStatement("", notes = listOf(TransformationNote(NoteType.WARNING, "W100", "x", "note only"))),
            DdlStatement("CREATE OR ALTER VIEW [v] AS\nSELECT 1;", phase = DdlPhase.POST_DATA),
        ),
    )

    test("dialects without batch semantics render exactly like DdlResult.render()") {
        for (dialect in listOf(DatabaseDialect.POSTGRESQL, DatabaseDialect.MYSQL, DatabaseDialect.SQLITE)) {
            DdlScript.render(result, dialect) shouldBe result.render()
            DdlScript.renderPhase(result, DdlPhase.POST_DATA, dialect) shouldBe result.renderPhase(DdlPhase.POST_DATA)
            DdlScript.render(result, dialect) shouldNotContain "GO"
        }
    }

    test("mssql scripts open with the SET-option preamble batch") {
        val script = DdlScript.render(result, DatabaseDialect.MSSQL)
        script shouldStartWith "SET ANSI_NULLS ON;\n"
        script shouldContain "SET QUOTED_IDENTIFIER ON;\nGO\n\n"
        // Ohne die Praeambel scheitert `CREATE INDEX … WHERE` unter sqlcmd (Msg 1934).
        DialectCapabilities.forDialect(DatabaseDialect.MSSQL).scriptPreamble!! shouldContain "SET ARITHABORT ON;"
        listOf(DatabaseDialect.POSTGRESQL, DatabaseDialect.MYSQL, DatabaseDialect.SQLITE).forEach {
            DialectCapabilities.forDialect(it).scriptPreamble shouldBe null
        }
    }

    test("mssql scripts end every executable statement with its own GO batch; comments carry none") {
        DdlScript.render(result, DatabaseDialect.MSSQL) shouldBe
            DialectCapabilities.forDialect(DatabaseDialect.MSSQL).scriptPreamble + "\nGO\n\n" +
            "-- Generated by d-migrate\n-- Target: mssql\n\n" +
            "CREATE TABLE [t] (\n    [id] INT\n);\nGO\n\n" +
            "-- [W100] note only\n\n" +
            "CREATE OR ALTER VIEW [v] AS\nSELECT 1;\nGO"
        DdlScript.renderPhase(result, DdlPhase.POST_DATA, DatabaseDialect.MSSQL) shouldBe
            DialectCapabilities.forDialect(DatabaseDialect.MSSQL).scriptPreamble + "\nGO\n\n" +
            "CREATE OR ALTER VIEW [v] AS\nSELECT 1;\nGO"
    }

    // Ueber ALLE Dialekte, nicht ueber eine Aufzaehlung: die frueher hier
    // stehende Liste nannte PG/MySQL/SQLite einzeln, sodass Oracle beim
    // Hinzukommen unbemerkt einen Trenner bekommen konnte -- und bekam
    // (`/`, was in SQL*Plus die Anweisung ein zweites Mal ausfuehrt).
    test("mssql is the only dialect with a batch separator") {
        DialectCapabilities.forDialect(DatabaseDialect.MSSQL).batchSeparator shouldBe "GO"
        (DatabaseDialect.entries - DatabaseDialect.MSSQL).forEach {
            withClue("dialect=$it") {
                DialectCapabilities.forDialect(it).batchSeparator shouldBe null
            }
        }
    }

    // ── Trenner je Anweisung ──────────────────────

    val plsql = DdlResult(
        listOf(
            DdlStatement("CREATE TABLE \"t\" (\"id\" NUMBER);"),
            DdlStatement(
                "CREATE OR REPLACE FUNCTION \"f\" RETURN NUMBER IS\nBEGIN RETURN 1; END;",
                scriptTerminator = "/",
            ),
        ),
    )

    test("a statement's own terminator applies in a dialect without a batch separator") {
        // SQL*Plus erkennt das Ende eines PL/SQL-Blocks nur an einem `/` in
        // eigener Zeile; die Tabelle daneben braucht keins.
        DdlScript.render(plsql, DatabaseDialect.ORACLE) shouldBe
            "CREATE TABLE \"t\" (\"id\" NUMBER);\n\n" +
            "CREATE OR REPLACE FUNCTION \"f\" RETURN NUMBER IS\nBEGIN RETURN 1; END;\n/"
    }

    test("the terminator belongs to the script, never to the statement's SQL") {
        // Ueber JDBC gesendet meldet ein angehaengtes `/` Erfolg und laesst die
        // Routine INVALID zurueck.
        plsql.statements.forEach { it.sql shouldNotContain "\n/" }
    }

    test("a statement terminator wins over the dialect's batch separator") {
        DdlScript.render(plsql, DatabaseDialect.MSSQL) shouldContain
            "BEGIN RETURN 1; END;\n/"
    }
})
