package dev.dmigrate.driver

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import io.kotest.matchers.string.shouldStartWith

class DdlScriptTest : FunSpec({

    val result = DdlResult(
        listOf(
            DdlStatement("-- Generated by d-migrate\n-- Target: mssql"),
            DdlStatement("CREATE TABLE [t] (\n    [id] INT\n);"),
            DdlStatement("", notes = listOf(TransformationNote(NoteType.WARNING, "W100", "x", "note only"))),
            DdlStatement("CREATE OR ALTER VIEW [v] AS\nSELECT 1;", phase = DdlPhase.POST_DATA),
        ),
    )

    test("dialects without batch semantics render exactly like DdlResult.render()") {
        for (dialect in listOf(DatabaseDialect.POSTGRESQL, DatabaseDialect.MYSQL, DatabaseDialect.SQLITE)) {
            DdlScript.render(result, dialect) shouldBe result.render()
            DdlScript.renderPhase(result, DdlPhase.POST_DATA, dialect) shouldBe result.renderPhase(DdlPhase.POST_DATA)
            DdlScript.render(result, dialect) shouldNotContain "GO"
        }
    }

    test("mssql scripts open with the SET-option preamble batch") {
        val script = DdlScript.render(result, DatabaseDialect.MSSQL)
        script shouldStartWith "SET ANSI_NULLS ON;\n"
        script shouldContain "SET QUOTED_IDENTIFIER ON;\nGO\n\n"
        // Ohne die Praeambel scheitert `CREATE INDEX … WHERE` unter sqlcmd (Msg 1934).
        DialectCapabilities.forDialect(DatabaseDialect.MSSQL).scriptPreamble!! shouldContain "SET ARITHABORT ON;"
        listOf(DatabaseDialect.POSTGRESQL, DatabaseDialect.MYSQL, DatabaseDialect.SQLITE).forEach {
            DialectCapabilities.forDialect(it).scriptPreamble shouldBe null
        }
    }

    test("mssql scripts end every executable statement with its own GO batch; comments carry none") {
        DdlScript.render(result, DatabaseDialect.MSSQL) shouldBe
            DialectCapabilities.forDialect(DatabaseDialect.MSSQL).scriptPreamble + "\nGO\n\n" +
            "-- Generated by d-migrate\n-- Target: mssql\n\n" +
            "CREATE TABLE [t] (\n    [id] INT\n);\nGO\n\n" +
            "-- [W100] note only\n\n" +
            "CREATE OR ALTER VIEW [v] AS\nSELECT 1;\nGO"
        DdlScript.renderPhase(result, DdlPhase.POST_DATA, DatabaseDialect.MSSQL) shouldBe
            DialectCapabilities.forDialect(DatabaseDialect.MSSQL).scriptPreamble + "\nGO\n\n" +
            "CREATE OR ALTER VIEW [v] AS\nSELECT 1;\nGO"
    }

    test("batchSeparator capability is GO for mssql only") {
        DialectCapabilities.forDialect(DatabaseDialect.MSSQL).batchSeparator shouldBe "GO"
        listOf(DatabaseDialect.POSTGRESQL, DatabaseDialect.MYSQL, DatabaseDialect.SQLITE).forEach {
            DialectCapabilities.forDialect(it).batchSeparator shouldBe null
        }
    }
})
