package dev.dmigrate.driver

/**
 * Options controlling which database object types to include when
 * reading a live schema via [SchemaReader].
 *
 * All flags default to `true`. CLI/IO concerns like output path,
 * format, or report mode do NOT belong here — they are application-layer
 * concerns.
 *
 * Dialect selection is also not part of these options because the dialect
 * is determined by the chosen [DatabaseDriver].
 */
data class SchemaReadOptions(
    val includeViews: Boolean = true,
    val includeProcedures: Boolean = true,
    val includeFunctions: Boolean = true,
    val includeTriggers: Boolean = true,
    /**
     * Declared preference resolving the inherent SQLite AUTOINCREMENT-width
     * ambiguity on reverse: SQLite's `INTEGER PRIMARY KEY AUTOINCREMENT` is a
     * 64-bit rowid and maps equally to the neutral 32-bit `identifier` contract
     * and to 64-bit `biginteger` + `generation: identity`. Only SQLite collapses
     * both (PG/MySQL distinguish by column width), so the tool cannot infer the
     * intent — the user declares it. Default is conservative (no regression);
     * the driver honours it, other readers ignore the field. See the
     * `reverse-preferences` slice / `dialect-preference-mechanism` spec.
     */
    val sqliteAutoincrement: SqliteAutoincrementReverse = SqliteAutoincrementReverse.IDENTIFIER,
    /**
     * Declared preference resolving the second inherent auto-increment
     * ambiguity: whether a legacy auto-increment column that the reverse
     * writes as `generation: identity` (MySQL `AUTO_INCREMENT` on `bigint`,
     * SQLite `AUTOINCREMENT` under the 64-bit width) was meant as a `SERIAL`
     * column or as a SQL-standard IDENTITY column. The database does not
     * record it. Default [AutoIncrementSyntaxReverse.SERIAL] keeps the reverse
     * byte-identical; the MySQL and SQLite readers honour the field, the
     * others ignore it. Unlike [sqliteAutoincrement] the field is
     * dialect-neutral: the caller picks the value for the dialect it reads
     * ([ReversePreferences]). See `spec/dialect-preference-mechanism.md`.
     */
    val autoIncrementSyntax: AutoIncrementSyntaxReverse = AutoIncrementSyntaxReverse.SERIAL,
)

/**
 * How the SQLite reverse renders an AUTOINCREMENT primary key into the neutral
 * model. The user surface is dialect-neutral *width* (`32` | `64`, CLI flag /
 * config `reverse.sqlite.autoincrement_width`); this enum is the internal
 * contract the surface maps onto.
 */
enum class SqliteAutoincrementReverse {
    /** Width 32 — the spec's `identifier` auto-increment contract. Default, conservative. */
    IDENTIFIER,

    /** Width 64 — `biginteger` + `generation: identity`, faithful to SQLite's 64-bit rowid. */
    BIGINTEGER_IDENTITY,
}

/**
 * How a reverse marks a legacy auto-increment column it writes as
 * `generation: identity` — the internal contract behind the config key
 * `reverse.<dialect>.autoincrement_syntax` and the CLI flags
 * `--mysql-autoincrement-syntax` / `--sqlite-autoincrement-syntax`
 * (`serial` | `identity`).
 */
enum class AutoIncrementSyntaxReverse {
    /** `legacy_serial_syntax: true` — PostgreSQL renders `BIGSERIAL`. Default, byte-identical to the reverse without the preference. */
    SERIAL,

    /** No flag — PostgreSQL renders `GENERATED BY DEFAULT AS IDENTITY`. */
    IDENTITY,
}

/**
 * The declared read preferences of a run or a project
 * (`.d-migrate.yaml`, block `reverse:`), resolved once and applied per read:
 * [applyTo] picks the values for the dialect being read. Without a
 * declaration every read keeps the conservative default.
 */
data class ReversePreferences(
    val sqliteAutoincrement: SqliteAutoincrementReverse = SqliteAutoincrementReverse.IDENTIFIER,
    /** Per dialect; a dialect without an entry reads [AutoIncrementSyntaxReverse.SERIAL]. */
    val autoIncrementSyntax: Map<DatabaseDialect, AutoIncrementSyntaxReverse> = emptyMap(),
) {

    /** The syntax preference for a read of [dialect]. */
    fun autoIncrementSyntaxFor(dialect: DatabaseDialect): AutoIncrementSyntaxReverse =
        autoIncrementSyntax[dialect] ?: AutoIncrementSyntaxReverse.SERIAL

    /** [options] with this run's preferences for a read of [dialect]. */
    fun applyTo(options: SchemaReadOptions, dialect: DatabaseDialect): SchemaReadOptions =
        options.copy(
            sqliteAutoincrement = sqliteAutoincrement,
            autoIncrementSyntax = autoIncrementSyntaxFor(dialect),
        )
}
