package dev.dmigrate.driver.postgresql

import dev.dmigrate.core.data.ColumnDescriptor
import dev.dmigrate.driver.DatabaseDialect
import dev.dmigrate.driver.DatabaseDriverRegistry
import dev.dmigrate.driver.connection.ConnectionConfig
import dev.dmigrate.driver.connection.ConnectionPool
import dev.dmigrate.driver.connection.HikariConnectionPoolFactory
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.core.NamedTag
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldContainExactly
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import org.testcontainers.postgresql.PostgreSQLContainer

private val SchemaSyncIntegrationTag = NamedTag("integration")

class PostgresSchemaSyncIntegrationTest : FunSpec({

    tags(SchemaSyncIntegrationTag)

    val container = PostgreSQLContainer("postgres:16-alpine")
        .withDatabaseName("dmigrate_test")
        .withUsername("dmigrate")
        .withPassword("dmigrate")

    var pool: ConnectionPool? = null

    beforeSpec {
        container.start()
        DatabaseDriverRegistry.register(PostgresDriver())

        pool = HikariConnectionPoolFactory.create(
            ConnectionConfig(
                dialect = DatabaseDialect.POSTGRESQL,
                host = container.host,
                port = container.firstMappedPort,
                database = container.databaseName,
                user = container.username,
                password = container.password,
            )
        )

        pool!!.borrow().use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute("CREATE TABLE sync_serial (id SERIAL PRIMARY KEY, name TEXT)")
                stmt.execute(
                    "CREATE TABLE sync_identity_default (" +
                        "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "name TEXT)"
                )
                stmt.execute(
                    "CREATE TABLE sync_identity_always (" +
                        "id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, " +
                        "name TEXT)"
                )
                stmt.execute("CREATE TABLE sync_empty (id SERIAL PRIMARY KEY, name TEXT)")
                stmt.execute("CREATE TABLE sync_trigger_target (id SERIAL PRIMARY KEY, name TEXT)")
                stmt.execute("CREATE TABLE sync_trigger_audit (target_id INT NOT NULL)")
                stmt.execute(
                    """
                    CREATE OR REPLACE FUNCTION sync_trigger_audit_fn()
                    RETURNS trigger AS $$
                    BEGIN
                        INSERT INTO sync_trigger_audit(target_id) VALUES (NEW.id);
                        RETURN NEW;
                    END;
                    $$ LANGUAGE plpgsql
                    """.trimIndent()
                )
                stmt.execute(
                    """
                    CREATE TRIGGER sync_trigger_target_ai
                    AFTER INSERT ON sync_trigger_target
                    FOR EACH ROW
                    EXECUTE FUNCTION sync_trigger_audit_fn()
                    """.trimIndent()
                )
                stmt.execute("CREATE SCHEMA ${quotePostgresIdentifier("Odd Schema")}")
                stmt.execute(
                    "CREATE TABLE ${quotePostgresIdentifier("Odd Schema")}.plain_seq " +
                        "(id SERIAL PRIMARY KEY, name TEXT)"
                )
                stmt.execute(
                    "CREATE TABLE ${quotePostgresIdentifier("Mixed Case Table")} " +
                        "(id SERIAL PRIMARY KEY, name TEXT)"
                )
                stmt.execute(
                    "CREATE TABLE ${quotePostgresIdentifier("Quote \"Table\"")} " +
                        "(id SERIAL PRIMARY KEY, name TEXT)"
                )
            }
        }
    }

    afterSpec {
        pool?.close()
        if (container.isRunning) container.stop()
        DatabaseDriverRegistry.clear()
    }

    beforeTest {
        pool!!.borrow().use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute("TRUNCATE TABLE sync_serial, sync_identity_default, sync_identity_always, sync_empty RESTART IDENTITY CASCADE")
                stmt.execute("TRUNCATE TABLE sync_trigger_target, sync_trigger_audit RESTART IDENTITY CASCADE")
                stmt.execute("TRUNCATE TABLE ${quotePostgresIdentifier("Odd Schema")}.plain_seq RESTART IDENTITY CASCADE")
                stmt.execute("TRUNCATE TABLE ${quotePostgresIdentifier("Mixed Case Table")} RESTART IDENTITY CASCADE")
                stmt.execute("TRUNCATE TABLE ${quotePostgresIdentifier("Quote \"Table\"")} RESTART IDENTITY CASCADE")
            }
        }
    }

    val schemaSync = PostgresSchemaSync()
    val idColumn = listOf(ColumnDescriptor("id", nullable = false))

    test("reseed serial column updates next generated value") {
        pool!!.borrow().use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute("INSERT INTO sync_serial (id, name) VALUES (7, 'manual')")
            }

            val adjustments = schemaSync.reseedGenerators(conn, "sync_serial", idColumn)

            adjustments.single().column shouldBe "id"
            adjustments.single().sequenceName shouldBe "public.sync_serial_id_seq"
            adjustments.single().newValue shouldBe 8

            conn.prepareStatement("INSERT INTO sync_serial (name) VALUES ('next') RETURNING id").use { ps ->
                ps.executeQuery().use { rs ->
                    rs.next() shouldBe true
                    rs.getLong(1) shouldBe 8
                }
            }
        }
    }

    test("reseed generated by default identity") {
        pool!!.borrow().use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute("INSERT INTO sync_identity_default (id, name) VALUES (15, 'manual')")
            }

            val adjustments = schemaSync.reseedGenerators(conn, "sync_identity_default", idColumn)

            adjustments.single().newValue shouldBe 16
            conn.prepareStatement("INSERT INTO sync_identity_default (name) VALUES ('next') RETURNING id").use { ps ->
                ps.executeQuery().use { rs ->
                    rs.next() shouldBe true
                    rs.getLong(1) shouldBe 16
                }
            }
        }
    }

    test("reseed generated always identity") {
        pool!!.borrow().use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(
                    "INSERT INTO sync_identity_always (id, name) " +
                        "OVERRIDING SYSTEM VALUE VALUES (25, 'manual')"
                )
            }

            val adjustments = schemaSync.reseedGenerators(conn, "sync_identity_always", idColumn)

            adjustments.single().newValue shouldBe 26
            conn.prepareStatement("INSERT INTO sync_identity_always (name) VALUES ('next') RETURNING id").use { ps ->
                ps.executeQuery().use { rs ->
                    rs.next() shouldBe true
                    rs.getLong(1) shouldBe 26
                }
            }
        }
    }

    test("no adjustment when max is null") {
        pool!!.borrow().use { conn ->
            schemaSync.reseedGenerators(conn, "sync_empty", idColumn) shouldBe emptyList()
        }
    }

    test("disable trigger mode uses disable trigger user") {
        pool!!.borrow().use { conn ->
            schemaSync.disableTriggers(conn, "sync_trigger_target")
            conn.createStatement().use { stmt ->
                stmt.execute("INSERT INTO sync_trigger_target (name) VALUES ('disabled')")
            }

            conn.prepareStatement("SELECT COUNT(*) FROM sync_trigger_audit").use { ps ->
                ps.executeQuery().use { rs ->
                    rs.next() shouldBe true
                    rs.getLong(1) shouldBe 0
                }
            }
        }
    }

    test("strict mode fails when table has user trigger") {
        pool!!.borrow().use { conn ->
            val ex = shouldThrow<IllegalStateException> {
                schemaSync.assertNoUserTriggers(conn, "sync_trigger_target")
            }

            ex.message.shouldContain("sync_trigger_target_ai")
        }
    }

    test("enable triggers is executed after disable path") {
        pool!!.borrow().use { conn ->
            schemaSync.disableTriggers(conn, "sync_trigger_target")
            schemaSync.enableTriggers(conn, "sync_trigger_target")

            conn.createStatement().use { stmt ->
                stmt.execute("INSERT INTO sync_trigger_target (name) VALUES ('enabled')")
            }

            conn.prepareStatement("SELECT target_id FROM sync_trigger_audit ORDER BY target_id").use { ps ->
                ps.executeQuery().use { rs ->
                    val targetIds = mutableListOf<Long>()
                    while (rs.next()) {
                        targetIds += rs.getLong(1)
                    }
                    targetIds shouldContainExactly listOf(1L)
                }
            }
        }
    }

    test("pg_get_serial_sequence quoting works for non public schema") {
        pool!!.borrow().use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(
                    "INSERT INTO ${quotePostgresIdentifier("Odd Schema")}.plain_seq (id, name) " +
                        "VALUES (31, 'manual')"
                )
            }

            val adjustments = schemaSync.reseedGenerators(conn, "Odd Schema.plain_seq", idColumn)

            adjustments.single().newValue shouldBe 32
            conn.prepareStatement(
                "INSERT INTO ${quotePostgresIdentifier("Odd Schema")}.plain_seq (name) VALUES ('next') RETURNING id"
            ).use { ps ->
                ps.executeQuery().use { rs ->
                    rs.next() shouldBe true
                    rs.getLong(1) shouldBe 32
                }
            }
        }
    }

    test("pg_get_serial_sequence quoting works for whitespace and mixed case") {
        pool!!.borrow().use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(
                    "INSERT INTO ${quotePostgresIdentifier("Mixed Case Table")} (id, name) VALUES (41, 'manual')"
                )
            }

            val adjustments = schemaSync.reseedGenerators(conn, "Mixed Case Table", idColumn)

            adjustments.single().newValue shouldBe 42
            conn.prepareStatement(
                "INSERT INTO ${quotePostgresIdentifier("Mixed Case Table")} (name) VALUES ('next') RETURNING id"
            ).use { ps ->
                ps.executeQuery().use { rs ->
                    rs.next() shouldBe true
                    rs.getLong(1) shouldBe 42
                }
            }
        }
    }

    test("pg_get_serial_sequence quoting escapes embedded double quotes") {
        pool!!.borrow().use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(
                    "INSERT INTO ${quotePostgresIdentifier("Quote \"Table\"")} (id, name) VALUES (51, 'manual')"
                )
            }

            val adjustments = schemaSync.reseedGenerators(conn, "Quote \"Table\"", idColumn)

            adjustments.single().newValue shouldBe 52
            conn.prepareStatement(
                "INSERT INTO ${quotePostgresIdentifier("Quote \"Table\"")} (name) VALUES ('next') RETURNING id"
            ).use { ps ->
                ps.executeQuery().use { rs ->
                    rs.next() shouldBe true
                    rs.getLong(1) shouldBe 52
                }
            }
        }
    }
})
