package dev.dmigrate.driver.postgresql

import dev.dmigrate.core.model.ColumnGeneration
import dev.dmigrate.core.model.IdentityMode
import dev.dmigrate.core.model.NeutralType
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.nulls.shouldNotBeNull
import io.kotest.matchers.shouldBe
import io.kotest.matchers.types.shouldBeInstanceOf

/**
 * Eine Identity-Spalte, die **nicht** im Primaerschluessel liegt.
 *
 * Zwei Zweige des Mappers fingen sie: der erste nur `bigint`, der zweite nur
 * den Primaerschluessel (dort traegt der Typ `Identifier(autoIncrement = true)`
 * die Angabe). Ein `integer GENERATED BY DEFAULT AS IDENTITY` ohne Schluessel
 * fiel zwischen beide und kam als gewoehnliches `Integer` zurueck -- live gegen
 * 18.6 gemessen, siehe `PostgresIdentityShapeIntegrationTest`.
 */
class PostgresNonPkIdentityMappingTest : FunSpec({

    fun map(dataType: String, udt: String, isPk: Boolean, mode: String?) =
        PostgresTypeMapping.mapColumn(
            PostgresTypeMapping.ColumnInput(
                dataType = dataType,
                udtName = udt,
                isPkCol = isPk,
                isIdentity = mode != null,
                identityGeneration = mode,
                colDefault = null,
                generatedSequenceName = null,
                charMaxLen = null,
                numPrecision = null,
                numScale = null,
                tableName = "t",
                colName = "c",
                geometrySubtype = null,
                geometrySrid = null,
            ),
        )

    test("a non-PK integer identity keeps its type and carries the identity") {
        val mapped = map("integer", "int4", isPk = false, mode = "BY DEFAULT")
        mapped.type shouldBe NeutralType.Integer
        val identity = mapped.generation as? ColumnGeneration.Identity
        identity.shouldNotBeNull()
        identity.mode shouldBe IdentityMode.BY_DEFAULT
    }

    test("the ALWAYS mode comes through as well") {
        val mapped = map("smallint", "int2", isPk = false, mode = "ALWAYS")
        mapped.type shouldBe NeutralType.SmallInt
        (mapped.generation as? ColumnGeneration.Identity)?.mode shouldBe IdentityMode.ALWAYS
    }

    // S1 (Reader-Plan 2): `ALWAYS` im Primaerschluessel faltet **nicht** mehr
    // auf `identifier`. Der Typ traegt keinen Modus und rendert als `SERIAL`,
    // das gesetzte Werte annimmt — der Verlust waere schon PostgreSQL →
    // PostgreSQL entstanden, und kein Vergleich zweier Reverses saehe ihn.
    test("the PK with ALWAYS keeps its base type and its mode") {
        val mapped = map("integer", "int4", isPk = true, mode = "ALWAYS")
        mapped.type shouldBe NeutralType.Integer
        (mapped.generation as? ColumnGeneration.Identity)?.mode shouldBe IdentityMode.ALWAYS
    }

    // Gegenprobe: `BY DEFAULT` behaelt den `identifier`-Vertrag — dort
    // verspricht das Modell nichts, was das Rendern bricht.
    test("the PK with BY DEFAULT keeps the folded spelling in the type") {
        val mapped = map("integer", "int4", isPk = true, mode = "BY DEFAULT")
        mapped.type.shouldBeInstanceOf<NeutralType.Identifier>()
        mapped.generation shouldBe null
    }

    // H1 (Eigner, 2026-09-18): der Zweig greift **nur** fuer `integer`.
    // `smallint` + `identity` gibt es im Modell nicht (`E130`), und der
    // PostgreSQL-Generator rendert es nicht — als `smallint` gelesen
    // braeche `schema generate` aus dem eigenen Reverse ab. Der Verlust
    // bleibt hier, ohne Code; die Frage nach den Breiten liegt in Plan 3.
    test("a smallint PK with ALWAYS keeps the identifier contract") {
        val mapped = map("smallint", "int2", isPk = true, mode = "ALWAYS")
        mapped.type.shouldBeInstanceOf<NeutralType.Identifier>()
        mapped.generation shouldBe null
    }

    // M3: der Reader unterscheidet nicht, ob die Spalte den Schluessel
    // **allein** bildet — `isPkCol` sagt nur, dass sie zu ihm gehoert. Ein
    // Mitglied eines mehrspaltigen Schluessels liest deshalb genauso.
    // `spec/type-mapping.md` 3.4 traegt diese Lesart.
    test("a member of a composite PK reads like a sole one") {
        val always = map("integer", "int4", isPk = true, mode = "ALWAYS")
        always.type shouldBe NeutralType.Integer
        (always.generation as? ColumnGeneration.Identity)?.mode shouldBe IdentityMode.ALWAYS

        val byDefault = map("integer", "int4", isPk = true, mode = "BY DEFAULT")
        byDefault.type.shouldBeInstanceOf<NeutralType.Identifier>()
    }

    test("a bigint identity was never affected — it kept its generation all along") {
        val mapped = map("bigint", "int8", isPk = false, mode = "ALWAYS")
        mapped.type shouldBe NeutralType.BigInteger
        mapped.generation.shouldNotBeNull()
    }

    test("an ordinary integer stays ordinary") {
        val mapped = map("integer", "int4", isPk = false, mode = null)
        mapped.type shouldBe NeutralType.Integer
        mapped.generation shouldBe null
    }
})
