package dev.dmigrate.cli

import dev.dmigrate.core.diff.SchemaComparator
import dev.dmigrate.driver.DatabaseDialect
import dev.dmigrate.driver.connection.ConnectionConfig
import dev.dmigrate.driver.connection.ConnectionPool
import dev.dmigrate.driver.connection.HikariConnectionPoolFactory
import dev.dmigrate.driver.connection.asJdbc
import dev.dmigrate.driver.mssql.MssqlSchemaReader
import dev.dmigrate.driver.postgresql.PostgresSchemaReader
import dev.dmigrate.test.containers.newMssqlContainer
import dev.dmigrate.test.images.TestImages
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldNotBeEmpty
import io.kotest.matchers.shouldBe
import org.testcontainers.containers.Container
import org.testcontainers.mssqlserver.MSSQLServerContainer
import org.testcontainers.postgresql.PostgreSQLContainer

/**
 * Die Kette, die einen Konsumenten-Fehlalarm erzeugt hat: **zwei echte Server,
 * beide zurueckgelesen, dann verglichen.**
 *
 * Der Fall kam aus einem Konsumentenprojekt, das zwei Reverses verschiedener
 * Dialekte gegeneinander hielt und 38 % Falsch-Positive maß. Zwei der Ursachen
 * lagen im **Reader** (`NO ACTION` explizit vs. weggelassen) — die konnte kein
 * Comparator-Test finden, weil er die Schemata schon fertig konstruiert. Diese
 * Spec faehrt deshalb den ganzen Weg.
 *
 * Die Trennung ist der Punkt, und sie ist im Test festgehalten: **nicht jeder
 * Fund ist ein Fehlalarm.** Was die Gegenseite wirklich nicht hat — hier die
 * UNIQUE-Constraint auf einer `TEXT`-Spalte, die SQL Server als
 * `NVARCHAR(MAX)` liest und darum nicht indizieren kann (E057) —, ist die
 * Wahrheit und muss gemeldet bleiben. Wer das mitzaehlt, ueberschaetzt die
 * Quote.
 */
class CrossDialectReverseCompareE2ETest : FunSpec({

    val pg = PostgreSQLContainer(TestImages.POSTGRESQL)
        .withDatabaseName("cross_dialect").withUsername("dmigrate").withPassword("dmigrate")

    val mssql = newMssqlContainer().withPassword(MSSQL_PASSWORD)

    lateinit var pgPool: ConnectionPool
    lateinit var mssqlPool: ConnectionPool

    beforeSpec {
        pg.start()
        mssql.start()
        pgPool = HikariConnectionPoolFactory.create(
            ConnectionConfig(
                dialect = DatabaseDialect.POSTGRESQL, host = pg.host, port = pg.firstMappedPort,
                database = pg.databaseName, user = pg.username, password = pg.password,
            ),
        )
        mssqlPool = HikariConnectionPoolFactory.create(
            ConnectionConfig(
                dialect = DatabaseDialect.MSSQL, host = mssql.host,
                port = mssql.getMappedPort(MSSQLServerContainer.MS_SQL_SERVER_PORT),
                database = "master", user = mssql.username, password = MSSQL_PASSWORD,
                params = mapOf("encrypt" to "false"),
            ),
        )
        mssqlPool.borrow().asJdbc().use { conn ->
            conn.createStatement().use { it.execute("CREATE DATABASE cross_dialect") }
        }
        mssqlPool.close()
        mssqlPool = HikariConnectionPoolFactory.create(
            ConnectionConfig(
                dialect = DatabaseDialect.MSSQL, host = mssql.host,
                port = mssql.getMappedPort(MSSQLServerContainer.MS_SQL_SERVER_PORT),
                database = "cross_dialect", user = mssql.username, password = MSSQL_PASSWORD,
                params = mapOf("encrypt" to "false"),
            ),
        )

        pgPool.borrow().asJdbc().use { conn ->
            conn.createStatement().use { st ->
                st.execute("CREATE TABLE customers (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email text NOT NULL)")
                // Ein **benanntes** UNIQUE an der Spalte — der Pfad, den ein Reverse nimmt.
                st.execute("ALTER TABLE customers ADD CONSTRAINT uq_customer_email UNIQUE (email)")
                st.execute("CREATE TABLE orders (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id bigint NOT NULL)")
                st.execute(
                    "ALTER TABLE orders ADD CONSTRAINT orders_customer_id_fkey " +
                        "FOREIGN KEY (customer_id) REFERENCES customers (id)",
                )
            }
        }
        mssql.execInContainer(
            "/opt/mssql-tools18/bin/sqlcmd", "-C", "-S", "localhost", "-U", mssql.username,
            "-P", MSSQL_PASSWORD, "-d", "cross_dialect", "-Q",
            "CREATE TABLE customers (id BIGINT IDENTITY(1,1) PRIMARY KEY, email NVARCHAR(MAX) NOT NULL); " +
                "CREATE TABLE orders (id BIGINT IDENTITY(1,1) PRIMARY KEY, customer_id BIGINT NOT NULL " +
                "CONSTRAINT orders_customer_id_fkey FOREIGN KEY REFERENCES customers(id) ON DELETE NO ACTION);",
        )
    }

    afterSpec {
        runCatching { pgPool.close() }
        runCatching { mssqlPool.close() }
        pg.stop()
        mssql.stop()
    }

    fun sqlcmd(sql: String): Container.ExecResult = mssql.execInContainer(
        "/opt/mssql-tools18/bin/sqlcmd", "-C", "-S", "localhost", "-U", mssql.username,
        "-P", MSSQL_PASSWORD, "-d", "cross_dialect", "-Q", sql,
    )

    fun foreignKeyChanges(): List<String> {
        val pgSchema = PostgresSchemaReader().read(pgPool).schema
        val mssqlSchema = MssqlSchemaReader().read(mssqlPool).schema
        val diff = SchemaComparator().compare(pgSchema, mssqlSchema)
        return diff.tablesChanged
            .flatMap { it.constraintsChanged }
            .filter { it.before.type.name == "FOREIGN_KEY" }
            .map { it.before.name }
    }

    /**
     * **Der Fehlalarm, um den es ging.** SQL Server meldet `ON DELETE NO ACTION`
     * explizit aus dem Katalog, PostgreSQL laesst die Aktion weg. Vor dem Fix
     * galt der Fremdschluessel dadurch als geaendert, obwohl beide Seiten
     * dieselbe Zusicherung tragen.
     */
    test("a foreign key is not reported as changed just because MSSQL spells NO ACTION") {
        mssqlPool.borrow().asJdbc().use { conn ->
            conn.createStatement().use { st ->
                st.executeQuery(
                    "SELECT delete_referential_action_desc FROM sys.foreign_keys " +
                        "WHERE name = 'orders_customer_id_fkey'",
                ).use { rs ->
                    rs.next() shouldBe true
                    // Vorbedingung: der Katalog sagt wirklich NO_ACTION.
                    rs.getString(1) shouldBe "NO_ACTION"
                }
            }
        }
        foreignKeyChanges().shouldBeEmpty()
    }

    /**
     * **Die Gegenprobe.** Eine UNIQUE-Constraint auf einer unbegrenzten
     * Textspalte kann SQL Server nicht anlegen (`NVARCHAR(MAX)` ist kein
     * zulaessiger Schluessel, E057) — sie fehlt dort also wirklich. Der
     * Vergleich meldet das zu Recht; wer es als Falsch-Positiv zaehlt,
     * ueberschaetzt die Quote.
     */
    test("a constraint the other side genuinely lacks is still reported") {
        val pgSchema = PostgresSchemaReader().read(pgPool).schema
        val mssqlSchema = MssqlSchemaReader().read(mssqlPool).schema

        mssqlSchema.tables.getValue("customers").constraints.map { it.name }.shouldBeEmpty()

        val diff = SchemaComparator().compare(pgSchema, mssqlSchema)
        diff.tablesChanged.flatMap { it.constraintsRemoved }.map { it.name }.shouldNotBeEmpty()
    }

    /**
     * Und die Gegenrichtung: ein **echter** Unterschied wird weiterhin
     * gemeldet. Ohne das waere der Fix ein Freibrief, alles zu glaetten.
     */
    test("a real foreign-key action difference is still reported") {
        sqlcmd("ALTER TABLE orders DROP CONSTRAINT orders_customer_id_fkey").exitCode shouldBe 0
        sqlcmd(
            "ALTER TABLE orders ADD CONSTRAINT orders_customer_id_fkey " +
                "FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE",
        ).exitCode shouldBe 0

        foreignKeyChanges() shouldBe listOf("orders_customer_id_fkey")

        // Zurueckbauen, damit die Reihenfolge der Tests keine Rolle spielt.
        sqlcmd("ALTER TABLE orders DROP CONSTRAINT orders_customer_id_fkey").exitCode shouldBe 0
        sqlcmd(
            "ALTER TABLE orders ADD CONSTRAINT orders_customer_id_fkey " +
                "FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE NO ACTION",
        ).exitCode shouldBe 0
    }
})

private const val MSSQL_PASSWORD = "DMigrate_CrossDialect_Pa55word"
